### ISSUE TITLE
Force SSL login doesn't work

### ISSUE THREAD

**Issue by schwindelbub** [piwik/piwik#10041]
Hi everybody,

in my configuration the parameter "force_ssl" has no effect.

May be the server constellation is guilty?
I use an nginx proxy in front of the apache.

```
Apache/2.4.6 (CentOS) on port 34282
nginx/1.6.3 on port 80 and 443
PHP 5.6.20
```

Has anybody an similar problem? Or a solution for that problem?

Best regards,
Schwindelbub

**Comment by tsteur** [comment]
For force_ssl see http://piwik.org/faq/how-to/faq_91/ 

If your server is behind a proxy you might have to set `assume_secure_protocol =1` or do more configuration see http://piwik.org/faq/how-to-install/faq_98/

What is otherwise not working? Are you not redirect to https when accessing the page with http?

**Comment by schwindelbub** [comment]
Yes, the redirect doesn't work. And in addition: If the loginpage ist non-HTTP the login doesn't occured against the HTTPS.
And of course i added the `force_ssl = 1` parameter. On the other hand: there is no diffrent with `assume_secure_protocol = 1` or even `proxy_client_headers[] = HTTP_X_FORWARDED_FOR` or `proxy_host_headers[] = HTTP_X_FORWARDED_HOST`

**Comment by tsteur** [comment]
What's your server setup? Are there any proxies or so?  I just realized `assume_secure_protocol` doesn't make much sense in this case. Maybe one of your servers is requesting the actual Piwik via HTTPS and Piwik can't detect that it's being used via HTTP

**Comment by schwindelbub** [comment]
There is of course a proxy: https://github.com/piwik/piwik/issues/10041#issue-147652117
Thats the main question ...

**Comment by tsteur** [comment]
Is the proxy requesting Piwik via HTTPS? Does the proxy set `HTTP_X_FORWARDED_PROTO` header? The proxy will need to forward the original protocol otherwise Piwik can't know whether it's requested via HTTP or HTTPS and therefore cannot redirect to SSL page correctly. 

I think even if it does there might be a bug. @mattab what do you think about changing

```php
    protected static function getCurrentSchemeFromRequestHeader()
    {
        if ((isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] === true))
            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
        ) {

            return 'https';
        }
        return 'http';
    }
```

to 

```php
    protected static function getCurrentSchemeFromRequestHeader()
    {
        if ((isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'http')) {
            return 'http';
        }

        if ((isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] === true))
            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
        ) {

            return 'https';
        }
        return 'http';
    }
```

This would fix the problem when Piwik is requested via HTTP, then goes to a proxy which requests Piwik with `https='on', 'forwarded_proto='http'. In current case we would still think it is requested via HTTPS but it was actually HTTP

**Comment by schwindelbub** [comment]
The Nginx is the entrypoint, is encrypting and sets `X_Forwarded-Proto $scheme`
`SetEnv HTTPS on` is set in the vhost of the apache in the background.

**Comment by tsteur** [comment]
I don't think `SetEnv HTTPS on` should be set on the apache in the background. It cannot know that actually HTTP is used and therefore not force a redirect to https. 
We still need to change the above mentioned method likely to make it actually work.

**Comment by mattab** [comment]
Hi @schwindelbub please  open a new issue if you still experience a problem with Piwik 2.16.2 beta: http://piwik.org/faq/how-to-update/faq_159/
