### ISSUE TITLE
Make UI tests more stable: Remove top controls from screenshots

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10084]
In the last two weeks I've seen one UI test failing randomly: http://builds-artifacts.piwik.org/piwik/piwik/master/18770/UIIntegrationTest_goals_overview.png

When It randomly fails, it always seems to fail with some few pixels difference in the rendering of a top control.

UI tests don't need to test for top controls most of the time, since top controls such as segment selector, calendar, site selector are UI tested separately in specific UI test suites.

Here is suggested approach:
* For this goals_overview.png we remove the top controls and take a screenshot of the main page / reports only.
* we could look at other UI tests that have top controls and change them to take a screenshot of the report only. 

Overall, this will make our UI tests failing less often for unrelated changes, and also will help minimise this occurrence of a random UI test failure.

**Comment by tsteur** [comment]
Ideally we would check if we can fix it somehow. The top controls test have been quite useful in the past when redesigning and making sure correct controls are still shown. Because of this I fixed many bugs that I would otherwise not have noticed, seriously. We should at least still make sure they are shown in the UI with some text. 

A rough idea why they randomly fail: There are methods calling `initTopControl` a couple of times in the code and they change the position of each control from time to time when the screen is loaded. This has been there for quite a while and it may capture pictures while this code is running and adjusting the left position. Ideally we make them more "responsive" and all this would not be needed anymore https://github.com/piwik/piwik/issues/9100

**Comment by mattab** [comment]
Ok @tsteur  closing as wont fix for now.
