### ISSUE TITLE
Piwik UI is takes a lot of time to load.

### ISSUE THREAD

**Issue by arvindsarangi14** [piwik/piwik#10138]
Hi team,

The first dashboard screen loads very quickly but when it comes to any other screen it takes around 2-3 mins to load the screen. I am currently using Piwik 2.16.0 and this was not a problem 2.14.x.

Could you please let me know why this happening?

**Comment by tsteur** [comment]
Have you configured auto-archiving? http://piwik.org/docs/setup-auto-archiving/

**Comment by arvindsarangi14** [comment]
`*/20 * * * * /app/php-5.5.30/bin/php /app/apache2/htdocs/analytics/piwik/console core:archive --url=http://mchp484a.global-intra.net:8080/analytics/piwik/ > /usr/local/apache2/logs/piwik-archive.log 2> /usr/local/apache2/logs/piwik-archive-errors.log`
I have this configured but the page loads are still slow

**Comment by tsteur** [comment]
It is also important that browser archiving is disabled see http://piwik.org/docs/setup-auto-archiving/#disable-browser-triggers-for-piwik-archiving-and-limit-piwik-reports-to-updating-every-hour . Otherwise it still tries to archive data. Is it faster when you view reports in the past? 

It's hard to tell why it is slow as there could be many reasons. Can you maybe check in the Browser developer tools in the network tab which request is particularly slow or whether it is many?

**Comment by arvindsarangi14** [comment]
`http://mchp484a.global-intra.net:8080/analytics/piwik/index.php?module=UsersManager&action=index&idSite=1&period=day&date=today` this is taking 2 mins to load.
![capture](https://cloud.githubusercontent.com/assets/16887541/15240807/be8327be-1909-11e6-8e02-627f0adc502c.JPG)

Also i have disabled browser archiving.

**Comment by mattab** [comment]
How many users do you have in your piwik?
Could you maybe paste your archive log output here?
(A ultimate solution would be to install XHPROF on your server and generate a XHProf so we can see where the time is spent exactly.)
