### ISSUE TITLE
Heartbeat Timer and New Visit Bug

### ISSUE THREAD

**Issue by curricula** [piwik/piwik#10140]
When manually adding the new visit flag ( on the the initial visit only ) combined with using the heartbeat timer, no duration is recorded for the visit. Unless you hit fresh or click onto some other page.

`_paq.push(['enableHeartBeatTimer', 30]);
_paq.push(['appendToTrackingUrl', 'new_visit=1']);
_paq.push(["deleteCookies"]);
_paq.push(['trackPageView']);`

**Comment by tsteur** [comment]
This might be similar to https://github.com/piwik/piwik/issues/10112 . There is not really a way yet to trigger a new visit. What you likely need to do is call `_paq.push(['appendToTrackingUrl', '']);` after the pageview was tracked. Otherwise it will be sent with each request and creates a new visit on each tracking request. 

Nonetheless the heart beat feature should still work and record a visit time by looking at the code but this will only work if a user spent actually more than 30 seconds on the page.

**Comment by hpvd** [comment]
@curricula
fyi:
with
_paq.push(['enableHeartBeatTimer', 5]);
on can set the duration of heartbeat-timer to 5s - but one should have alook on server load...
see
https://developer.piwik.org/guides/tracking-javascript-guide#accurately-measure-the-time-spent-on-each-page
