### ISSUE TITLE
Piwik Archiving Process is eating up ram

### ISSUE THREAD

**Issue by FarhadF** [piwik/piwik#10194]
Hi guys, 

I am using Piwik in my production environment and everything is working fine. But archiving process is demanding more and more memory. Here is screenshot of the error.
I have currently set 7GB Memroy Limit in php.ini. Is this behavior normal? 

![l_41b tmp](https://cloud.githubusercontent.com/assets/17374492/15647664/4e8a0ab2-267a-11e6-93ec-7fdf8ce9d2b3.PNG)

any help would be appreciated
Regards,
Farhad

**Comment by tsteur** [comment]
Do you know how many actions there were in the last year? 

Can you maybe execute `select count(*), count(distinct idaction_url_ref), count(distinct idaction_name_ref), count(distinct idvisit), count(distinct idvisitor) from piwik_log_link_visit_action where server_time like '2016%' and idsite = 1;`

**Comment by FarhadF** [comment]
Hi,
thanks for the reply, Here are the results.
![image](https://cloud.githubusercontent.com/assets/17374492/15804138/d63ee2be-2b13-11e6-8597-7cfe04828544.png)
any help would be appreciated
Regards,
Farhad

**Comment by tsteur** [comment]
For 28 mio actions it shouldn't take up that much memory I reckon. Maybe having so many different URLs is a problem that lead to more memory consumption. I wonder if it maybe helps to reduce the number of rows in action tables see http://piwik.org/faq/how-to/faq_54/ 

The default value for `datatable_archiving_maximum_rows_actions` is currently 500 and maybe it gets better if you set it to like 300. It might not fix the problem though as the other reports for the past months are already archived. It may be needed to invalidate previously archived month reports and archive them again which might actually not take too long. I can give you some instructions for this. Can you try if it already helps by just setting the config value to eg 300? 

Are you using the latest Piwik 2.16.1 version btw? I currently don't have access to a server with lots of data so I cannot really profile anything currently. Also profiling wouldn't help much as memory consumption is different depending on the metrics above. I presume the problem here is having too many different distinct URLs and action names. Any idea maybe @mattab ?

**Comment by mattab** [comment]
please check you're using latest Piwik version and latest PHP version. After upgrade, do you still have this memory issue?

**Comment by mattab** [comment]
As we have not heard from you, closing the issue. Feel free to comment and re-open if you still experience the issue and have more info.
