### ISSUE TITLE
Some confirms are broken in 3.x

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#10479]
When opening a modal confirm for a specific element, the element is currently moved into the modal box. Closing the box, doesn't move it back, so recreating won't work, as the content can't be found anymore.

To reproduce the failure, simply try to remove a segment, click no, and try it again.

Cloning the content before showning didn't work. See https://github.com/piwik/piwik/pull/10478

**Comment by tsteur** [comment]
I had this tested and it works fine for me but can reproduce it for "remove segment". We should have a look why it fails for this confirm but not for others. I'll have a quick look

**Comment by tsteur** [comment]
Problem is that it uses here https://github.com/piwik/piwik/blob/3.x-dev/plugins/SegmentEditor/javascripts/Segmentation.js#L682

`self.target.find('.segment-delete-confirm')` instead of eg `$('.segment-delete-confirm')`. We usually address them via an id I think like `$('#resetDashboardConfirm')`. Maybe we can simply replace `self.target.find` with `$`?

**Comment by sgiehl** [comment]
should work I guess. Maybe we should give the dialog an id, so it's consistent with other dialogs.
