### ISSUE TITLE
Transitions - numbers from Incoming Traffic don't match

### ISSUE THREAD

**Issue by tomasztomik** [piwik/piwik#10482]
Hello,

I recently discovered that numbers from Incoming traffic report (Transitions) often does not match.
Good example can be found at piwik.pro demo instance: https://demo.piwik.pro/index.php?module=CoreHome&action=index&idSite=1&period=day&date=2016-09-07#?module=Actions&action=menuGetPageUrls&idSite=1&period=day&date=2016-09-07&popover=RowAction$3ATransitions$3Aurl$3Ahttp$3A$2F$2Fexample$2Fanalyticsapp-available-again-in-microsoft-windows-web-app-gallery

![image](https://cloud.githubusercontent.com/assets/16131839/18352872/6c20b5b6-75e0-11e6-84c7-4c6eebfe1bfd.png)

Another example, from demo.piwik.org: http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-08-31#?module=Actions&action=menuGetPageUrls&idSite=7&period=day&date=2016-08-31&popover=RowAction$3ATransitions$3Aurl$3Ahttp$3A$2F$2Fforum.piwik.org$2Flatest

Shouldn't the number of pageviews be equal to the sum of all incoming traffic sources?
In this example, we have 123 pageviews and only 79 views explained in the "incoming traffic" report.

I observed the same issue many times on our customers instances, so it looks like a general bug with the module.

Regards,
Tomasz

**Comment by GatheredPain** [comment]
Hi,

i can confirm this Bug. In my opinion it's caused by the User-ID Feature. Since using this Feature, Campaing-Visits with UserID aren't counted/displayed in transitions view.

I have a Campaign for the page. When i use a Segment for this campaign, there are many impressions on the landing page but only a few (<1%) are considered as Entry page.

I think the UserID Feature causes Piwik to count all visits of this user as ONE visit instead of many visits of the same user an therefore doesn't track or calculate the Entry-Points correctly. ... This would be very bad and makes the UserID Feature nearly useless.

@tomasztomik can u check if the missing ~150 can be found via  Referrers > Campaigns

**Comment by tomasztomik** [comment]
@GatheredPain I don't think that it's connected with the campaigns nor UserID in my cases.

In the example from demo.piwik.org - no campaigns entries for the affected day, also no UserID.
Demo.piwik.pro example - UserID feature is not in use.

@mattab Do you maybe have any idea what can be the cause of described Transitions report behavior and if it's a bug?

**Comment by mattab** [comment]
Hi @tomasztomik 

> Shouldn't the number of pageviews be equal to the sum of all incoming traffic sources?

The number of pageviews should (ideally) be equal to the sum of incoming traffic sources + the number of page reloads (this metric displayed below the middle block).  In your screenshot example we have 24 (internal) + 55 (campaigns) + 25 (page reloads) = 104 pageviews which is not equal to 123 pageviews. So there is some discrepancy. I believe this discrepancy could be explained in more details and we could understand its cause but unfortunately right now I am missing some time to be able to investigate the code and reply more precisely. 

Definitely it's an issue that we should investigate/tackle in the future, thanks for the report!

**Comment by mattab** [comment]
I'm not 100% sure but this PR might help a bit the Transitions API data: https://github.com/piwik/piwik/pull/10510/files

**Comment by tsteur** [comment]
FYI: The example for Piwik seems to be correct

**Comment by mattab** [comment]
In Piwik 3 beta 3, Transitions report will sometimes show more "Loops" (number at the bottom of the central pane). Because we stop measuring outlinks and downloads as entry or exit action (in https://github.com/piwik/piwik/tree/9345 ), the number of "loops" increases. This may improve the accuracy of transitions report. Feel free to reopen or create new issue if you can still reproduce the issue on data collected with Piwik 3 beta 3 or newer :+1:
