### ISSUE TITLE
Button to add a segment is missing some text in French language

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10656]
Should read `Ajouter un segment`

the end of the button is not visible 

![ajouter un](https://cloud.githubusercontent.com/assets/466765/19052690/3e8ef764-8a14-11e6-812f-9021b7d7b620.png)

**Comment by tsteur** [comment]
The text says actually "Ajouter un nouveau segment". It's shown but not visible because the text is white below. Even when removing the padding it still does not fit in there.It would work when removing all the padding and removing the letter spacing and look like this:

![image](https://cloud.githubusercontent.com/assets/273120/20549807/829049de-b194-11e6-96da-0736597c58b2.png)

I noticed our buttons have a fixed height of 36px and I could remove the height for this one and reduce the line-height so it would look like this:

![image](https://cloud.githubusercontent.com/assets/273120/20549842/d94da172-b194-11e6-8b61-d836b92b5fa1.png)
