### ISSUE TITLE
Impossible de sortir d’un niveau de la carte

### ISSUE THREAD

**Issue by clasmusic** [piwik/piwik#10673]
In the IFRAME Piwik with the world map and all the countries there is no navigation widget what would allow us to step back in previous level. Is this something what is planned to fix/change/improve?

**Comment by clasmusic** [comment]
In the IFRAME Piwik with the world map and all the countries there is no navigation widget what would allow us to step back in previous level.

**Comment by mattab** [comment]
Thanks for the report @clasmusic - could you please post a screenshot showing the lack of controls in your iframe?

**Comment by clasmusic** [comment]
Here is the screenshot with last detailed level, correct me if i am wrong, but no navigation in order to go back one level can be found. Thank you!
![piwik_iframe_last_detailed_level](https://cloud.githubusercontent.com/assets/14886457/19105214/242da49c-8ae1-11e6-9b13-7880969b9b0a.png)

**Comment by mattab** [comment]
What iframe URL do you use to load this report? (without the token_auth) 
what do you expect to see?

**Comment by clasmusic** [comment]
We are using the right URL, our internal URL. The problem in my opinion is that when IFRAME is minimized, not a fullscreen, we have no close button on the last level, like here. So in minimized mode we do not responsive IFRAME content.
![piwik_iframe_fullscreen_navigation](https://cloud.githubusercontent.com/assets/14886457/19106106/df2c7ed6-8ae5-11e6-9f89-f22b29b50ceb.png)

**Comment by clasmusic** [comment]
Hello, any comments on this issue? Thanks.

**Comment by mattab** [comment]
Hi @clasmusic I think what you need is that Piwik content in the iframe will automatically resize to the iframe size you include, so that you see all the content even if the iframe had a smaller width. Many users have requested this feature as well, you're not alone. we'd like to implement but unfortunately not enough resource.  please comment in this other issue if you're interested: https://github.com/piwik/piwik/issues/10460 - cheers
