### ISSUE TITLE
New plugin about IP privacy

### ISSUE THREAD

**Issue by joubertredrat** [piwik/piwik#10758]
Hi @mattab @tsteur @sgiehl 

I think that is wrong to use Github issue for this, but I don't have other option to talk with you directly.

I want to write new plugin for anonymizing the visitor IP, but Piwik already have this option, but my case is different.

I use Piwik to measure visitor from all site hosted on my server and I use this data to compare with my [LibreNMS](http://www.librenms.org) monitorator to identify if I need to scale vertically my instances, DoS or other attacks. Then for me I need to see IP visitor for this.

On my Piwik, users that have site hosted on my server can view your respective site reports, but for this users I want to anonymize the visitor IP.

For this I want to write an plugin, but I want to understand if this plugin can be a problem for Piwik and your privacy policy.

Sorry for use this issues and thanks for Piwik.

**Comment by tsteur** [comment]
The ideal place to ask this is the forum and the plugin development category https://forum.piwik.org/c/plugins-platform . You can build pretty much anything you'd like in a plugin as Piwik is Free and there is no problem with our privacy policy because you host Piwik yourself. 

I don't 100% understand what you need because LibreNMS seems unrelated to Piwik but you could basically develop a plugin that anonymizes IP's in the UI and API for other users but not yourself.
