### ISSUE TITLE
Granting View access to anonymous users for All Websites fails

### ISSUE THREAD

**Issue by mehulkar** [piwik/piwik#10787]
Repro:
1. Go to Settings > Administration > Users
2. select "Website: Apply To All Websites" from dropdown
3. Click red dot under "View" to turn it green
4. Click "Yes" on confirmation modal
5. Watch page refresh (as if request it sent)
6. Notice that dot remains red

I'm using 2.16.5. not sure if this is supposed to work.

I can help debug further if needed!

**Comment by mattab** [comment]
Hello,

The UI is a bit confusing actually but it should work. it's confusing because it will never show a "Green tick" when "All websites" is selected. But when you click to give someone access to all websites, it should work as expected (you can verify by loading specific websites and you'll see the green tick)

**Comment by mattab** [comment]
We'll improve this UI in the future for example in https://github.com/piwik/piwik/issues/6187
