### ISSUE TITLE
new Plugin-Release doesn't show on marketplace

### ISSUE THREAD

**Issue by Thomas--F** [piwik/piwik#10804]
Hi Piwik-Team,

I released a new version of BotTracker (v0.58) some days ago, but it's not showing up on the Piwik marketplace.
Usually it updates minutes after the release, now nothing happens after a whole week.

**Comment by tsteur** [comment]
Hi Thomas,

I just had a look at it and indeed there is no such version in the database. I looked through the logs and found this:

```log
INFO - 2016-10-21T19:24:16+00:00 - Failed to get plugin.json from Thomas--F/BotTracker/refs/tags/0.58: [curl] 6: Couldn't resolve host 'api.github.com' [url] https://api.github.com/repos/Thomas--F/BotTracker/contents/plugin.json?ref=refs%2Ftags%2F0.58
```

It failed to get a `plugin.json` (maybe Github was down) and didn't import the plugin because of this. It should have sent an email but I can see it. It should fallback to the "committer email" we receive from GitHub because we cannot email the `authors` as defined in `plugin.json` because the file was missing. However, the email we received there was not valid for our system as it had brackets etc. I will update the Marketplace on Monday to also fallback to "Github's pusher email" in such a case and CC us (pusher email might be a noreply from GitHub) if no valid email address can be found so we will be aware of this next time. 

To solve this I would recommend to either delete the Tag on GitHub and to tag the same version again, or to simply tag it again as `v0.58_a`. Piwik Marketplace will read the version number from `plugin.json`.

Sorry for this. A plugin should be usually updated within approx. 2 min. If it's not visible on the Marketplace after 2 hours feel free to ping us :) Thx
