### ISSUE TITLE
System check: don't display warning when piwik.js is not writable as long as no plugin need it

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#10855]
Currently the system check issues a warning when the `piwik.js` file is not writable. 

The feature of editing piwik.js file to add custom JS code is very useful for providing advanced JavaScript integrations such as was done for [Media Analytics](http://www.media-analytics.net/) and [AB Testing](http://www.ab-tests.net/). 

On the other hand:
* for most users at the moment, the piwik.js does not need to be writable as all core features are included in the file already. 
* as a best practise for optimal security, or in some particular deploy scenario, one simply cannot make the file writable...

So because of these two points I propose that we could:

* Don't Warn in system check but instead display an info (as long as no plugin requires to hook into the piwik.js. if a plugin requires piwik.js then, display warn)
* Change the message eg. replace `In the future even some core features might not work as expected.` by `In the future, some of your plugins might not work as expected.` or so

Reported in #10706

**Comment by tsteur** [comment]
We should still warn because we eventually would like to refactor all plugins and make more use of it. Otherwise people will never make it writable. Also it is only a warning, not an error so people can ignore it if they choose so. It will save us a lot of pain over time when it is a warning and when people do make it writable.
