### ISSUE TITLE
Piwik reloads page when applying a segment

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#11012]
This should not reload the page as it is slow etc.

**Comment by mattab** [comment]
fyi This was regressed in: https://github.com/piwik/piwik/pull/10969/files
because with the patch: 

*  When editing a segment and clicking "save" then when re-editing again this segment, attributes such as "Available to all users" are not restored
*  Newly created Segments appear in the segment list with creator 'undefined' in the Tooltip text, instead of displaying the username
