### ISSUE TITLE
Potential 3.0.0 password API logme bug

### ISSUE THREAD

**Issue by c-prompt** [piwik/piwik#11094]
Testing out latest version and noticed automatic logins no longer work. When using [logme](https://piwik.org/faq/how-to/faq_30/) (i.e., https://stats.example.org/index.php?module=Login&action=logme&login=your_login&password=your_MD5_password), I'm seeing the following error:

> An error occurred The password parameter is expected to be a MD5 hash of the password.

The password being submitted was retrieved via the [UsersManager API](https://developer.piwik.org/api-reference/reporting-api#UsersManager) (i.e., http://demo.piwik.org/?module=API&method=UsersManager.getUsers&userLogins=&format=xml&token_auth=anonymous) and I verified the password retrieved matches what's in the password column of the piwik_user table. I noticed the old passwords from the previous version still login properly via logme so I'm guessing it has something to do with [#5278](https://github.com/piwik/piwik/issues/5728) (Passwords: use better algorithm than md5 hash, use salts and maintain BC ) and/or [#10740](https://github.com/piwik/piwik/pull/10740) (Updates password/token_auth hashing).

**Comment by mattab** [comment]
Thanks for the report @c-prompt 

Hi @mneudert  @sgiehl maybe you have an idea about this issue? This is for our `logme` feature documented in https://piwik.org/faq/how-to/faq_30/

**Comment by sgiehl** [comment]
UsersManager API won't return the md5 password any longer, but the password_hash'd one instead, so you can't directly use that for the logme method.

**Comment by mattab** [comment]
sounds like something can be improved / clarified in our documentation, let's do it

**Comment by mattab** [comment]
@c-prompt we updated the FAQ and added ` Since version 3.0 Piwik does not store the password as md5 any longer. As a result there is no way to access the md5 hashed password using the API. To generate the md5 password, you need the user's raw password and then call the md5() hash function on this raw password using your favorite programming language.` 

So hopefully this is clear and there is no more issue. if we missed something let us know
