### ISSUE TITLE
dashboard widget: entry pages: content width / height

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#11104]
There seem to be some modification on dashboard widget: entry page (seen in P3.0.1b1, haven't seen this before..)
which leads to
a) horizontal scrollbar
b) vertical scrollbar (not needed/no function)
or
c) too wide content

depending on browser...

please see attachments

![2016-12-27_15h46_15](https://cloud.githubusercontent.com/assets/5681880/21501969/b8c6c0a0-cc4c-11e6-9469-14600401e77d.png)

![2016-12-27_15h48_10](https://cloud.githubusercontent.com/assets/5681880/21502006/fbb46eda-cc4c-11e6-905f-e4ac3f510f39.png)

**Comment by mattab** [comment]
Hi @hpvd 

thanks for the report!

a) is expected when the widget content is too wide

b) I have not seen this yet, but I guess it's not too bad unless it happens often (maybe create separate issue if you can find steps to reproduce)

c) is covered in #11076

**Comment by tsteur** [comment]
It is certainly there, there is a little threshold where a widget is allowed to go like max 10 or 20px or so out of the widget as it is otherwise almost impossible to detect whether we need to show scroll bars or not. Especially with our dataTables etc that do random stuff at various points etc. Without this threshold it would very often in widgets etc show scrollbars where they are not needed (like most of the time )
