### ISSUE TITLE
Update notification dropdown not usable

### ISSUE THREAD

**Issue by srsbiz** [piwik/piwik#11111]
Hovering over button displays more info with link to update, but this box disappears immediately after moving mouse out of the button. Clicking it also takes us nowhere.

![update](https://cloud.githubusercontent.com/assets/1525842/21540360/12df4040-cdaf-11e6-853a-6f21154c62c9.gif)

**Comment by RMastop** [comment]
What browser and version were you using when this behaviour showed up?

**Comment by RMastop** [comment]
Yes, I confirm this is not working as expected. However, if I quickly hover over and move down, it works for me.

**Comment by LarsBauer** [comment]
Workaround for users struggling to update:
Edit the HTML and add the class `expanded` to the <div>. Box expands and stays open. Now you can click the link.

Should be easy to fix I suppose.

**Comment by Findus23** [comment]
The problem seems to be that there is 2px margin between the button div 
and the .dropdown div.
Possible solutions:
 - remove the margin (ssimple, works, but looking a bit odd)
![bildschirmfoto vom 2017-01-14 20-39-32](https://cloud.githubusercontent.com/assets/6266037/21957592/bc687252-da99-11e6-9b01-d0752bd04f5e.png)
 - open dropdown with click
- add a small dalay after mouseleave. Then check if mouse is again in div and if so don't remove *expanded* class
