### ISSUE TITLE
Tibet should be part of China

### ISSUE THREAD

**Issue by hoyang** [piwik/piwik#11152]
Tibet is not an independent country, is a province of China.

**Comment by Glisse1** [comment]
No, is an independent country. Like Taiwan. Like Kosovo is not part of Serbia anymore, and just like Macedonia is a country of its own today, not the northern province of Greece as it used to be 2400 years ago. So on and so forth.

This ticket is completely invalid and should be closed.

**Comment by s1awa** [comment]
duplicate https://github.com/piwik/piwik/issues/10343

**Comment by ppwwyyxx** [comment]
@Glisse1 
I would say you're the one who lives in a distant past. As someone in 2017 you'd at least know to use wikipedia as a source of trustworthy knowledge, rather than some random news report or your personal speculation.

Since you probably don't know, I'd be happy to help you with some links to the relevant pages, and the definition of the following names:
[Tibet](https://en.wikipedia.org/wiki/Tibet): is **an autonomous region of the People's Republic of China** in the Tibetan Plateau in Asia, spanning about 2.4 million km2 and nearly a quarter of China's territory.
[Kosovo](https://en.wikipedia.org/wiki/Kosovo):  is a disputed territory and partially recognised **state** in Southeastern Europe.
[Macedonia](https://en.wikipedia.org/wiki/Republic_of_Macedonia):  officially the Republic of Macedonia is a **country** in the Balkan peninsula in Southeast Europe. 
[India](https://en.wikipedia.org/wiki/India):  is a **country** in South Asia.

By definition given by wikipedia, it already clearly shows the difference between Tibet and Kosovo, Macedonia, India. Your comments demonstrated a classical false analogy.
