### ISSUE TITLE
Ignore piwk-archive.log in integrity check

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#11244]
The file should not be deleted as we recommend users eg to use "piwik-archive.log" in cronjob see https://piwik.org/docs/setup-auto-archiving/ and https://twitter.com/JourneyGreatest/status/822417671476101121

**Comment by mattab** [comment]
It's actually on purpose that *.log files will appear in the File integrity diagnostic as warning, because log files contain sensitive information (segment definitions, number of sites, etc.). I've updated the user guide to clarify this `This log file should be written in a location outside of your web-server so that people cannot view it via their browser (because this log file will contain some sensitive information about your Piwik installation).`.
