### ISSUE TITLE
pclzip.lib.php warning on 3.0.1

### ISSUE THREAD

**Issue by tuxmaster** [piwik/piwik#11335]
PHP 7.1 using FPM.
OS CentOS 7.3
After update the ReferrersManager plugin to 3.0.2 open the plugin page the follow warning was shown:

>  WARNING: /var/www/piwik/html/vendor/piwik/decompress/libs/PclZip/pclzip.lib.php(1797): Notice - A non well formed numeric value encountered - Piwik 3.0.1 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

**Comment by Findus23** [comment]
As the error seems to occur in this line: https://github.com/piwik/component-decompress/blob/master/libs/PclZip/pclzip.lib.php#L1797 :
What does PHP return for `ini_get('memory_limit')` on your server?

**Comment by tuxmaster** [comment]
128M

**Comment by Findus23** [comment]
I think I found the problem: 
`$v_memory_limit` is a string similar to "128M". `$last` is then the last character in lowercase (so in this case `m`).
But in line 1797 the string `"128M"` (instead of the integer `128`) is multiplied with 1048576 to convert it to bytes.
This works, but since PHP 7.1 results in the notice `A non well formed numeric value encountered`.

See https://3v4l.org/bQpGA

**Comment by Findus23** [comment]
And it seems like I am not the fist to notice :https://github.com/piwik/component-decompress/pull/9

**Comment by mattab** [comment]
fixed in  piwik/component-decompress#9
