### ISSUE TITLE
Clicking on the "Dashboard" top link hides all dashboard content 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#11386]
Reproduce:
* Open http://demo.piwik.org/
* The dashboard has loaded
* In the top bar click the "Dashboard" link
* Expected: the Dashboard reloads
* Got: dashboard disappears

![empty](https://cloud.githubusercontent.com/assets/466765/23166773/308e8fa2-f842-11e6-9fad-81b3aa3ba554.png)

**Comment by sgiehl** [comment]
The link currently points to `index.php?module=CoreHome&action=index&...`.
This currently destroys the report area, as the url is the same base url as on every report page, but doesn't provide a hash part in the url. The change of the hash part (to nothing) triggers the history service. 

What exactly would be the expected behaviour here? A hard link to the default dashboard of the current user? Or a link to the default page (which could also be the multisites dashboard,)

**Comment by mattab** [comment]
> Or a link to the default page (which could also be the multisites dashboard,)

It would be I think confusing if it linked to Multisites. The "default page" can be reached by clicking on logo. 

> A hard link to the default dashboard of the current user? 

Yes
