### ISSUE TITLE
Upgrader does not delete files that were removed in a newer Piwik version

### ISSUE THREAD

**Issue by daniel-barrows** [piwik/piwik#11446]
Today, I updated Piwik, as installed via Softaculous.
I had Piwik version 3.0.1, and upgraded to version 3.0.2

I went from this page: https://example.com/piwik/index.php?module=CoreUpdater&action=newVersionAvailable, and chose an automated update, which took me to this page: https://example.com/piwik/index.php?module=CoreUpdater&action=oneClickUpdate,
which reported:
> An error occurred
> Your Piwik version 3.0.2 is up to date.

However, I appear to now be running 3.0.2 just fine. I ran the System Check and the only thing I see is another file integrity check issue which may have been pre-existing:
> Files were found in your Piwik but we didn't expect them.
> --> Please delete these files to prevent errors. <--
> 
> File to delete: error_log
> File to delete: libs/jquery/jquery.smartbanner.js
> File to delete: libs/jquery/MIT-LICENSE-smartbanner.txt
> File to delete: libs/jquery/stylesheets/jquery.smartbanner.css

I'm not sure what the error message was about, but at the very least, this is a usability problem.

**Comment by chillivilli** [comment]
File to delete: libs/jquery/jquery.smartbanner.js
File to delete: libs/jquery/MIT-LICENSE-smartbanner.txt
File to delete: libs/jquery/stylesheets/jquery.smartbanner.cs

i have this too after update.

**Comment by lourdas** [comment]
Same here. Before upgrading to 3.0.2 I had this kind of report and I manually deleted these extra files. After copying the files from 3.0.2, several tens of extra files reappeared. I manually deleted them again. Other than that, the application seems to work fine.

**Comment by daniel-barrows** [comment]
I'm going to take a wild guess that this is a variation on https://github.com/piwik/piwik/issues/11107, but there is no message to the user indicating what the error was. I was only able to discover the file integrity issue by running a System Check. With no error report, the user is left to wonder if something is wrong with their installation even though everything seems fine.

**Comment by mattab** [comment]
+1, we also experienced this. So there must be a bug in our updater where it should have deleted those files automatically yet it didn't.

**Comment by gamanet** [comment]
I´m running a Debian GNU/Linux 8-Server with Piwik 3.0.2.

I´m using following repos:

deb https://debian.piwik.org/ piwik main
deb-src https://debian.piwik.org/ piwik main

After the upgrade to 3.0.2 (from 3.0.1) the systemcheck shows me following message:

_Die nachfolgenden Fehler könnten durch einen teilweise oder gänzlich fehlgeschlagenen Upload der Piwik-Dateien entstanden sein.
--> Versuche die Piwik-Dateien im BINARY-Modus neu hochzuladen. <--

Fehlende Datei: /usr/share/piwik//etc/apt/trusted.gpg.d/piwik-keyring-automatic.gpg_

In english it should read like:

_The following errors could have been caused by a partial or completely unsuccessful upload of the Piwik files.
-> Try to re-upload the Piwik files in BINARY mode. <-

Missing file: /usr/share/piwik//etc/apt/trusted.gpg.d/piwik-keyring-automatic.gpg_

The file "/etc/apt/trusted.gpg.d/piwik-keyring-automatic.gpg" exists on my server...
The file "/usr/share/piwik//etc/apt/trusted.gpg.d/piwik-keyring-automatic.gpg" doesn´t exists.
Not sure if it´s possible at all to have a file-/directory with "//" within name...

When running

_php /usr/share/piwik/console diagnostics:run_

i get that output:

_INFO [2017-03-15 09:16:58] Unable to test if mod_pagespeed is enabled: the request to http://unknown/usr/share/piwik/console?module=Installation&action=getEmptyPageForSystemCheck failed
File integrity: WARNING File integrity check failed and reported some errors. You should fix this issue and then refresh this page until it shows no error.

Directories were found in your Piwik but we didn't expect them.
--> Please delete these directories to prevent errors.
Memory limit: WARNING M
On a high traffic website, the archiving process may require more memory than currently allowed. If necessary, change the memory_limit directive in your php.ini file.
After making this change, restart your web server.
2 warnings detected_

But again no information which files were found...

**Comment by mattab** [comment]
Moving out of 3.0.3 for now as we likely don't have time for 3.0.3  cc @sgiehl
