### ISSUE TITLE
Piwik v2.17.1 unable to install plugin that have version for v2 and v3 via the Marketplace interface

### ISSUE THREAD

**Issue by Mayeu** [piwik/piwik#11480]
Hello,

We have a Piwik v2.17.1 running, in which we wanted to install the MediaAnalytics plugin.

When we go on the web marketplace, we can see that there is a version for [Piwik v2](https://plugins.piwik.org/MediaAnalytics?piwikversion=2) (the v2.0.5), and one for [Piwik v3](https://plugins.piwik.org/MediaAnalytics?piwikversion=3) (the v3.0.4).

But when I go to the Marketplace interface in Piwik, I am unable to install the plugin as it only shows the v3.0.4.

My expectation would be that Piwik v2 will allow downloading the version working with it, and not only the very last version of the plugin.

I stay available for any information you would like to have, or missing from the previous description.

**Comment by sgiehl** [comment]
That should work indeed. Maybe @tsteur is able to have a look at this.
In the meantime maybe get in touch with contact@innocraft.com they should be able to send you zip of the plugin in the correct version so you can install it manually if you already bought a license.

**Comment by Mayeu** [comment]
Thank you for the quick feedback, we downloaded the archive via our account page on the web Shop, and uploaded the zip to be able to install it :)

**Comment by tsteur** [comment]
Thank you for the feedback @Mayeu  👍   I was able to reproduce. Then debugged Piwik and Marketplace to notice there was an edge case in the communication with the Piwik Release API which returned a Piwik 3 version instead of a Piwik 2 version. I have fixed this now and it should work in the future (might take a while until the cache is cleared on your Piwik)
