### ISSUE TITLE
Wrong device resolution (almost always 360x640)

### ISSUE THREAD

**Issue by jsmad** [piwik/piwik#11569]
I've noticed that there are an excessive number of devices with resolution 360x640, which is obviously wrong. This resolution made me even more suspicious that something is wrong, because it appears with devices that run some high-end devices with relatively recent Android versions, which seems impossible that they actually use such low resolution screens.

Upon further investigation, I found that indeed the 360x640 is completely wrong.

For example, an HTC One M8 device running Android 6 Marshmallow with a resolution of 1080x1920 is reported as 360x640. Same problem with the Samsung Galaxy S7 running Android 6.0.1 with a resolution of 1440x2560, again reported as 360x640.

**Comment by mattab** [comment]
Thanks for the report. Would you maybe be able to troubleshoot further this issue i case you are familiar with JavaScript and could debug what is wrong with the tracker?

**Comment by jsmad** [comment]
I am unable to run piwik at the moment, because it does not run on CentOS 7.3 (which is the latest version), hopefully I'll have that sorted out soon.

**Comment by mattab** [comment]
Have you made some progress @jsmad 
what is not working with Centos 7.3 exactly?

**Comment by jsmad** [comment]
piwik 3.0.4 will not run under CentOS 7.3 because the default PHP version of CentOS is too old (5.4.16).

unfortunately, due to various reasons, I am not in liberty to install a newer PHP because my servers are certified to run official packages only, thus 5.4.16 will probably be the only version I'll be able to run under CentOS 7.3. I am not sure what 7.4 will use, probably another 5.4.x release.

what is sad, is the fact that I couldn't find anything specific in the piwik code that requires a newer version, so maybe I'll make a patch for myself to force piwik 3.0.4 to run under php 5.4.

**Comment by mattab** [comment]
> what is sad, is the fact that I couldn't find anything specific in the piwik code that requires a newer version, so maybe I'll make a patch for myself to force piwik 3.0.4 to run under php 5.4.

It would be more sad to patch Piwik to run on an old insecure PHP version and waste time on this... We very much recommend using a better host / server setup and use modern software :+1:

**Comment by mneudert** [comment]
Regarding the screen sizes shown I don't think the values you are seeing are wrong. At least when tracking a website.

I had the opportunity to look at a physical `Galaxy S7 Edge` and the numbers are correct regarding the pixels used for website styling.

If you take a look at https://mydevice.io/devices/ you can see there is not only "CSS height" but also "physical height". The difference made up due to the "pixel ratio". And the S7 actually displays a website with the styles defined for a 360 pixel width while using all it's physical pixels do make everything look crips and.

#11405 is probably the issue you want to track for getting the tracking information extended to include the relevant information.

**Comment by sgiehl** [comment]
Thanks for the explanation @mneudert. Closing in favor of #11405
