### ISSUE TITLE
Visits over Time - Annotations when we create, it does not display Automatically

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#11573]
Feature: Visits over Time 
Issue:  Annotations when we create, it does not display Automatically

Attached the GIF file, to reproduce the steps.

![apr-1-2017-11-24-am](https://cloud.githubusercontent.com/assets/4346684/24575838/4b12550c-16ce-11e7-9308-6ebf794f9fac.gif)

**Comment by RMastop** [comment]
Hi @srinivasskc,

The created annotation is for April first. The date that is selected is March 31st, if you make sure  April first is in the date range, this annotation will be shown.

Cheers,
Richard

**Comment by srinivasskc** [comment]
Thanks @RMastop,
I created for Apr 1st. Still it does not show when saved. 
![apr 1 2017 3-35 pm](https://cloud.githubusercontent.com/assets/4346684/24577769/b15ba002-16f1-11e7-8100-a1ecdc51f1b7.gif)

Question: If my to-date is 1st April, why does it default to 31st March?
Question: If i create an annotation today(April 1st), will it display after April 1st?

**Comment by RMastop** [comment]
The selected date for the overview is set to March 31st, Piwik defaults to the current selected date. Since one is checking reports based on that date, a new annotation is added to that date.

Change the date in the top to April 1st and it wil show up. Annotations will be shown if they are within the range of the viewed report. In this case no data for april 1st is shown, so is the annotation for April 1st is not shown.

The line just above the annotations tells you what items will be shown.

**Comment by mattab** [comment]
Thanks @RMastop for your explanation :+1: 

Probably we could improve the usability of annotations in general but this should be another issue
