### ISSUE TITLE
slow query when get Live.getLastVisitsDetails API for month data

### ISSUE THREAD

**Issue by xiaotaozi1127** [piwik/piwik#11592]
Hello piwik team,

I need call **Live.getLastVisitsDetails** API for a month data. But i found it is very slow to load all the data, eventually, it will say '**Gateway_Timeout**' error.

I tried to filter only 'actionDetails' column and get 100 items one time. So, it will call around twenty times to get a month data. Just like below code.
```
$data = \Piwik\API\Request::processRequest('Live.getLastVisitsDetails', array(
            'idSite' => $idSite,
            'period' => $period,
            'date' => $date,
            'segment' => $segment,
            'filter_offset' => $filter_offset,
            'filter_limit' => 100,
            'filter_column' => 'actionDetails'
        ));
```

But it didn't make much improvement.  How can i improve the performance?

Thanks in advance,

**Comment by tsteur** [comment]
There is not really any way to improve this performance. If you are happy with some raw data you may want to add `disable_queued_filters=1` which will remove a lot of formatting and I think it will also remove the action details. The only way around this is otherwise to work with filter offset and filter limit and fetch them over many requests. Or you could develop your own plugin that gives you the data in the way you want which could be optimized for better performance. More info on developing plugins see  https://developer.piwik.org/ or https://piwik.org/development/

**Comment by tsteur** [comment]
BTW: The actionDetails filter will only remove data afterwards AFAIK but still fetch it initially so it only speeds up transferring less data
