### ISSUE TITLE
[FR] Translation issue leads to wrong sentence construct (visitor profile)

### ISSUE THREAD

**Issue by justinmassiot** [piwik/piwik#11667]
Piwik 3.0.3 stable
PHP 5.6.30
French locale

When viewing a visitor profile with Piwik configured to be in French, the first sentence of the section "Sommaire" is misconstructed. The number of pages viewed is swapped with the word "affiché" which gives a non-valid sentence. See the screenshot:
![screenshot visitor profile French](https://tof.cx/images/2017/05/06/ddf2efa28ecd7b62a784223d5fa1065a.jpg)

Also it's weird because I'm unable to locate in the "lang" directory the translation file in which this sentence appear. I would have proposed a fix but I couldn't, sorry.

**Comment by sgiehl** [comment]
Thanks for your report. Our translations are managed using transifex. Please get an account there in order to help us improving the translations. 

https://www.transifex.com/piwik/piwik/

Once you have an account you can update the according translation key here: https://www.transifex.com/piwik/piwik/translate/#fr/$/44516766?key=Live.VisitSummary
