### ISSUE TITLE
Failed to load resource: net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by agokulravikumar** [piwik/piwik#11809]
I get the error and the Piwik 3.0.4 integration is not getting hits. Both the request and host server are https and still the error throws up in the console.

Kindly check the error on console of the site https://blog.furnituremagik.com and the piwik.js file when accessed in an another tab opens perfectly.

It is working fine when integrated with a http domain.

Tried all possibilities but nothing worked. Need help in resolving.

**Comment by Findus23** [comment]
Hi,

The problem is exactly what chrome tells you: an insecure response.

The piwik url in your tracking URL is `https://www.fmgk.in/analytics/piwik.js`, but if one tries to request this url, the server responds with a file that is encrypted with a certificate that is only valid for `fmgk.in`. (without `www`)
You can test this with curl:
`curl -v https://www.fmgk.in`

```curl
[...]
* Server certificate:
*  subject: CN=fmgk.in
*  start date: Jun 19 16:23:00 2017 GMT
*  expire date: Sep 17 16:23:00 2017 GMT
*  subjectAltName does not match www.fmgk.in
* SSL: no alternative certificate subject name matches target host name 'www.fmgk.in'
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'www.fmgk.in'
```

The solution is to also request a let's encrypt certificate for the www. domain (`-"d www.example.com -d example.com"`

**Comment by agokulravikumar** [comment]
Thanks and after installing certificates to both www and non www it is finally working.
