### ISSUE TITLE
is it possible to return all the results from api call ? 

### ISSUE THREAD

**Issue by idhard** [piwik/piwik#11846]
according this ticket  #8458 now all api call results apply a limit of 100 records , but in the documentation https://piwik.org/faq/how-to/faq_24536/ it shown that you could specify the format_limit=-1  to get all the results , which is not longer possible .

Is the documentation outdated  ? is not possible to get all the results anymore ?

thanks

**Comment by RMastop** [comment]
Hi @idhard,

It's a typo, use filter_limit in those cases.

Important note about high traffic Piwik servers

If you export a lot of data, for example more than 10,000 visits and their associated actions and clickstream, then the HTTP request above may take a long time or even time out (depending on your server and PHP settings). Therefore when you export a lot of data, we recommend that you only export 10,000 at a time and use our paging &filter_offset= feature. Here is how this works: to export the first 10,000 records, instead of filter_limit=-1 you would write filter_limit=10000&filter_offset=0. Then, to export the next dataset, you would write filter_limit=10000&filter_offset=10000. Then to export the next dataset, you will write filter_limit=10000&filter_offset=20000. You repeat this until there is no more result in the dataset.

**Comment by sgiehl** [comment]
thx @RMastop  for answering this.

**Comment by RMastop** [comment]
@sgiehl do we need a separate ticket to edit this faq: https://piwik.org/faq/how-to/faq_24536/ 
Or is it already edited?

**Comment by sgiehl** [comment]
Sorry, guess the cache wasn't purged. The FAQ should be fixed now.

**Comment by RMastop** [comment]
fixed it is 👍
