### ISSUE TITLE
AND AGAIN: TIBET AND TAIWAN , PART OF CHINA

### ISSUE THREAD

**Issue by Vsevorod** [piwik/piwik#11913]

**Comment by ILOFI** [comment]
Yes

**Comment by Vsevorod** [comment]
Please issue a new one if you agree.
Thanks in advance

**Comment by ILOFI** [comment]
I issued but is marked duplicate by a fucking member

**Comment by brockholzer** [comment]
The People's Republic of China claims that Tibet is an integral part of China. The Tibetan government-in-exile maintains that Tibet is an independent state under unlawful occupation. This is an issue tracker for an open source web analytics platform... which I now have to stop following because it is now being spammed with political rants that do not belong here. There isn't a political statement being made here with Taiwan, either - there is simply a distinction being made between Taiwan, the contemporary geographical territory, and Mainland China, the contemporary geographical territory. For now, you can just add the figures together if you're concerned about a total.

If you're losing sleep over this, fork the project and create a version that fits your political position and share it with the world. Or, you could create a proper pull request that would allow toggling the classification of Tibet/Taiwan and I'll bet it would get accepted. There are over 1300 open issues and there are hundreds that will take priority over addressing this. Duplicating the same issue over and over will only make you less of a priority.
