### ISSUE TITLE
Same website user with multiple IP getting tracked with only 1 IP not both

### ISSUE THREAD

**Issue by Bits101** [piwik/piwik#11952]
Hi,

I have added a user id using setUserId parameter for tracker website's logged in user. The issue is that if I am logged into two different devices or through two different IP's. I cannot see these multiple IP or devices in the USER visitor's log data. It still shows me the same previous data of that USER.

If its a bug how soon can it be fixed? If not a bug then why its behaving like this?

Thanks

**Comment by Bits101** [comment]
It only shows the First User IP, Browser & Device information in the visitor logs.

**Comment by DrCard** [comment]
i also have the same problem my Magento users are login in from 2 different devices and 2 different IPs but i can only see the first user information in piwik

**Comment by mealiusman** [comment]
I am also facing the same issue. I have a piwik setup and my ip is dynamic and gets updated everyday. Whenever my ip gets updated, piwik still shows the old ip and never updates it. We really need this fixed as this is a real concern for me.

**Comment by mattab** [comment]
Yes, it is by design that when the same person views the website using 2 devices, only one of the IP addresses get stored in the visit. This only occurs when the person visits the website at the same time in both devices, because we only create one visit and therefore can only store one IP and device information.

>  Whenever my ip gets updated, piwik still shows the old ip and never updates it. 

this should only occur as long as the visit is not finished. But if your IP changes and you visit the website 30min after the last pageview, then a new visit will be created and the IP address will be set to your current one.
