### ISSUE TITLE
Piwik not count social media referrers

### ISSUE THREAD

**Issue by waleednagaty** [piwik/piwik#12116]
Hello,

My Post in Piwik forum https://forum.piwik.org/t/urgent-i-am-not-going-to-use-piwik-anymore/25725

I am not writing this topic to say something bad for Piwik team but I write it because I hope this issue can solve by them.

Before 3 month I re-open my blog and as usual I used Piwik and visits everyday like 76 or 34 after one month I added Google Analytics to my blog to see visits report, the reports same as piwik so I believe everything is ok, Before one month I start using Google Shortner but I found many many clicks everyday on links and Piwik and Google analytics still 34, 45 visit WTF for example in one day I got 700+ clicks in one link and Piwik and Google analytics give me 54 visits only.

For one week I search and search and search for solution but no hope one day I remember hosting provider given me AwStats in my cpanel so I open it and I found answer it is provide me the real number of visits huge number.

The Summary you have to know Piwik and Google analytics not count the referrers from Social media like Facebook, Twitter, etc. so now I am using AwStats and I am happy good bye Piwik.

Thanks

**Comment by sgiehl** [comment]
Well there is a very big difference between AWStats and Piwik Analytics (or Google). If you use JavaScript tracking, visits from Bots and Crawlers aren't counted as most of them don't load any JavaScript. This is on puporse as Bots and Crawlers would make any statistic useless. 
Your AWStats and the stats from your URL shortener report statistics based on the page call, which include all Bots and Crawlers. If you populate a shortened Link on Twitter, Facebook or in any forum dozens of Crawler and Bots will follow those links.
I would guess your links a crawled a lot, but not that many "real" people click on them.
If you wish to have such high numbers in Piwik as well you can use Log Analytics feature instead of JS tracking.  When importing your webserver logs there is an option to include bot traffic.

**Comment by waleednagaty** [comment]
Hi Sgiehl,

I would like to explain something I am make sure there not Bots or Crawlers because I have 2 post views stats in my blog and same Google Shortner and Awstats and WP-Statistics plug-in.

I did a test I went to my social media page and click on the link then went to Piwik & Google Analytics to see real time visit I find 0 also went to Piwik find 0 so I open browser and go to my website the real time visit find 1. 

Please try to do this and see the result.

**Comment by sgiehl** [comment]
There are different reasons why your visits might not be counted. Are you using an ad blocker or do you have the Do-Not-Track feature enabled in your browser? Did you activate the Opt-Out for Piwik (or Google) or have you configured Piwik to exclude visits from your IP? All that might be possible reasons that you aren't tracked, while scripts like AWStats, the URL Shortener or the Wordpress plugin would still count.
