### ISSUE TITLE
Customizable LESS var for header/menu links color

### ISSUE THREAD

**Issue by chrisschauer** [piwik/piwik#12201]
Hi all,

I already dicussed on forum.piwik.org about that: https://forum.piwik.org/t/customize-header-menu-links-color-within-a-theme/23418

I wish to have the oportunately to define the 
 * header-background color
 * header-menu color 
within a theme.

But there is only the following:
`@theme-color-header-background: #ffffff;`

It would be nice to have also e.g. a
`@theme-color-menu-text: #ffffff;`

Current-version: 3.2.0

Thx

**Comment by tsteur** [comment]
Hi there,

to understand this correctly, you want to change the text color in the header menu? Eg do a dark color because the background is eg white? Only got a little confused because both examples contain `background`. With `menu` we reference to the left reporting/admin menu which can be changed with these colors:

```less
@theme-color-menu-contrast-text: @theme-color-text;
@theme-color-menu-contrast-textSelected: @theme-color-menu-contrast-text;
@theme-color-menu-contrast-textActive: @theme-color-brand;
@theme-color-menu-contrast-background: @theme-color-background-contrast;
```

**Comment by tsteur** [comment]
FYI: I issued a PR to add `@theme-color-header-text`

**Comment by chrisschauer** [comment]
Hi @tsteur,

sorry for confusing you. You are right - it was a typo on my side. I edited the issue text.
Thanks for the quick response and the PR. It might be useful to add also documentation on: https://developer.piwik.org/guides/theming

Thanks a lot
Chris
