### ISSUE TITLE
responce code is 405 will send twice request

### ISSUE THREAD

**Issue by quanjunjie531** [piwik/piwik#12260]
![image](https://user-images.githubusercontent.com/15264394/32529207-2a87c8f6-c472-11e7-86a2-4b7a62fb436c.png)

if request length more than 2000 will be errors,and this request type is POST(responce code is 405,my server disabled POST request), after the error wille request again by GET and success,

how to solve this.

**Comment by sgiehl** [comment]
why are you disallowing POST requests?
Requests with a length over 2000 chars might fail due to it's length in IE and maybe other browsers. So Piwik sends those request using POST and there is no possibility to change that.
I would highly recommend to enable POST requests, otherwise you will have an inaccurate tracking.
