### ISSUE TITLE
Custom report not working

### ISSUE THREAD

**Issue by ArchiReport** [piwik/piwik#12296]
Hi,
I just bought Custom Report plugin and it seems not to work for previous data.
In order to test, i generated the unique visitors evolution and compared it with the existing graph.
I only have a value for the 23rd november and none before.
Here are snapshots to understand.
![capture d ecran 2017-11-24 a 14 13 10](https://user-images.githubusercontent.com/23122751/33212150-0fa2eb4e-d122-11e7-8b70-d03e4aaf65c9.png)
![capture d ecran 2017-11-24 a 14 13 16](https://user-images.githubusercontent.com/23122751/33212151-0fbeedd0-d122-11e7-9731-265ff0421778.png)

Could you please help me with that ?
Regards,
Morgan

**Comment by sgiehl** [comment]
That is currently per design. Old reports need to be reprocessed in order to get data for it.
You can trigger that on the command line (see https://piwik.org/faq/custom-reports/faq_25265/) or use the [invalidate reports plugin](https://plugins.piwik.org/InvalidateReports) to invalidate reports, reprocessing should then happen automatically in the browser or when the cron job runs.

We need to change some stuff in Piwik itself in order to be able to add new reports for already archived periods. We hope to make that possible in the near future, so plugins like custom reports can add their reports automatically without reprocessing all reports.
