### ISSUE TITLE
Matomo 4.0.2 warns about "ExampleLogTables requires Piwik <4.0.0-b1"

### ISSUE THREAD

**Issue by slawa-dev** [piwik/piwik#16857]
Matomo version: 4.0.2

![system_check](https://user-images.githubusercontent.com/20663500/100815614-4fd85280-347f-11eb-91ef-4c1d86cfc9ad.jpg)

Related to https://github.com/matomo-org/matomo/issues/16804

**Comment by tsteur** [comment]
Thanks @slawa-dev for reporting this. I'll push a fix for this.

**Comment by Starker3** [comment]
Looks like this issue is still occuring:
_I've upgraded to Matomo 4.0.3 and now I see this message "The plugin ExampleLogTables could not be loaded as it has missing dependencies: ExampleLogTables requires Piwik <4.0.0-b1. Please contact your Matomo administrator."._
and: 
_I've updated to the latest version which is 4.0.4 and still the message appear._

**Comment by tsteur** [comment]
Maybe the update script was not executed. The user can still remove the plugins manually from the filesystem. They are in the `plugins` directory.

**Comment by slawa-dev** [comment]
> Maybe the update script was not executed.

After the update you get the warning once. When I checked on the plugins, they were removed properly.
