### ISSUE TITLE
AbstractDeviceParser::getShortCode() must be of the type string, int returned

### ISSUE THREAD

**Issue by gusevmaksim** [piwik/piwik#16889]
Matomo 4.0.4
./console queuedtracking:process
vendor/matomo/device-detector/Parser/Device/AbstractDeviceParser.php line 924:
Return value of DeviceDetector\Parser\Device\AbstractDeviceParser::getShortCode() must be of the type string, int returned

version to
return (string) \array_search($brand, self::$deviceBrands) ?: '';

**Comment by tsteur** [comment]
@sgiehl any idea how this might happen? Looking at the code it should always return a string.

I see it might return `false` though if the brand is not found. It seems technically that method is not even in use anymore. @gusevmaksim how did you upgrade to Matomo 4? Using the one click UI upgrade or by any chance did you upgrade manually?

**Comment by sgiehl** [comment]
@tsteur That should be already [fixed in device detector](https://github.com/matomo-org/device-detector/commit/a5f8efa6d0e8bad81832072a1b3ab9edb0b87e71). Seems it wasn't included in the last release. It happens when a device is detected that has a brand with a short code that only contains numbers like the brand `8848`. Will release a new version of Device Detector tomorrow and update it in Matomo afterwards

**Comment by gusevmaksim** [comment]
I updated in one click from version 3
