### ISSUE TITLE
Unable to login to Matomo since the last update and unable to update to Matomo version 4.0.5

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#16944]
Hi there, 

since the last Matomo update 4.0.4. I am not able to login into my account because of this warning: 
<img width="1436" alt="Bildschirmfoto 2020-12-13 um 18 20 39" src="https://user-images.githubusercontent.com/75946336/102018861-3cc35d80-3d70-11eb-9d4c-fc99f3a61b07.png"> 

I am not able to reject the warning by clicking on the link as suggested in the warning message. I am administrator but cannot access at all to make any changes in the settings section to get it fixed.
Because of this I also cannot update to Matomo 4.0.5.

I saw some users having a similar problem since the last update but I could not find a proper solution for my issue yet.
I would very much appreciate support to get this fixed.
Thank you!

**Comment by tsteur** [comment]
@alew3d as a workaround you could as suggested in the screen disable the trusted host config temporarily until you upgraded to 4.0.5. Can you not access the file system to make this change? It may be required in order to make it work again.

Alternatively, the 3 step manual update might work but I suppose if you can't change a config, then you also can't update the files itself: https://matomo.org/docs/update/#the-manual-three-step-update

Do you know what webserver you are using?

**Comment by ghost** [comment]
@tsteur Thank you for your support.
I am unfortunately not able (yet) to make any changes in the system and do not know where to access the file system. Do you have a hint?
We are running our website on IONOS. Is this the place where I can access the file system?

**Comment by tsteur** [comment]
@alew3d yes, that's the place where you can access the file system very likely. Hope this helps. If you still have problems with that it might be good asking your hoster IONOS for information on how to edit the file.
