### ISSUE TITLE
File Integrity: Core Plugin: Provider

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#16962]
I have installed a fresh copy downloaded and unzipped directly from your server to the server using ssh.
The Core plugin Provider was installed direct from marketplace.
System check now shows the following error:

`File size mismatch: /home/eajglobal-net/matomo/plugins/Provider/Provider.php (expected length: 3479, found: 4328)
Missing file: /home/eajglobal-net/matomo/plugins/Provider/screenshots/Report.png`

**Comment by tsteur** [comment]
@EntrepreneurAJ1 this is indeed an error. Sorry about that. Currently, it's not needed to install the provider plugin from the marketplace just yet as we're shipping it with Matomo core as a transition for a few months and then it will be updated through the marketplace. The error should go away with the next update. Apart from this we won't be changing anything for now as the error will be automatically fixed in 2-3 months (and also next time you update Matomo core). It's safe to remove this file though.

**Comment by tank-paradoxnft** [comment]
So is it going to be best to download the plugin zip from GitHub (https://github.com/matomo-org/plugin-Provider/releases/tag/4.0.3), extract, and then upload Provider.php and overwrite the current Provider.php that is throwing the error? 

I fixed the missing png by pulling it from the plugin zip, adding the directory "settings" (/plugins/Provider/**screenshots**/) and then adding the "Report.png" to it.

```
File size mismatch: /home/mrtank7/webapps/chronalytics/plugins/Provider/Provider.php (expected length: 3479, found: 4328)
Missing file: /home/mrtank7/webapps/chronalytics/plugins/Provider/screenshots/Report.png
```
So should I put back the file that was throwing the error or use the one I downloaded and installed (overwriting the one throwing the error)?

Here are the differences between the two Provider.php's (see Comparison Report "provider.pdf" below). The left is the file that was giving me an error and the file I was comparing it to was the Provvider.php I got from the zip I downloaded from: https://github.com/matomo-org/plugin-Provider/releases/tag/4.0.3

Comparison Report: [provider.pdf](https://github.com/matomo-org/matomo/files/7114420/provider.pdf)
