### ISSUE TITLE
Improve average page load time query accuracy (reporting too low in some cases)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#17012]
The metric **Page load time** is defined as `How long it takes to load the whole page, from requesting a page until it is fully rendered within the browser. This is the sum of all previous metrics.`

When looking at some of the websites reports, it seems this metric is (sometimes?) calculated wrongly.

For example [here](https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=26#?idSite=26&period=week&date=2020-12-15&segment=&category=General_Actions&subcategory=PagePerformance_Performance) seeing this report which says ` 0.2s Avg. page load time` but we'd expect the value to be approx 4s or 5s instead.

![Screenshot from 2020-12-24 09-46-35](https://user-images.githubusercontent.com/466765/103035799-f6ba9500-45cc-11eb-92d6-78e1028aca46.png)

the "Avg page load time" are shown correctly in the report table below though:

![Screenshot from 2020-12-24 09-51-16](https://user-images.githubusercontent.com/466765/103036029-98da7d00-45cd-11eb-9b0f-8f43bb1f2336.png)

so maybe the issue is only in this sparkline metric and how it's calculated?

The strange thing is that it sometimes seems to work correctly for example in the same instance for another website [here.](https://demo.matomo.org/index.php?module=CoreHome&action=index&date=today&period=week&idSite=36&updated=1#?idSite=36&period=week&date=2020-12-15&category=General_Actions&subcategory=PagePerformance_Performance) 

(but the problem is  reproduced in other instances for example [here](https://web.innocraft.cloud/index.php?module=CoreHome&action=index&idSite=12&period=day&date=yesterday#?idSite=12&period=day&date=yesterday&segment=&category=General_Actions&subcategory=PagePerformance_Performance)

**Comment by dev-101** [comment]
I noticed this long time ago, Google page load times are much higher (and more relevant to that matter). I always wondered how Piwik / Matomo reports such low overly optimistic numbers.

**Comment by dev-101** [comment]
Actually, my comment was erroneous in a way that I referred to old Matomo / Piwik metrics, which were completely unrealistic. I didn't know that you completely revamped this section and introduced new visuals, now those reports are much more realistic!

Sorry about any potential confusion, I haven't checked that section for a very long time, because it was kinda useless to me :)

_edit:_ Just to be clear, I am talking about data under **Behaviour > Performance** section (that one is good), not **Visitors > Overview > Visits Overview section > average generation time** (that one is still useless one I was talking about! - and it also includes AVG GEN TIME column in Pages tables!).
