### ISSUE TITLE
Missing metric "AVG. TIME ON PAGE" within the custom reports

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#17046]
Hi guys,
Would it be possible to add the following metric AVG. TIME ON PAGE within the custom reports premium feature configuration.
A client of mine would need to create a report with the following dimensions and metrics:
- User ID
- Page URL
- Pageviews
- AVG. TIME ON PAGE
Thank you

**Comment by sgiehl** [comment]
I guess it's not available as the dependent metric `sum_time_spent` is not available for custom reports.

**Comment by tsteur** [comment]
Hi @Chardonneaur for premium feature related requests could you email our support? That's shop@innocraft.com . Cheers :)

**Comment by KrzysztofMadejski** [comment]
@Chardonneaur do you know if that is available now in custom reports?

**Comment by atom-box** [comment]
This seems to have been misplaced; it was never moved to the proper board.  

Plugins like Custom Reports are prioritized in an internal backlog here at Matomo. I will add this request there once I hear back from that team, hopefully by tomorrow.

**Comment by goochj03** [comment]
Have had another customer inquiring about the 'AVG time on page' metric being available for custom reports.

**Comment by 9joshua** [comment]
Another customer requesting the same thing today.

**Comment by atom-box** [comment]
Another customer requested this today.

**Comment by atom-box** [comment]
The internal ticket for this is titled "Average time on page metric missing from custom reports. " FYI

**Comment by goochj03** [comment]
Another customer requesting this metric be available for Custom Reports

**Comment by goochj03** [comment]
Another customer has asked for the "AVG. TIME ON PAGE" metric to be available for custom reports.

**Comment by goochj03** [comment]
Have had a customer today stating they would like to see the "AVG. TIME ON PAGE" metric available in custom reports.

**Comment by paul-buttimore** [comment]
Another request today for the "Average time on page" metric for custom reports

**Comment by goochj03** [comment]
Another customer asking why "Average time on page" is not included in the custom report metrics.

**Comment by paul-buttimore** [comment]
Customer asking today why 'avg time on page' is missing from custom reports

**Comment by goochj03** [comment]
Another customer request to see 'avg time on page' included in Custom Reports.

**Comment by emernual** [comment]
Another customer request for this feature.

**Comment by Chardonneaur** [comment]
Another client asked for it today.

**Comment by goochj03** [comment]
Had a cloud customer wanting to use "AVG. TIME ON PAGE" in a Custom Report today. They would like to see this metric added as an option.

**Comment by atom-box** [comment]
@tsteur Can we open this issue?

**Comment by atom-box** [comment]
@sgiehl  _commented via an internal conversation (in Core: AVG time on page missing from metrics):_ 

This won’t be an easy fixable thing. The problem is how the time on page is stored and calculated.
The time on a page is not stored for the action itself. It is stored within the next action together with the id of the action it actually belongs to.
That fact makes it hard to select it in SQL on an action level without using very very cost intensive subqueries or joins. 

For the action reports we even execute extra queries to fetch that metric only and merge it into the action reports.
To solve this we need to develop a migration plan. We can’t simply change the way the metric is stored. Introducing a new dimension in the log_link_visit_action table would be be possible in a new major release, but we can’t update all old actions, as that would take too long. So we need to maintain code that is able to handle how it was previously store and how it might be stored in the future.

**Comment by Stan-vw** [comment]
Created a new comprehensive ticket for all the metrics that are missing from custom reports, which include avg time on page: https://github.com/matomo-org/matomo/issues/23196
