### ISSUE TITLE
enable_auto_update option misleading

### ISSUE THREAD

**Issue by vrandr** [piwik/piwik#17096]
I think the `enable_auto_update` option can be a little bit confusing. 

# What it does

Disable the "automatic update check".

# Confusion

Does it disable the `Update Automatically` function in the Web UI or not.

# Steps to reproduce

1. Setting `enable_auto_update` to `0`
1. `Update Automatically` option is still available in the Web UI (`CoreUpdater` action `newVersionAvailable`)
1. Updating the instance is possible 
1. After the successful update you'll receive an error: `An error occurred: Auto updater is disabled`

# Expected behavior

After setting `enable_auto_update` to `0` updates over the Web UI aren't possible any more.

**Comment by tsteur** [comment]
Cheer @vrandr technically, it was kind of already working because when disabled, Matomo would no longer look if an update is available. The method you mentioned would still work though if at the time of disabling a newer version was available. Added https://github.com/matomo-org/matomo/pull/17105 for now.

**Comment by Findus23** [comment]
I think #17106 is the correct linked issue.
