### ISSUE TITLE
Segments are not accurate

### ISSUE THREAD

**Issue by cleger80** [piwik/piwik#17128]
I have a segment for example :
PageURL Contains abc-home

The filter works fine for :
/en/abc/abc-home/
/en/abc/abc-home/something
/en/abc/abc-home/something-else
...

but I see also sometimes
/en/xyz-home/
/en/def/def-home/

How is it possible ?
What could affect it ?

I am on 3.14.1

**Comment by tsteur** [comment]
Hi @cleger80 

this is actually expected behaviour and we fixed a bug in some 3.X version to make sure it works like this as it used to falsely work like a filter https://github.com/matomo-org/matomo/issues/15438 (which is a not implemented feature yet).

For a workarounds have a look at eg https://github.com/matomo-org/matomo/issues/15438#issuecomment-663198958

refs https://github.com/matomo-org/matomo/issues/15130 https://github.com/matomo-org/matomo/issues/15341 https://github.com/matomo-org/matomo/issues/15211

**Comment by cleger80** [comment]
@tsteur  : May I kindly ask you to explain me what is the expected behaviour of a segment when I set up "PageURL Contains abc-home" ?

**Comment by tsteur** [comment]
@cleger80 it will find all visits that had viewed the given page URL and then shows you all page urls in the results all all these matching visits. So you basically can see which page views this group of visits were interested in.
