### ISSUE TITLE
What happens when a user denies consent and grants it later in the same session?

### ISSUE THREAD

**Issue by unikitty37** [piwik/piwik#17183]
(thank you, GitHub, for submitting the form when I pressed Enter in the subject box… how useful)

https://github.com/AmazingDreams/vue-matomo/issues/47 implies that, if a user denies consent and then later grants it in the same session, all the events that took place between denying consent and granting it will be tracked.

Is this true? My reading of GDPR is that, as consent was denied for those events, they should *not* be tracked, or even sent to the Matomo instance.

**Comment by diosmosis** [comment]
Hi @unikitty37, thanks for the interesting question! We discussed this internally and thought that this behavior could indeed be problematic for single page apps. However there's a simple solution in that the app could just not queue any tracking requests until it knows consent is given. Ie, only call the track methods on the JS tracker after consent is given. This puts the onus on users of matomo's JS tracker, so it would likely have to be implemented in the referenced library if not already done this way.

Since the question is answered, I'll close this now.
