### ISSUE TITLE
console does not have generate theme

### ISSUE THREAD

**Issue by sagarkale8** [piwik/piwik#17196]
My console does not show a generate theme option. I've installed/reinstalled matomo from git repo multiple times. Can someone help please?

![image](https://user-images.githubusercontent.com/50763788/107050852-bff1b480-67f1-11eb-8c36-7df51cf3c97a.png)

**Comment by sgiehl** [comment]
Hi @sagarkale8 
Most of those development commands require the development mode to be enabled.
`./console development:enable`

If you have any further question regarding theme or plugin development feel free to consult our forum at https://forum.matomo.org, as we usually don't ask questions here to keep our issue tracker "clean".

**Comment by Findus23** [comment]
Also keep in mind that you should install Matomo from git (as explained in https://developer.matomo.org/guides/getting-started-part-1) instead of using the matomo.zip if you want to use these generate options as they are intended for local development

https://github.com/matomo-org/matomo/issues/16922
