### ISSUE TITLE
All websites dashboard images may show as 404 

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17248]
Matomo 4.2

"All websites" dashboard (module=MultiSites&action=index)

The image is not displayed
![grafik](https://user-images.githubusercontent.com/1645099/108774886-8d211d80-7560-11eb-96c8-bf398d609deb.png)

404 error received
![grafik](https://user-images.githubusercontent.com/1645099/108775434-5c8db380-7561-11eb-906e-8a414cabfce0.png)

**Comment by Findus23** [comment]
This should be fixed with #17249
Indeed the URL for loading the image is generated incorrectly, but it seems no-one apart from you noticed this since 2014 as everyone else has their website set up so that `https://matomo.example/?someparam` is the same as  `https://matomo.example/index.php?someparam`.
