### ISSUE TITLE
Calender shows compare to previous period after page reload instead of period year

### ISSUE THREAD

**Issue by flamisz** [piwik/piwik#17414]
## Expected Behavior

When we choose "compare to previous year" in the calendar, after page reload, we'd like to see "compare to previous year" in the calendar when we open it.

## Current Behavior

When we choose "compare to previous year" in the calendar, after page reload, the dates and data are correct, but when we open the calendar, it shows "compare to previous period".

## Steps to Reproduce (for Bugs)

1. Open the calendar and set the period to day, week or month.
2. Choose "compare to previous year"
3. Reload the page
4. Open the calendar and check what it shows 

## Your Environment

* Matomo Version: 4.2.1 on demo site

The problem probably is that in the URL we don't save what kind of comparison is that, only the dates, so the data is correct, but the calendar doesn't know it is actually a "compare to previous year".

**Comment by mattab** [comment]
Thanks for contributing to this issue. As it has been a few months since the last activity and we believe this is likely not an issue anymore, we will now close this. If that's not the case, please do feel free to either reopen this issue or [open a new one](https://developer.matomo.org/guides/core-team-workflow#submitting-a-bug-report). We will gladly take a look again!
