### ISSUE TITLE
useEventValueAsRevenue still ticked after switching goal type

### ISSUE THREAD

**Issue by Findus23** [piwik/piwik#17500]
reported in https://forum.matomo.org/t/switch-goal-type-after-creation/41593/2

## Expected Behavior

One can create a goal with type "send an event" and afterwards switch the type successfully

## Current Behavior

- create a new goal with "send a goal" set
- tick `Use the event value (if it exists) as the goal conversion revenue.`
- save the goal
- edit the goal 
- change the type to "visit a given URL"
- notice how the "Use the event value..." UI dissapears, but still seems to be ticked
- save the goal
- see `'useEventValueAsRevenue' can only be 1 if the goal matches an event attribute.`

## Possible Solution
Whenever the UI is hidden, the value should also be set to 0 as 1 doesn't make any sense anymore

**Comment by leobardimpact** [comment]
This bug is still here. 

1. create a goal that has "goal is triggered: manually", set a "goal revenue: 10", save. Then maybe I did something I forgot to create a state of error.
2. edit the same goal. 
3. I had the gui in a state where 
  a. the goal value "10" was set
  b. but also use_event_value was checked. 
  c. the div "form-group row matomo-form-field" around the use_event_value was "display:none" 
  c. On save, there was an error message 'useEventValueAsRevenue' can only be 1 if the goal matches an event attribute.
4. my solution was to use Google Chrome dev tools to remove display:none from the div, uncheck the box, and save.
