### ISSUE TITLE
Can matomo heatpmapsessionrecording widget embed into a iframe

### ISSUE THREAD

**Issue by zkaitanx** [piwik/piwik#17550]
I try embed a heatmapsessionrecording widget to my page(my url like this:https://xxx.com/matomo/index.php?module=Widgetize&action=iframe&moduleToWidgetize=HeatmapSessionRecording&actionToWidgetize=showHeatmap&idSiteHsr=1&idSite=1&period=day&date=yesterday). But when i open the page, it will open a new window replace the origin page, is there  any solution to do open heatmapsessionrecording widget in a iframe and not open a new tab?

**Comment by tsteur** [comment]
Hi @zkaitanx thanks for reaching out. I just tried to reproduce and this works for me as expected. It doesn't replace the origin page for me. Are you using the latest version of Matomo and our heatmaps plugin? For example when you click on "Manage Heatmaps" and then on the "eye" icon next to a heatmap it should be opening such a URL like you mentioned and show the heatmap standalone.

When embedded in an iframe you can otherwise try to set the following setting in your `config/config.ini.php` as part of the `[General]` section.

```ini
enable_framed_pages=1
```

And then test if it works afterwards. If it still doesn't work, I suggest you email our support: shop@innocraft.com as we provide support for our premium features. In this issue tracker we usually only manage issues that relate directly to Matomo.
