### ISSUE TITLE
report information: "Report generated" without time unit (seconds?)

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17567]
![grafik](https://user-images.githubusercontent.com/1645099/118405099-4f6ef500-b676-11eb-8150-62871d15c80e.png)
link: https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&segment=&category=General_Visitors&subcategory=VisitTime_SubmenuTimes

## Expected Behavior
Information, when the report was generated

## Current Behavior
time unit missed (seconds, minutes, hours, days?)

## Possible Solution
time unit added

## Steps to Reproduce (for Bugs)
see above

## Your Environment
* Matomo Version: 4.2.1 (demo.matomo.cloud)
* Browser: Firefox
* Operating System: Windows 10

**Comment by Findus23** [comment]
I'm not entirely sure why, but `$this->metricsFormatter` is a `Piwik\Plugins\CoreVisualizations\Metrics\Formatter\Numeric` here
https://github.com/matomo-org/matomo/blob/6b12f37eb630d25dffa13e315b894abda80ed5af/core/Plugin/Visualization.php#L570-L575

which returns the number as-is instead of creating a proper text.

**Comment by flamisz** [comment]
Some tables (like Graph) are overwriting the text-formatter: 

https://github.com/matomo-org/matomo/blob/9c128ddd5a317ac42bd3e6f83d6fa8a3d5ef2519/plugins/CoreVisualizations/Visualizations/Graph.php#L89

I made a fix to use HTML-formatter when we format when a report was last updated.
