### ISSUE TITLE
Marketplace: "more" link does not work

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17561]
If you click in the marketplace on the "more" link, than nothing happens.

![grafik](https://user-images.githubusercontent.com/1645099/118395372-58e26800-b64a-11eb-9f84-585528af987b.png)

## Expected Behavior
more information will shown

## Current Behavior
nothing happend. The hash anchor jumps to the top of page:

module=Marketplace&action=overview&idSite=1&period=range&date=previous30&activated=&mode=admin&type=&show=# 

## Steps to Reproduce (for Bugs)
open the marketplace page and click on the "more" link on each plugin. See screenshot

## Your Environment
* Matomo Version: 4.2.1
* PHP Version: 7.4.3
* Browser: Firefox 88
* Operating System: Windows 10

**Comment by diosmosis** [comment]
@mathContao thanks for the report! Confirmed this is a bug. I also don't see any code related to handling the `'.more'` link so I don't know exactly what's going on there.

**Comment by tsteur** [comment]
I just checked and it is setting up a click event listener in https://github.com/matomo-org/matomo/blob/4.3.0-rc2/plugins/Marketplace/angularjs/plugins/plugin-name.directive.js#L51 but for some reason the element doesn't trigger the click event by the looks.

**Comment by math-GH** [comment]
there is no event appended on the link
![grafik](https://user-images.githubusercontent.com/1645099/118412047-21021180-b698-11eb-8a58-24dfe648e212.png)

**Comment by tsteur** [comment]
Hey @mathContao it does the onclick handler in the angular directive.

**Comment by flamisz** [comment]
The jquery dotdotdot plugin causes this issue. One solution can be if we simply use `style="overflow:hidden"` on the description. Anyway, when the description too long, we don't show the `more` link, because dotdotdot plugin cuts that. the only thing that would be different, if it's too long, we won't see the ellipsis (see attached images).
Other solution could be using some css, but that won't work on old browsers. ping @tsteur @diosmosis 
<img width="844" alt="Screen Shot 2021-05-17 at 10 17 04 AM" src="https://user-images.githubusercontent.com/6749509/118414542-4ffc9f80-b6f9-11eb-998b-a5c5121aa308.png">
<img width="823" alt="Screen Shot 2021-05-17 at 10 17 08 AM" src="https://user-images.githubusercontent.com/6749509/118414543-525ef980-b6f9-11eb-9593-6a699b87dbb3.png">

**Comment by tsteur** [comment]
> Other solution could be using some css, but that won't work on old browsers. 

Do you know which browsers it wouldn't work @flamisz ?

**Comment by flamisz** [comment]
On all IE:
<img width="924" alt="Screen Shot 2021-05-17 at 11 12 17 AM" src="https://user-images.githubusercontent.com/6749509/118415834-c94bc080-b700-11eb-8701-6c25aed015d4.png">
