### ISSUE TITLE
annoying banner (the 'refer matomo' banner at the bottom of the page)

### ISSUE THREAD

**Issue by dev-101** [piwik/piwik#17571]
No, seriously folks, I don't need this *reminder* in order to recommend something. Pls don't clutter already cluttered space with ridiculous popups and banners and what not. Pls don't make us use ad-blocker on our own self-hosted analytics ffs. Thx.

![piwik-banner](https://user-images.githubusercontent.com/5383059/118453272-4c681900-b6f7-11eb-8825-4dbd79ee02cf.png)

Instead, it would be better to actually ad a changelog for the latest version 4.3.0 here https://matomo.org/changelog/

**Comment by diosmosis** [comment]
Another complaint: https://github.com/matomo-org/matomo/issues/17581

**Comment by diosmosis** [comment]
Original issue for the banner: https://github.com/matomo-org/matomo/issues/16803

**Comment by tsteur** [comment]
Here are few tweaks to make:

* The refer banner should be first shown after 6 months (i think currently it is right away). So if `ReferReminder.getUserOption===false` then we'd set the time to in 6 months so it will be shown in 6 months (after a user has used it for a while). We may need to double check the reminder date won't overlap with the review reminder. Maybe, if no date for refer reminder is set but a date for the next review reminder then we might need to find a solution so they won't overlap and there is at least 6 weeks between them. To make this work we might have to change the review reminder from every 3 months to say every 6 months. Be great to have a think about this how this could work.
* We change the wording in the banner to `If you like Matomo please help us spread the word about us so more people get control over their analytics data. Share us on [social media icon]`. 
* We also change all link to https://matomo.org/ instead of the current landing page.
* We remove the refer matomo button. The social media share message stays the same for now.
* We have an option "never show again"
* We don't show it if any premium feature is installed. I think there is no method yet for this so far but we can probably iterate over all active plugins and call `$plugin->isPremiumFeature()` to find out if at least one premium feature is installed.

we could also make the look the same as when we ask for a review:

![image](https://user-images.githubusercontent.com/273120/118879783-3cde0f80-b945-11eb-82ec-04330cd4ccd0.png)

The title be then "Like Matomo?" etc. It be a bit like below but the icons be the social media ic/ons. This way the look be more consistent but we could also keep existing look if preferred.

![image](https://user-images.githubusercontent.com/273120/118880007-79117000-b945-11eb-98ae-6ce0377c8b85.png)

**Comment by flamisz** [comment]
Adding buttons/links like `Remind me later` and `Never ask me again` to a footer banner doesn't look very good and almost impossible in one line. 
So maybe the modal is the better option and this way we are more consistent as @tsteur mentioned.

**Comment by flamisz** [comment]
I have a PR for the first new version for this #17598.

That includes all the changes from @tsteur's comment, ~~except the `premium feature` related (yet).~~
I used modal instead of a banner.
