### ISSUE TITLE
"Visits over time" does not match with "visits in Real-time"

### ISSUE THREAD

**Issue by math-GH** [piwik/piwik#17608]
I think the "Visits Over Time" chart does not calculate the correct number for today:
![grafik](https://user-images.githubusercontent.com/1645099/119127965-5199d080-ba35-11eb-8964-7550912c2256.png)

The chart also does not update the numbers when I visit the Visitors:Overview section
![grafik](https://user-images.githubusercontent.com/1645099/119128218-a9d0d280-ba35-11eb-8c82-5ef4b89ef522.png)
The chart does not give a information that the calculation could be out of date. So I expect that this are the real time data.

HTML export of this chart:
![grafik](https://user-images.githubusercontent.com/1645099/119128402-e997ba00-ba35-11eb-9a91-97bac2878736.png)

## Expected Behavior
correct amount of visits

## Current Behavior
numbers looks not correct

## Steps to Reproduce (for Bugs)
set filter "day" from yesterday and today

## Your Environment
* Matomo Version: matomo.cloud
* Browser: Firefox 88

**Comment by diosmosis** [comment]
Hi @mathContao, can you contact cloud support at support@matomo.cloud and provide them with your matomo.cloud subdomain so we can look into it further?

**Comment by tsteur** [comment]
fyi @mathContao also note that these reports are updated only every few hours so you might not have seen the latest data yet and comparing the two numbers would only work around midnight because the number of visits/visitors in the last 24 hours might be different to the numbers during the day in the site's timezone.

* For example in the site's timezone will always look at the visits from 0:00-23:59:59 on that day
* Vs for example the last 24 hours would also include hours from the previous day. If you view the report at 10AM, then 14 hours of the previous day would be looked at too and if you had more visitors yesterday than today then the numbers are different.

As @diosmosis mentioned if you have more questions around this be great to contact support.

**Comment by math-GH** [comment]
@tsteur @diosmosis 
Ok, thanks for information. Please let us discuss some points:
1) I use Matomo on-prem and matomo.cloud. For me as a user I expect same/similar experience on both. On-prem the stats "Visits over time" is calculated with the newest numbers.
2) for me it is fine that not all stats are calculated with the newest numbers, but I expect an information about the age of stats. For exmple the "pages" stats  has an age information, where I see how old are the numbers. Most stats have this information behind the (?) icon
![grafik](https://user-images.githubusercontent.com/1645099/119326169-e98bfa00-bc81-11eb-8cea-e2e097aeaf42.png)
