### ISSUE TITLE
Required Private Directories "SSL certificate problem: unable to get local issuer certificate." warnings after upgrading to 4.3.0

### ISSUE THREAD

**Issue by TimothyAlexisVass** [piwik/piwik#17600]
Unable to execute check for https://xxxxxxxxxxx.se/config/config.ini.php: curl_exec: SSL certificate problem: unable to get local issuer certificate. Hostname requested was: xxxxxxxxxxx.se
Unable to execute check for https://xxxxxxxxxxx.se/tmp/: curl_exec: SSL certificate problem: unable to get local issuer certificate. Hostname requested was: xxxxxxxxxxx.se
Unable to execute check for https://xxxxxxxxxxx.se/tmp/empty: curl_exec: SSL certificate problem: unable to get local issuer certificate. Hostname requested was: xxxxxxxxxxx.se
Unable to execute check for https://xxxxxxxxxxx.se/tmp/cache/tracker/matomocache_general.php: curl_exec: SSL certificate problem: unable to get local issuer certificate. Hostname requested was: xxxxxxxxxxx.se
Unable to execute check for https://xxxxxxxxxxx.se/lang/en.json: curl_exec: SSL certificate problem: unable to get local issuer certificate. Hostname requested was: xxxxxxxxxxx.se 

This happened after upgrade.

## Expected Behavior
All certificates are valid and everything else works properly.

## Context
This doesn't seem to affect anything.

## Your Environment

* Matomo Version: 4.3.0
* PHP Version: 7.4.15
* Server Operating System: Debian 10
* Browser: Firefox 88.0.1 (64-bit) for Ubuntu

**Comment by Findus23** [comment]
Hi,

For the system check to see if those files are public Matomo makes a HTTP request to your own server using curl.
So it seems that while your certificates are valid and trusted by your users (otherwise tracking wouldn't work), your server itself doesn't trust the certificate. 
You can try this out by running `curl https://your.matomo/lang/en.json` on your server and see if the same error occur there too.

Maybe your CA list is outdated...

**Comment by TimothyAlexisVass** [comment]
After having done more testing with curl and wget with this and some other servers, it's safe to say that the issue is something other than matomo.
