### ISSUE TITLE
General Settings - no Email Settings

### ISSUE THREAD

**Issue by dguttierrez** [piwik/piwik#17621]
In general settings I'm missing E-mail Settings on two multiserver instances. 
On single Matomo instance there is no such error. 

* Matomo Version: 4.3.0
* PHP Version: 7.3.20
* Server Operating System: RHEL 7.8

**Comment by diosmosis** [comment]
Hi @dguttierrez this section is removed if the `[General] multi_server_environment` INI config option is set. This is because the mail settings are stored in the INI configuration file, and that file is not automatically synced between instances in a multi server environment. The solution to how to set this depends on how your environment keeps this file synchronized. If you are using a shared filesystem to synchronize updates to the file, then you can simply set `multi_server_environment = 0`. Otherwise, you'd need to manually set the `[mail]` options in the config file in each of your instances, however that is done for your environment.

Does this answer your question?

**Comment by dguttierrez** [comment]
Hi @diosmosis 

Tnx for your reply. Yes I have multi_server_environment set to 1. For syncing files I'm using lsyncd and sync files through three servers - one for admin (UI) and two for tracking - those two trackers are behind load balancer. So you suggest, that I don't need multi_server_environment set to 1?

I also have smtp settings in config.ini.php file, but now in version 4.3, when I tried to mail report, I get error, that smtp server is not reachable. But server is reachable and this works prior to version 4.3 - I have upgraded to 4.3 directly from 3.9.1. The same happened in my testing environment.

**Comment by diosmosis** [comment]
@dguttierrez 

> So you suggest, that I don't need multi_server_environment set to 1?

Possibly, no you don't. If you set it to 0, then the UI settings will display, and you'll be able to change the mail settings, for instance. Changing it will only change the config.ini.php file on the specific instance that's handling the request. If you have some way to synchronize the config.ini.php file on the other instances, then it should be fine and you shouldn't need to set multi_server_environment to 1.

> I also have smtp settings in config.ini.php file, but now in version 4.3, when I tried to mail report, I get error, that smtp server is not reachable. But server is reachable and this works prior to version 4.3 - I have upgraded to 4.3 directly from 3.9.1. The same happened in my testing environment.

This is likely a separate problem. Can you try running the `core:test-email` command and see what the output is?

**Comment by dguttierrez** [comment]
Hello

Thx for this command. I have found error. Connection to SMTP on port 25 has send STARTTLS which I don't use (internal mail relay). When I added encryption = "none" to config file, sending works.

TNX for help
