### ISSUE TITLE
Error in accessing plug-in Market

### ISSUE THREAD

**Issue by Amber-Wish** [piwik/piwik#17652]
When I wanted to install the plug-in from the plug-in market, matomo kept reporting this error. How to solve this problem?
![image](https://user-images.githubusercontent.com/55867470/121125322-f8190a80-c858-11eb-86dd-38bd508eb232.png)

**Comment by diosmosis** [comment]
Hi @Amber-Wish it seems like your deployment does not have access to the outside internet, which would be the case by default if your using docker. Can you confirm this? (Note: we don't provide support on how to configure docker so for specifics you will have to look elsewhere for your answer.)

EDIT: actually docker containers should have access to the internet depending on how you're using them, but I suspect that's the issue here.
