### ISSUE TITLE
Problems caused by service restart

### ISSUE THREAD

**Issue by Amber-Wish** [piwik/piwik#17651]
When matomo is deployed with docker, the plug-in needs to be reinstalled every time it is restarted. In addition, the authorization token of the API needs to be regenerated. It's very troublesome. Is there any way to avoid it?

**Comment by diosmosis** [comment]
Hi @Amber-Wish, unfortunately we don't answer questions on how to use or deploy matomo in this issue tracker but only handle feature requests or bug reports. That said, the issue here is likely that your docker containers are not using volumes. The folder containing plugins, your config and the tmp folder should be stored in volumes that persist outside of the docker container (though there are other ways to accomplish this so this should not be considered the official recommended way). The same goes for your mysql database's data files.

In the future we would rather you ask questions like this in our forum: https://forum.matomo.org/. Thanks for your understanding.

**Comment by Findus23** [comment]
I'd recommend you to contact the maintainer of the Matomo docker image you are using.

I think at least https://github.com/matomo-org/docker already does what @diosmosis is suggesting.
