### ISSUE TITLE
Improve UI of report info icon to show report generation time and help message

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#17815]
Icon for "Report generated X min ago" displayed for "Today" is too small 
## Expected Behavior

icon size consistent  with the ? icon next to it

## Current Behavior
icon smaller than the ? icon next to it, see screenshot:
![Screenshot from 2021-07-26 16-03-26](https://user-images.githubusercontent.com/466765/126931613-416db651-8aa9-4a4a-a92c-b482e4f9fac0.png)

## Steps to Reproduce (for Bugs)

* Open "Today" (period = day) in the calendar

## Your Environment
latest Matomo

**Comment by tsteur** [comment]
It's also a bit odd how it's shown on the very right and how it's always shown. It's visible "a lot" and the only thing that is shown on the right making it a bit disturbing for something that's rarely needed (and also available through the question mark). Maybe we could remove that icon and replace the original help icon with an information icon? This might make it more clear there might not be just "help" but also other information like time report ago @mattab . Since help is in the end also "information"

![image](https://user-images.githubusercontent.com/273120/127052547-dfc0c038-3d12-45a4-9563-13a7d0818378.png)

![image](https://user-images.githubusercontent.com/273120/127052630-8c6674ce-07fe-4ba8-ae04-4c759b4150e3.png)

**Comment by mattab** [comment]
Sounds good me to have only one icon. Maybe `?` is still better than `!` though? not sure...

Also could the tooltip be changed from  simply `Help` to be instead:
> Click to display help info about this report
> (Note: report generated 6min ago) 

(the second line would only be shown when "today" is included in date range)

**Comment by tsteur** [comment]
It's not a `!` it's an `'i` which is more clear/intuitive than the help I would say. Sure tooltip could be changed too.

**Comment by heurteph-ei** [comment]
I think that if the generation time is "hidden" in the information/help icon, users won't see it easily (they will forget the generation time display feature)
Why not always display the generation time for today graphs?

**Comment by tomper00** [comment]
After updating to 4.6.2 today the icon is still missing so the information about:  "Report generated" is still missing. 
<img width="1224" alt="icon missing" src="https://user-images.githubusercontent.com/366013/145850922-6c1a6dad-d850-47a3-8edf-2d5f458814ae.png">

**Comment by peterhashair** [comment]
@tomper00 thanks for letting us know. This is regression here. The report time icon is removed, but The report generated time should be displayed in helper like the screenshots below, but currently is missing, I will quickly do a hotfix for that.  
![image](https://user-images.githubusercontent.com/3783072/145908303-009ee509-e973-42d2-95d1-b7f2157fc3c8.png)
