### ISSUE TITLE
After watchtower auto-update, there is an error showing matomo docker AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by yche2990** [piwik/piwik#17911]
## Expected Behavior

It was working in the last version.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by Findus23** [comment]
This seems a lot like an issue in the operating system of your docker container and not the Matomo application. See for example `https://github.com/docker-library/wordpress/issues/630` for the same thing happening to a Wordpress user.

**Comment by tsteur** [comment]
@yche2990 maybe you meant to create this issue in https://github.com/matomo-org/docker ? Or if you are using a different docker maybe you meant to create this issue in a different repository? As @Findus23 mentioned this looks like a docker or OS issue rather than a Matomo issue. I will close this issue for now and if you meant to create this issue eg for our docker repository it be great to create the issue there.

If there is an issue with Matomo after all feel free to comment and we will happily reopen this issue.
