### ISSUE TITLE
Improve in-app feedback mechanism to gain insight from users about pain points

### ISSUE THREAD

**Issue by justinvelluppillai** [piwik/piwik#18186]
In line with our objective to generate a feedback loop to understand our users better this issue will allow us to combine our ideas and create a better feedback mechanism in Matomo than the existing thumbs up/down.

We will need to think about:

* UI changes
* CTA, eg "Not finding something you need?" or something that invites the right type of feedback
* Structured vs qualitative feedback (will we provide radios/checkboxes or text fields or a combination?)

refs 
* [x] https://github.com/matomo-org/matomo/issues/18232
* [x] https://github.com/matomo-org/matomo/issues/18250

**Comment by bx80** [comment]
I think a choice for structured feedback will help increase engagement since not everyone has the time or inclination to compose a message. While individual qualitative feedback has more value, aggregate structured feedback could provide a valuable reinforcing metric. If we can design a mechanism that can gather structured feedback on specific usage while retaining the option to provide more detailed comments or suggestions then we will have a broader range of user experiences from which to gain insights.

How many structured feedback questions are too many? Could 'Rate your experience' [1-5 star] coexist with a rating dependent 'How could this be better?' ['Better help', 'More intuitive UI', 'More options', ...] or 'Why did you like this?' ['Easy to use', 'Configurable', ...] ?

That would be as little as three clicks to get a general rating for feature combined with an easy to analyze tag for improvement, without removing the option for more detailed written feedback.

If the delivery mechanism for feedback is to be an automatically generated email then we could add specially formatted tags from structured feedback data which could be automatically aggregated into a report when the email is received. eg. every feedback email with [Goals-Chart-Rating-4] would affect the rating for the Goals Chart feature or [Goals-Chart-Improve-Better-Help] would be another vote for improving the help in that area.

**Comment by tsteur** [comment]
Here are specs:

* [ ] Require a message to be entered. Sending feedback will only work when at least 5 characters entered. Otherwise we show a message telling them to enter a message. Or maybe we could also highlight the textarea red or so.
* [ ] When hovering a title, directly show both thumbs up and down, not just the thumbs up initially and on hover of the thumbs up the thumbs down. As soon as we show thumbs up, we also want to show immediately thumbs down alwatys.
* [ ] In the popups where you enter the feedback show the buttons in the bottom like in below screenshot. Basically `send feedback` needs to have css class `btn` not `btn-flat` 
![image](https://user-images.githubusercontent.com/273120/139356045-0ddacd29-a311-4dca-a61b-4c0a1a8c21ba.png)

### If they click on thumbs up

* [ ] Use below wording

**What do you like about this feature?** (“this feature” to be replaced with feature name where we have it)
Please let us know more about how you use this feature so we can improve Matomo further. Thank you ❤️

* [ ] Use below thank you screen for the good rating

![image](https://user-images.githubusercontent.com/273120/139356205-2af803b8-3524-41fe-a473-91cd89cd0c97.png)

* [ ] Note the button in above screen should say `Close`, not `OK`.

### If they click on thumbs down


* [ ] Use below wording

**How can we improve this feature?** (“this feature” to be replaced with feature name where we have it)
Please let us know more about how we can do better so we can improve Matomo. Thank you ❤️

* [ ] Thank you confirmation 
![image](https://user-images.githubusercontent.com/273120/139356341-9a24e50a-1b63-4e21-aa9a-4c008112d90f.png)

Text:
**Thank you for helping us to make Matomo better!**
We really appreciate your feedback. ❤️  We will be in touch in case we require more information about your feedback.

* Note here also the button in above image should be `Close` and not `OK`. 

### Tooltip text

When hovering the thumbs icons, let's change the below message 

![image](https://user-images.githubusercontent.com/273120/139356889-116fed3a-9317-4d26-8d52-506c9369065b.png)


To: `Do you like the '...' feature? Please let us know so we can improve Matomo`

If easily doable, the email we receive with the feedback could also track the source whether this was from On-Premise, Matomo for WordPress or the demo. This may not be that easy though. On the Cloud this feature is not available so it might not be that important.

**Comment by tsteur** [comment]
> 'How could this be better?' ['Too difficult to use', 'Lack of features', 'Buggy', 'Too slow', 'Other', ...]  (if click on thumbs down)
> or 'Why did you like this?' ['Easy to use', 'Configurable', ...] ? (if click on thumbs up)

Having a select option in the feedback additionally could be otherwise good too. Once this feedback has been sent, we could then follow up with showing a textarea and asking for more details.

Like we always show the radio fields (single choise) on the top, and then adjust the textarea description

![image](https://user-images.githubusercontent.com/273120/139374199-0ec75e67-c9c5-4224-a9c2-341fcd45a27f.png)

I couldn't prepare proper UI but imagine it looked better and there be radio fields :) 

however, I'm not sure what to show as options for "why do you like this"

**Comment by bx80** [comment]
@tsteur Can I clarify if we're going to a) show a single dialog with select option choices at the top and optional text comments below, or b) if we're going to first show a mandatory text feedback dialog and then after submitting that show another dialog with selection option choices and then send that as a second email?

Seems like a single dialog would be a better UX?

**Comment by tsteur** [comment]
I was thinking `a)`. And then the question for the text comment changes depending on the selected field. The textarea could be hidden or disabled until a radio field has been selected. So all in a single dialog 👍

**Comment by GreenReaper** [comment]
I wanted to give feedback but I got an error: "Could not instantiate mail function." This is correct; the system is not set up to send mail, but it would've been nice if it suggested an alternative method to give feedback. Or better, if it didn't rely on mail; or didn't solicit the user to send feedback if it wasn't going to work, though I'm not sure if you can easily determine that before trying.

**Comment by sgiehl** [comment]
Hi @GreenReaper 
Thanks for your suggestion. I'll create a new issue with your feedback. It would indeed be valuable to at least give the user an alternative method to send the feedback if mail doesn't work.
