### ISSUE TITLE
Notice - A non well formed numeric value encountered in Goals API

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18261]
Below warnings I can see in our own Matomo. It refers to this line https://github.com/matomo-org/matomo/blob/4.6.0-b2/plugins/Goals/API.php#L513

> WARNING CoreHome[2021-11-02 23:33:27 UTC] [ee954 ] core/Metrics/Formatter.php(161): Notice - A non well formed numeric value encountered - Matomo 4.5.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) #0/core/Metrics/Formatter.php(161),#1/plugins/CoreHome/Columns/Metrics/ConversionRate.php(42),#2/core/Metrics/Formatter.php(202),#3/plugins/Goals/API.php(522),[internal function]: Piwik\Plugins\Goals\API->Piwik\Plugins\Goals\{closure}(),#5/core/DataTable.php(512),#6/core/DataTable.php(618),#7/core/DataTable/Map.php(97),#8/core/API/DataTablePostProcessor.php(303),#9/core/API/DataTablePostProcessor.php(133)

We have probably hundred of these entries for each request where this happens.

Let me know if more details is needed to find the problem.

**Comment by sgiehl** [comment]
@tsteur are you able to figure out an example url where that happens?
I would assume the reason is kind of explained in the comment here maybe:
https://github.com/matomo-org/matomo/blob/4fe950ae94b0fe3bd13f928544ff876275fe6733/plugins/Goals/API.php#L513-L524

It says the data is normally queried with `format_metrics=0`, but to get formatted metrics nevertheless, the formatter is applied.
I actually wonder if the problem occurs if a compare is requested with `format_metrics=1`? In that case the metric might already be formatted, but the formatter is applied again nevertheless. Maybe the problem would be solved if we extend the condition with an direct check if `format_metrics === 0`

**Comment by tsteur** [comment]
Indeed it might only happen when comparing. I view a specific goal report for a week, then compare a segment, and then see this in the logs. I don't have a specific URL though.
