### ISSUE TITLE
Remove glossary notes in Weblate CLA field

### ISSUE THREAD

**Issue by comradekingu** [piwik/piwik#18324]
https://hosted.weblate.org/contributor-agreement/matomo/glossary/?next=/projects/matomo/glossary/

When any list of strings is loaded that has glossary strings included, none of them can be translated in Zen mode.

Remove it form https://hosted.weblate.org/settings/matomo/ and add it to the info field in https://hosted.weblate.org/settings/matomo/glossary/#basic

**Comment by sgiehl** [comment]
@Findus23 can you have a look at that?

**Comment by Findus23** [comment]
@comradekingu I removed the CLA.
While I wish that every single person editing the Glossary has read this text:
> This is the glossary for important words and phrases in the Matomo project.
> Please refer to the existing usage in the Matomo translations before making any changes here as ideally this glossary should reflect the canonical translation for terms like "Goal", "Measurable" or "Pageview". 
> The existing entries were imported from Transifex and might not be correct.

You are right that using the CLA for this is not the correct way and seems to break in all kind of weird ways. (which you might want to report as bugs to Weblate).

Unfortunately, I can't add something to the info text just for the glossary as it is project wide. So I updated that text with a short summary and hope everyone sees it, instead of quickly bringing the glossary to 100% without checking the existing translations.

**Comment by comradekingu** [comment]
@Findus23 You can add an announcement in just the glossary component (without alerting users).
https://hosted.weblate.org/projects/matomo/glossary/#announcement

Edit: The issue with not being able to use Zen mode didn't get fixed though.
I think maybe some component is still locked. Not all of them are linked.

**Comment by Findus23** [comment]
I'm not sure if more people read old announcements than the page info.

Can you describe in more detail how Zen mode doesn't work for you? I can see https://hosted.weblate.org/zen/matomo/matomo-base/de/?q= perfectly fine.

**Comment by comradekingu** [comment]
@Findus23 Announcements are displayed at the top of the page.
I see the Zen mode too, but can't save anything.
There is an error popping up without text, and then the field status next to the string just blinks.

**Comment by Findus23** [comment]
Even editing works fine in zen mode for me. 

Can you maybe check if your ad-blocker isn't just blocking requests with "matomo" in the URL?

**Comment by comradekingu** [comment]
Ah yes, uBlock origen with the filters I have blocks it.
I'll try to have it allowed.
Closing since the CLA is gone :)
