### ISSUE TITLE
Goals by dimension view might not fully show

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#18373]
![image](https://user-images.githubusercontent.com/273120/143310768-646f1900-88cc-40d9-a825-bce9fd23849f.png)

I think this has happened the first time around merging https://github.com/matomo-org/matomo/pull/18243/files 

I can reproduce this sometimes locally when I have say 15 goals, and load a range etc.

It's like the "by dimension" view loads faster than any of the goal reports and then maybe thinks there's less width available or something.

Not 100% sure it's a regression but haven't really noticed this before

**Comment by sgiehl** [comment]
This might more likely be a regression from the sticky headers. I'm able to reproduce that locally on the goals overview, when switching between custom date ranges (not on the initial page load), but didn't yet find a proper fix.
The problem seems to be here:
https://github.com/matomo-org/matomo/blob/8066b3536c2399e1c2992c9ee4607b3985b94b42/plugins/CoreHome/javascripts/dataTable.js#L428-L434

For some reason `$table.width()` is only `100` in some cases and thus the `max-width` is set to `60`.
I tried a couple of fixes, but each fix I tried broke it somewhere else. If anyone else wants to have a look, feel free to do so. I already spent too much time with that fragile code 🤯  If not I might try to continue with that tomorrow.
