### ISSUE TITLE
Allow users with reduced access to Tag Manager. 

### ISSUE THREAD

**Issue by jmumby** [piwik/piwik#18512]
The minimum level for a user to have sufficient access to Tag Manger is admin. 

Can we have access to the tag manager independent to that of the Matomo user level? Some users have third parties manage their tag manager and do not want to allow the temporary user to have admin access to their Matomo. Alternatively, allow view access to have the required privileges to edit and publish tags.

**Comment by tsteur** [comment]
@jmumby this should be already possible using capabilities. Eg someone with view access can have the "write tag manager capability". Also users with "Write" access should directive be able to edit the tags.

Let me know if there's an issue and I'll be happy to reopen 
 
![image](https://user-images.githubusercontent.com/273120/146434286-c2dbbc7b-f11f-476d-9e15-9263fb5a31a9.png)

**Comment by atom-box** [comment]
A user has requested the opposite.  
Custom Reports editing: **Yes**
Tag Manager editing: **No**

This could take the form of an X in this view, near the (2), allowing us to rescind the [_MTM:Write_ capability] from a user who otherwise has [_Write_ role].
![image](https://user-images.githubusercontent.com/22874146/220778244-8aa228cd-10b3-47f8-92b7-0e6680ab1e06.png)
