### ISSUE TITLE
Running report from 2021-12-01 to 2021-12-31 returns no data

### ISSUE THREAD

**Issue by wadih** [piwik/piwik#18561]
Hi,

Running report from 2021-12-01 to 2021-12-31 returns no data.

However running report from 2021-12-01 to 2021-12-30 returns full data set. 

Looks like a bigger or equal conditional logic at play somewhere.

![2022-01-02_15-30_1](https://user-images.githubusercontent.com/1222066/147888691-ff99fc00-997c-48e5-a303-1f807b6a08d2.png)
![2022-01-02_15-30](https://user-images.githubusercontent.com/1222066/147888692-a7e74792-e14f-4c82-9402-a8b6c36238a2.png)

**Comment by bx80** [comment]
Hi @wadih, thanks for reporting this issue. 

When running the report for 2021-12-01 to 2021-12-30 report data is calculated on-demand and then cached since this is a custom date range. But when running the report for 2021-12-01 to 2021-12-31 this date range maps to entire month and so the pre-generated monthly data for December will be used.

As you are not seeing any data for the December month then it seems likely that this monthly data has not been generated for some reason.

You could try invalidating the cached data for December 2021 with 

`./console core:invalidate-report-data --dates=2021-12-01,2021-12-31 --periods=month --site=[your site id]`

and regenerating it with:

`./console core:archive`

**Comment by wadih** [comment]
Hi @bx80,

You are right, after running those two commands, it now works. 

I had to make console executable first, and it didn't recognize --site, so I ran:

```
./console core:invalidate-report-data --dates=2021-12-01,2021-12-31 --periods=month
./console core:archive
```

Thank you so much. I will go ahead and close the ticket.
