### ISSUE TITLE
Comparing two segments in goals, sets the graph to all zeros for the first segment

### ISSUE THREAD

**Issue by ghost** [piwik/piwik#18783]
When you go to the tab goals and select a specific goal, the graph and overview data show the amount of conversions for the current segment. Sometimes when you compare a secondary segment, the first segment shows all zeros on the y-axis in the graph. The overview below the graph still shows the correct numbers. (See screenshots).

I've tried this with several segments, and it looks like this is the case when the first segment contains multiple conditions. Furthermore, if the first segment contains just one condition, and the secondary segment contains multiple conditions, it does work.

![Screenshot_20220212-102414_1](https://user-images.githubusercontent.com/11771529/153706337-e4c0b013-cbcc-467e-9a32-2c9138fb1fcc.jpg)
![Screenshot_20220212-102247_1](https://user-images.githubusercontent.com/11771529/153706345-a7d81f97-525c-406a-a667-d54a5f238f57.jpg)

**Comment by sgiehl** [comment]
@conflate-nl Thanks for creating this issue. It might have something to do with the segment definition. The evolution chart doesn't show the segment name in the series labels, but the definition. I'm wondering if the reason for that might maybe be the space in the segment definition. Does the behavior change if you switch the segments in the comparison?

**Comment by ghost** [comment]
@sgiehl I did check this indeed
> Furthermore, if the first segment contains just one condition, and the secondary segment contains multiple conditions, it does work.

So yes, switching the segments does work :-)

**Comment by sgiehl** [comment]
I tried digging deeper into that for a while. So the issue seems to be the space in the segment definition, but only if the segment is used as base segment to be compared with. The requests sent to load the widget don't contain the original segment like `deviceType%3D%3Dfeature%252520phone`, but `deviceType%3D%3Dfeature%2520phone` instead. So the space isn't triple, but only double encoded.

@diosmosis Could you have a look at that one? It seems to be a regression from the vue migrations, as it used to work e.g. in Matomo 4.6.0.
