### ISSUE TITLE
Checkbox "keep url fragmets" always checked

### ISSUE THREAD

**Issue by chopsol** [piwik/piwik#19061]
In "global websites settings", the checkbox for "URL fragments" is always active. If you save the settings, this option is also always saved as Active, even if you deactivate the checkbox. This captures URL fragments even if you don't want them to. You have to explicitly deactivate this option in the settings for the respective website. That's where it's stored, possibly because it's a select list there.
There are similar errors in the Tag Manager, where you can no longer set the priority of the tags and the delay.
I only noticed these problems from 4.8.0 and have reproduced them in 8 instances

![matomo-fragments](https://user-images.githubusercontent.com/12293848/162203457-87e39e1d-4ca9-47e6-8dbd-3eab6537874e.png)

**Comment by sgiehl** [comment]
Hi @chopsol. Thanks for creating the issue. I was able to reproduce that. This is most likely a regression from migrating the UI to vue js.

@diosmosis could you have a look at that one. Guess the problem is that the variable is sent as `true` / `false` with the request. Might need to be changed to `0` / `1`. Not sure if that might be a general issue of check boxes maybe

**Comment by diosmosis** [comment]
I created a PR to fix the boolean value issue, but I couldn't reproduce the tag manager priority / delay issue in 4.9.

**Comment by chopsol** [comment]
@diosmosis the problem i mentioned was fixed before here https://github.com/matomo-org/tag-manager/issues/459
