### ISSUE TITLE
Geography Statistics - ACT not present under Australia

### ISSUE THREAD

**Issue by avimaymon** [piwik/piwik#19283]
## Expected Behavior
There should have been a state called ACT under Australia

## Current Behavior
No ACT state under Australia which makes it impossible to identify usage for ACT alone

## Possible Solution
Add it as a country under Australia

## Context
Because of this bug users can't distinguish usage from ACT alone

## Your Environment
The other details will be added shortly
* Matomo Version: 4.9.0
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser: Microsoft Edge
* Operating System: Windows 10

**Comment by peterhashair** [comment]
@avimaymon thanks for reporting this our product team will prioritize it from here

**Comment by sgiehl** [comment]
Hi @avimaymon 
I assume this issue is regarding the maps being displayed in Matomo. Those are unfortunately outdated and missing some country regions. We are planning to update our maps at some point, which should then also include those missing regions. See #11929

In the list of regions it should actually be available named "Australian Capital Territory". At least it is defined. If it doesn't show up, that could also mean that the geolocation your are using is not able to identify users in that region correctly.

I will close this issue as we won't work on this specific map issue separately, but as part of #11929
