### ISSUE TITLE
Error Message "There was an error setting cookie `mtm_consent_removed`. Please check domain and path" on every page load, when requireConsent option is set

### ISSUE THREAD

**Issue by Constantin-Init** [piwik/piwik#19488]
When the requireConsent option is set, every page load logs the error message "There was an error setting cookie `mtm_consent_removed`. Please check domain and path" to the console.

Reason seems to be that during creation of a Tracker `forgetConsentGiven` is being called, which then calls `setCookie(CONSENT_REMOVED_COOKIE_NAME, ...)`. `setCookie` sets the cookie properly, but wants to check that it is indeed set with a call to get `getCookie`, which then fails, because `configCookiesDisabled` is set to true at this point, and the function returns 0

Fix would be make the behavior of `getCookie` and `setCookie` in regards to the `CONSENT_REMOVED_COOKIE_NAME` and `configCookiesDisabled` the same.
The change to `setCookie` was introduced here https://github.com/matomo-org/matomo/commit/9e10a150585522ca30ecdd275007a882a70c6df5

**Comment by sgiehl** [comment]
Hi @Constantin-Init 
Thanks for creating this issue. Guess this should be easily fixed by doing the same check in `getCookie` as well.
I'll put up a PR to fix that.

**Comment by ghnp5** [comment]
I noticed I was getting this on every page load, for both "mtm_consent" and "mtm_cookie_consent".

The cookies seemed to be already set, but for some reason, Matomo was failing to set them.

Then I removed the cookies manually (through DevTools) and the issue went away.

I wonder if some Matomo update changed something with the cookies, and the existing cookies were somehow conflicting with the latest Matomo version, that it tried to set them again, but failing.

Now it will be hard to debug, since it's no longer happening to me. But just wanted to put the comment here, in case it brings some lights to you.

Thank you!
