### ISSUE TITLE
problem with map tooltip and accented letters

### ISSUE THREAD

**Issue by paolobenve** [piwik/piwik#19500]
A cuban province, **Camagüey**, appears as **Camagey** in the map tooltip. Looks like a utf8 issue

Matomo version: 4.10.1

![camagey 1](https://user-images.githubusercontent.com/1417508/178106108-3c4be8c8-1a52-49ea-a96b-f7639ee7560c.png)

**Comment by bx80** [comment]
Hi @paolobenve, thanks for spotting this. I've created a PR to correct the name

**Comment by paolobenve** [comment]
is it not a problem with a cuban province, it's a problem with utf8 non-ascii text: see other cuban provinces with accented letters: Pinar del Río, Ciego de Ávila, Guantánamo.

I suppose it's a problem with all the tooltips which involve accented letters

**Comment by bx80** [comment]
@paolobenve My mistake, I thought it was just an issue with a single province name. You are correct - accented characters in many (but not all) map names are missing, this seems to have been a UTF-8 issue with the initial map SVG files that were generated sometime before 2013. There have been various fixes since to correct individual countries that have places with accented characters .

I expect at some point the visitor map code will receive a major overhaul as it uses libraries that are no longer maintained, but in the meantime I'll can at least adjust my fix to correct all Cuban province names.
