### ISSUE TITLE
Remove again the "refresh" icon 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#19515]
The goal of this issue is to revert the PR https://github.com/matomo-org/matomo/pull/19261 so that the Refresh icon is again removed.

We discussed quickly with @tsteur and agreed this icon creates clutter but doesn't really bring much value in the end. Most reports will never change unless they include today anyway. And the icon doesn't look good or consistent so it's just easier to remove it at this point. 

This icon here and associated logic should be removed again:
![image](https://user-images.githubusercontent.com/466765/178422141-8accb6ed-5e08-4d83-af22-3a1855ccb4be.png)

**Comment by sgiehl** [comment]
@mattab That PR fixed an issue that was actually created by @tsteur (#11047). It might not look best and we maybe could improve that further, but I strongly dislike reverting PRs that were contributed by volunteers from the community. If that would have happened in the beginning of my contributions I might have stopped doing further contributions at all.

I strongly urge you and @tsteur to at least look through all the issues you had created in the past and close those you don't want to see implemented anymore. We should at least be able to trust that the tickets we create are reasonably up-to-date. Otherwise it is not only a waste of time for the person who invests his time to implement something, but also for us to review (and then revert something).

**Comment by mattab** [comment]
Sorry about the trouble here, and thanks for the feedback!

We'll try and review our created issues but realistically we don't have the time at the moment and for the next few months. In the meantime, we need to involve our UX expert and PM to assess early on, whether we want to do a given issue. They are the experts that know whether a given issue is still worth it or not. (and they can ask us questions to get our updated thoughts etc.)

In the meantime we do need to revert the change because we don't want to have this new icon forever in the app and it provides too little value and creates "UI noise" that is not helping our users.

**Comment by sgiehl** [comment]
@mattab In that case maybe we should leave somewhere a clear advice that people who want to work on an issue should first leave a note there, so you can decide if it makes sense to do so or not (if needed).

Btw. I don't think we need to fully revert https://github.com/matomo-org/matomo/pull/19261. It also added a keyboard shortcut to refresh the page. I guess we could at least keep that one, but only remove the icon?

**Comment by Findus23** [comment]
I guess [CONTRIBUTING.md](https://github.com/matomo-org/matomo/blob/4.x-dev/CONTRIBUTING.md) would be a good location.

**Comment by mattab** [comment]
Opened PR in https://github.com/matomo-org/developer-documentation/pull/646/files

**Comment by peterhashair** [comment]
The refresh icon is removed, close the issue.
