### ISSUE TITLE
Config.ini.php file not getting reflected

### ISSUE THREAD

**Issue by Prithivi-Rajan** [piwik/piwik#19523]
We are currently running the Matomo as a container in AWS ECS. Now, I’m trying to update the config.ini.php file and get that pushed via Dockerfile. But for some reason the setup works in my local environment and same doesn’t work in AWS ECS.

## Expected Behavior
 Values in config file should work
[General]
datatable_archiving_maximum_rows_actions = 10000
datatable_archiving_maximum_rows_referrers = 10000

## Current Behavior
 Values in config file is not getting updated.
datatable_archiving_maximum_rows_actions = 500
datatable_archiving_maximum_rows_referrers = 1000

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version: 3.13.5
* PHP Version:
* Server Operating System: AWS ECS
* Additionally installed plugins:

* Browser: Chrome
* Operating System:

**Comment by bx80** [comment]
Hi @Prithivi-Rajan, it seems likely that this issue is related to your Dockerfile / ECS setup. Unfortunately we cannot provide support for this via github, however you might be able to find further assistance in our forums here: https://forum.matomo.org/ or via a paid support plan https://matomo.org/support-plans/
