### ISSUE TITLE
Handle encoding in translation files

### ISSUE THREAD

**Issue by atom-box** [piwik/piwik#19626]
In the French translation, a character (ampersand poundsign 039) is not displaying correctly in the view for
⚙️ > System > Import > Google analytics

![image](https://user-images.githubusercontent.com/22874146/184416901-f3a96df5-c2a6-427b-a42d-17aacefa5312.png)

**Comment by Findus23** [comment]
The translation string is correct (https://hosted.weblate.org/translate/matomo/plugin-googleanalyticsimporter/fr/?checksum=f881f6f5577e3d1f), so this is an issue in all languages and just doesn't appear in English because there are no non-letter-characters there.

Maybe we should expand the [Matomo "development" language](https://github.com/matomo-org/matomo/blob/4.x-dev/core/Translation/Loader/DevelopmentLoader.php) to a proper pseudolocalization where random non-ascii characters are added/replaced and increase the length of the English string by X% (as often things are cut off in the German translation simply because things are longer in German)

**Comment by sgiehl** [comment]
refs https://github.com/matomo-org/matomo/pull/19190

**Comment by sgiehl** [comment]
I think this one should be fixed with #19190.
