### ISSUE TITLE
Why the color of Taiwan is difference with other Province of China, Taiwan is part of China. Do not make the mistake!

### ISSUE THREAD

**Issue by canuonifeng** [piwik/piwik#19701]
![image](https://user-images.githubusercontent.com/8425355/187937399-de6e8bff-3a5c-4654-bc1e-432029883ff8.png)

**Comment by sgiehl** [comment]
Hi @canuonifeng 
Our maps have been contributed by a former contributor years ago. As the tools to generate/update the maps don't work anymore, we are currently unable to make any bigger changes to our map. Due to that fact they are unfortunately fairly outdated.
We are planning to replace our maps in #11929. But as we still don't have enough free capacities, it might take some time, till we are able to tackle it. If you a familiar with maps in general and Matomo, feel free to comment on #11929 if you want help starting some work towards replacing our maps. 
Cheers.

**Comment by xunguo2** [comment]
@sgiehl
When it comes to national sovereignty, you should take it seriously

**Comment by sgiehl** [comment]
This is an open source project. Feel free to contribute. I don't have enough time to work on #11929 nor do I have enough experience with map related stuff or frameworks.
