### ISSUE TITLE
I crashed Matomo by screwing around with composer.json

### ISSUE THREAD

**Issue by Nyaundi** [piwik/piwik#19752]
I tried to install a custom script. then It crased the whole system, This is the error log
[Wed Sep 21 03:20:30.607789 2022] [php:error] [pid 119833] [client 99.41.201.237:59292] PHP Fatal error:  Uncaught Error: Class "Piwik\\Plugin\\Manager" not found in /var/www/matomo/core/boot>
Any idea?

**Comment by peterhashair** [comment]
@Nyaundi this is really hard to tell what are the factor causing that issue, but if you have version control set up, you can always revert back. 

For further help, I'd like to refer you to our forum at https://forum.matomo.org/, as we usually don't do any troubleshooting on GitHub, due to our limited resources. Thanks!

**Comment by bx80** [comment]
Hi @Nyaundi, 

That error would indicate that the autoloader isn't functioning as `\Piwik\Plugin\Manager` is the very first auto loaded class in the application. Without knowing exactly what was changed it's hard to suggest a solution, but you could consider trying:
- restore the composer.json from the Matomo installation archive and run `composer update` again
- delete the `vendor` subdirectory and attempt a `composer update` to complete reset the library configuration.
- backup your `config/config.ini.php` file and reinstall

Although we can't offer support for non-application issues via github, you might be able to find additional help in the [Matomo forums](https://forum.matomo.org/).
