### ISSUE TITLE
Segment just created, and real-time processing of segments is disabled, And Segment has no data, the message is not displayed at the top to warn it may take some time display

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#20060]
expected notification:

![image](https://user-images.githubusercontent.com/466765/204420804-b94f82ec-afdb-4e57-bd65-6e3ef93dd38b.png)

we reproduced on Cloud this wasn't displayed after creating a segment.
This may be a regression in core?

**Comment by heurteph-ei** [comment]
There was another issue about this notification in case of empty report (because no data, not because not processed), but impossible to find it again... 🤔

**Comment by justinvelluppillai** [comment]
Let's make sure we add UI tests once this is resolved so we can catch if it regresses again

**Comment by sgiehl** [comment]
I'm actually not able to reproduce that problem locally. When browser archiving is disabled and I create a new segment the notification is shown. And there is a UI test for exact this case:

https://github.com/matomo-org/matomo/blob/a81d55323a9c9a80694609ab131c9ce46f956f63/plugins/SegmentEditor/tests/UI/UnprocessedSegment_spec.js#L48-L61

![result](../blob/a81d55323a9c9a80694609ab131c9ce46f956f63/plugins/SegmentEditor/tests/UI/expected-screenshots/UnprocessedSegmentTest_unprocessed_default_segment.png?raw=true)

The only change around that logic I could find is https://github.com/matomo-org/matomo/pull/18540

**Comment by peterhashair** [comment]
I can't reproduce this locally as well. Will try again today.

**Comment by justinvelluppillai** [comment]
@mattab are you still able to reproduce this issue and provide info about the steps?

**Comment by mattab** [comment]
@justinvelluppillai it can be reproduced on Cloud (in our instance), but i haven't reproduced on on-premise  yet, but you had maybe reproduced it before? or maybe it's just an issue on Cloud

**Comment by mattab** [comment]
fyi reproduced today again on Cloud, created a random segment and there was no notification box:
![image](https://user-images.githubusercontent.com/466765/210485040-b3fb4003-8be2-4a16-a599-565d3f39cf3f.png)

**Comment by mattab** [comment]
Because the issue is only happening on Cloud, we will close it here, and Cloud team will investigate.

**Comment by mattab** [comment]
reproduced on demo2

**Comment by sgiehl** [comment]
Relevant config values that are e.g. used on demo2:
```
browser_archiving_disabled_enforce = 1
enable_create_realtime_segments = 0
enable_browser_archiving_triggering = 0
process_new_segments_from = "last60"
```

**Comment by bx80** [comment]
I can recreate this on locally and on demo2 by creating a new segment which will not return any visits for the selected time period.

For example:

1. Use a site with a day selected containing only visits between say 6am to 11pm
2. Create a new segment "Site - time hour is not 3am"
3. The segment unprocessed message will be shown because there are visits for this segment in the selected time period.
4. Create a new segment "Site - time hours is 3am"
5. The segment unprocessed message will **not** be shown because there are no visits for this segment in the selected time period.
6. Change the time period to a whole year where there will be some visits at 3am, now the segment unprocessed message will be shown.

This is because of the code ['if no visits recorded, data will not appear, so don't show the message'](https://github.com/matomo-org/matomo/blob/9183b6dbd106447d3605da90db70be64fc50de80/plugins/SegmentEditor/SegmentEditor.php#L266) 

This is intentional behavior added as part of #12823, but it's potentially confusing as experienced users wouldn't expect a new segment to be 'ready' immediately and seems a bit inconsistent that the segment will sometimes show as unprocessed depending on the selected period.

Possible changes:
1. Disable the check and always show the unprocessed message until the segment has been processed even if there will be no data for that time period.
2. Show a discreet info message: "Hey this segment is new and probably hasn't been processed for all periods yet, but there is no segment data for this particular time period anyway, so we're showing you a blank report"
3. Leave it as is and add some explanatory documentation somewhere (probably not very helpful as it would be hard to find in a search)
4. Better ideas?

@mattab Do you have any preferences on how to proceed with this?

**Comment by mattab** [comment]
I'd go with 1) to make things consistent & simple, maybe?

**Comment by mattab** [comment]
Closing due to complications to implement and not being worth it yet
