### ISSUE TITLE
log_visit error: idvisit entries have 0 total_visit_time and the same visit_first_action_time

### ISSUE THREAD

**Issue by asmaa-TRULUV** [piwik/piwik#20116]
I am reaching out today because our team noticed an oddity in the Matomo log_visit dataset for our project. There seem to be many idvisit entries that have 0 total_visit_time and the same visit_first_action_time (see attached screenshot).

There is a reference to a similar problem on the [Matomo forums](https://forum.matomo.org/t/0-second-visits/14101) from a few years ago, but we're not sure why Matomo would be creating multiple entries for a visit that started at the same time. 

How would you suggest we address this issue with Matomo?
![screenshot](https://user-images.githubusercontent.com/119529094/208170980-a08df76d-3284-4697-bef7-748ff5135e1f.png)

Thank you!

**Comment by sgiehl** [comment]
@asmaa-TRULUV This can have various reasons. It would be a bit out of scope to determine this here on github, as we try to focus on fixing bugs and implementing new features. Maybe try to get some first help on our forum. Or if you are a paying customer you can also get in touch with our support.
If you are able to find the reason and it turns out to be a bug, I'm happy to assist here in fixing it.

Just a few thoughts that might cause creating new visits:
* different referrers or different campaign parameters in the URL (might depend on the config)
* different config id (might currently happen when using consent manager & disabled feature detection)
* setting a user id after something was tracked
