### ISSUE TITLE
cannot install without wordpress

### ISSUE THREAD

**Issue by AVRajanaav** [piwik/piwik#20187]
Hello

I just downloaded the zip file from the web site and extracted and accessed index.html

and I get the error:

Fatal error : Declaration of Piwik\Plugins\Monolog\Handler\WebNotificationHandler::write(array $record) must be compatible with Monolog\Handler\AbstractProcessingHandler::write(array $record): void in /</matomo/plugins/Monolog/Handler/WebNotificationHandler.php on line 34

I see a user had posted → https://forum.matomo.org/t/php-fatal-error-monolog-handler-webnotificationhandler-php-on-line-34/44551

**But I don’t have wordpress installed** and don’t want to install it!

PHP V7.4

What’s wrong please?

Thanks

Rajan

**Comment by sgiehl** [comment]
Hi @AVRajanaav 
Did you use the latest version available on https://builds.matomo.org/ ?
Installing that one should not require anything else. For wordpress there is a special release or a plugin to use (which the forum entry refers to).
If that doesn't work maybe you have some PHP settings in place, that are causing the problem. Like a global auto include or similar.
As this is most likely a server configuration issue please try to find some help on our forum first. If this turns out to be a bug in Matomo itself, we are happy to handle that here again for sure.

**Comment by AVRajanaav** [comment]
I figured it out.

It was on a shared host who had their own scripts to install Matomo. I used them

Then manually updated files on the server

All is well
