### ISSUE TITLE
Error in PiwikTracker.php after Upgrade of PHP to 8.0

### ISSUE THREAD

**Issue by ReinerKissel** [piwik/piwik#20212]
Migration PHP to 8.0 creates an error in Matomo script PiwikTracker.php :
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /mnt/web206/c1/71/552871/htdocs/_efg-neuhofen_de_test/wp-content/plugins/matomo-tracker/inc/frontend/PiwikTracker.php on line 519 

The error can be fixed by replacing the "{" and "}" with "[" and "]".

**Comment by Findus23** [comment]
Hi,

I think that code is part of this Wordpress plugin:
https://wordpress.org/plugins/matomo-tracker/

Which is not maintained by the Matomo-Team and not maintained at all for many years.

**Comment by bx80** [comment]
Hi @ReinerKissel, thanks for reaching out. As @Findus23 noticed, this error is in an old third-party plugin that is no longer maintained so this issue is unlikely to ever be fixed. I'd recommend checking out the official Matomo WordPress plugin  https://wordpress.org/plugins/matomo/ which supports all the latest features and is regularly updated.
