### ISSUE TITLE
Cannot enter password when attempting to Add a new user. Input field has the property "disabled"

### ISSUE THREAD

**Issue by varunKothare** [piwik/piwik#20228]
A user  was trying to invite a new user and when they clicked on the "Invite User" button, they was asked to enter my password. However, when they tried to enter my password into the field, it was disabled and I couldn't type anything in. After examining the source code, I discovered that the <input> field for the password had the "disabled" attribute.

[Administration > System > User > "Add a new User"]

![image](https://user-images.githubusercontent.com/100554311/213062476-8501e341-f561-4612-a2c1-e378794ec1fc.png)

![image](https://user-images.githubusercontent.com/100554311/213062504-27d4228e-ebb4-498b-815a-e9a794235c72.png)

![image](https://user-images.githubusercontent.com/100554311/213062513-29a1bdd5-f798-4b7c-b09c-3b2ad09885c5.png)

System Check Attached
[matomo_system_check.txt](https://github.com/matomo-org/matomo/files/10441157/matomo_system_check.txt)

**Comment by AltamashShaikh** [comment]
@varunKothare they are using the latest the version of `LoginSaml` plugin i.e 4.3.0 and since 4.3.0 password confirmation is disabled by default.
Refer this [doc](https://matomo.org/faq/general/set-up-login-with-saml-authentication/#security-considerations) 
They can change this if they want by changing the config option from UI

![Screenshot from 2023-01-18 07-40-28](https://user-images.githubusercontent.com/14902277/213064562-03cf8899-0c8f-4785-ac63-981a701c4d8e.png)

**Comment by AltamashShaikh** [comment]
To proceed ahead, they can click the "ok" button and it will work, we have a issue to change the text of confirmation modal in such cases to make it more clear, Refer #20186
