### ISSUE TITLE
pagename is missing

### ISSUE THREAD

**Issue by matomoto** [piwik/piwik#20242]
Matomo Version: 4.13.1
Matomo Update History: 4.11.0,4.10.1,4.9.1,4.7.0,4.6.2,4.6.1
Matomo Install Version: Unknown - pre 3.8.
Latest Available Version: 4.13.1

JavaScript Tracking
Tracking code in the HTML head

How is it possible, that the pagename is missing? It is not the only one. I know the pagename and by other visits of this page there is correct with a darkgrey folder symbol and the pagename.
Screenshot from the "Visits Log" page:
![matomo-without-pagename-1](https://user-images.githubusercontent.com/35422079/213309608-89ae7915-fdb9-484e-a031-baef77757cd4.png)
Same in the "Real-time" page and the "Visitor profile" page.

**Comment by sgiehl** [comment]
Hi @matomoto 
It can have a plenty of reasons why the page view tracking might not work correctly. In seems in this case only the outlink tracking was triggered. This might be caused by a problem with the tracking or e.g. an adblocker, that only blocks certain type of requests.
Maybe try to find some help on our forums first for this kind of issues. We don't have the capacity to investigate and narrow down such "unspecific" problems here on GitHub. If you are able to find a specific bug (together with our forum team), feel free to create a detailed bug report again, so we are able to fix it.

**Comment by matomoto** [comment]
> This might be caused by a problem with the tracking or e.g. an adblocker, that only blocks certain type of requests.

When this is the cause, you can make a fallback to fill the pagename?

**Comment by sgiehl** [comment]
If there isn't any tracking request for a page view, we can't fill in anything. As mentioned above, try to get some help on the forum in order to find out the reason why the page view is not tracked correctly.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/erfahrungsbericht-matomo-tracking-rauschen/46151/32

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/difference-between-pages-and-page-titles/22939/4

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/setdocumenttitel-beim-nachladen/51941/2
