### ISSUE TITLE
Global View of all 'Hits'

### ISSUE THREAD

**Issue by goochj03** [piwik/piwik#20295]
**Customers Response**: "What I want is a global view of all the sites. Would it be possible to add the column "hits/actions" in the page "all websites"?"

Is it possible to display a column for 'Hits' in the **All Websites** section of the Matomo UI, so customers can easily see the total number of hits per site based on the selected date picker.

**Comment by bx80** [comment]
Thanks for the suggestion @goochj03, I'll assign it for consideration by the product team :+1:

**Comment by mattab** [comment]
Thank you for the report! 
Duplicates https://github.com/matomo-org/matomo/issues/18978

**Comment by atom-box** [comment]
Currently we tell customers to find "hits" in either Custom Reports or in their Cloud Billing. 
Because a majority of Matomo users have neither of these things, it would be nice to have a way to see hits; this would be a good feature to add.

**Comment by Team-Startup** [comment]
Hi there. It's a good idea to add the hits in the global view. Matomo bills us based on hits, and we bill our customers based on the hits they consume. So this is data we use very often and to have it for all sites at once would be really nice.
I vote for it ;)

**Comment by Stan-vw** [comment]
Reopening this since seeing the number of hits per website on the All Websites page is slightly different than having a global view of all your hits.
With the All Websites view they can see which websites are using the most hits, but since the All Websites view doesn't have totals it would still be up to the user to add all the numbers up before knowing their billing implications. This ticket would make it easier to check regarding billing, whereas All Websites would make it easier to compare cost per website.
