### ISSUE TITLE
Sort all menu lists alphabetically

### ISSUE THREAD

**Issue by AltamashShaikh** [piwik/piwik#20340]
Problem: Lists and Dropdowns that are in random order instead of alphabetical.

## Summary
Solution:
- Find all lists and dropdowns in menu which is not sorted alphabetically
- Sort them all alphabetically (keep "Overview" on top of lists)
- Notify Stan or Matt in case you find a list/dropdown where you believe alphabetical sorting does not make sense. There might be exceptions where something else should be on the top.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

**Comment by sgiehl** [comment]
This issue actually more likely feels like a placeholder that will never be actively worked on. We don't have time to click and look through all the application to check if certain lists are correctly sorted.
@AltamashShaikh If you have specific lists that should be sorted, please add them to the issue description or consider creating new issues for each list, as that makes it a lot easier to work on it.

**Comment by AltamashShaikh** [comment]
@sgiehl PO will collate and update the ticket

**Comment by Stan-vw** [comment]
In absence of a full audit of menus, can we scope this ticket to sort the menus on the left of the Dashboard and Settings screens, as well as the dropdowns that are part of those? 
I've attached screenshots of them (note that I might not have screenshotted every section in the Settings menu due to restricted access).

![Screen Shot 2023-02-10 at 4 21 20 PM](https://user-images.githubusercontent.com/52564377/217992855-b561d870-5e5d-456c-adac-386e7479469d.png)
![Screen Shot 2023-02-10 at 4 21 07 PM](https://user-images.githubusercontent.com/52564377/217992857-98489190-f76a-49c8-ae02-fb556bfde6c1.png)
![Screen Shot 2023-02-10 at 4 20 59 PM](https://user-images.githubusercontent.com/52564377/217992858-c07ac55e-2131-4e60-9917-2ec98167232d.png)
![Screen Shot 2023-02-10 at 4 23 56 PM](https://user-images.githubusercontent.com/52564377/217992860-7c12f6ce-e19d-4e9f-80d9-32a784b87f24.png)
![Screen Shot 2023-02-10 at 4 20 52 PM](https://user-images.githubusercontent.com/52564377/217992861-aea439f6-321b-4f7a-94b8-cae1b2dbf35e.png)
![Screen Shot 2023-02-10 at 4 23 05 PM](https://user-images.githubusercontent.com/52564377/217992865-715ed503-7040-451c-9224-65f3cd71538c.png)
![Screen Shot 2023-02-10 at 4 20 31 PM](https://user-images.githubusercontent.com/52564377/217992867-f1028685-94dc-4090-adbc-857149c7362c.png)
![Screen Shot 2023-02-10 at 4 22 33 PM](https://user-images.githubusercontent.com/52564377/217992868-89236b41-0402-44fd-9383-55678461e478.png)
![Screen Shot 2023-02-10 at 4 22 26 PM](https://user-images.githubusercontent.com/52564377/217992869-1dd20f31-cf49-41e0-a04c-41f2cf4e5bd1.png)
![Screen Shot 2023-02-10 at 4 22 21 PM](https://user-images.githubusercontent.com/52564377/217992871-3010d75c-9743-4780-b14a-ea4a01463395.png)

**Comment by Stan-vw** [comment]
As you'll notice, most of them have an "Overview" item (which logically should be on top) and the rest is not in any very clear order (and thus alphabetical would make sense)

**Comment by pbb72** [comment]
Alphabetic ordering *only* makes sense when the labels are predictable, that is when the user beforehand knows what word to look up.

For example, when listing API method names, such as add_payment_method, order_review, etc, it makes sense. But when describing items, such as All Channels, Search Engines & Keywords, Websites it makes no sense as the items could just as well be named Channels, Keywords, Sites and thus end up in a different order.

The main objective is findability, and alphabetization is not always helping there.

**Comment by sgiehl** [comment]
I agree with @pbb72. Also we should not forget about other languages. Imho it would not be helpful to sort the menus based on the final names. It's very helpful to always have the same order of menu entries across languages. Using an alphabetic order in that case, could cause the order to change when an translation is updated or added.

**Comment by Stan-vw** [comment]
Thanks for the feedback, good consideration around translations.
Right now it's based on creation date, which has no merit in most of the menus. I wouldn't argue that alphabetical is perfect, but it sounds more workable than the current sorting order. Do you see a better sorting option?

**Comment by sgiehl** [comment]
For custom created list, like dashboards or custom reports I think it's fine to sort them alphabetically. Everything else should maybe stay static - even though we could consider to change the order if that makes sense.

**Comment by pbb72** [comment]
Ordering by creation date actually makes some sense; this assures that the order of items is never changed, as new items are added at the bottom of the list, making it easier for experienced users.

As an alternative, are there any usage statistics of these menus? You could order them from most-used to least-used.

**Comment by Stan-vw** [comment]
I agree that keeping it the same has some benefit for some experienced users and I'm mindful of it. Then again, we're hearing from both new and existing users that they want a cleaner UX. Menu sorting is just a small item of the wider UX improvements we're looking at, but the benefit of easier menus does add up rapidly across most users. To be fair there likely isn't "a best way of sorting" just a "least bad way for most people".

I'll have to check if there are statistics on this.

**Comment by mattab** [comment]
we'll research further internally, so for now i'm closing the issue in favour of this smaller one: https://github.com/matomo-org/matomo/issues/17950
