### ISSUE TITLE
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL

### ISSUE THREAD

**Issue by zigojacko** [piwik/piwik#20350]
Trying to use the Google Analytics Importer and reported in the gaimportlog.3..log file is this error:

PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /.../core/testMinimumPhpVersion.php on line 128

Running PHP 8.2

**Comment by bx80** [comment]
@zigojacko Thanks for reaching out.

I've tested the function referenced in the error message with PHP 8.2 but was unable to recreate the error.

It seems this error usually occurs when PHP 5.x attempts to run code with type hints. Since it's not uncommon to have a different version of PHP running on the command line than the one used by the web server. Could you confirm that your command line PHP version is 8.2 with `php -v` ?

**Comment by zigojacko** [comment]
@bx80 PHP 5.x does exist on the server and it will be the version on the command line however the site that is running Matomo is running PHP 8.x - because the server uses Plesk, the only way to return the correct PHP version on the command line is by running this command first:

export PATH=/opt/plesk/php/8.1/bin:$PATH;

I've no idea if this is of any relevance.

**Comment by sgiehl** [comment]
@bx80 I think we need to check `testMinimumPhpVersion.php`. That file should be able to run with PHP <7, so it's able to print an error, that the PHP version is too low. Guess we need to remove the type hints there. Might be something we should do for the next patch release. Could you have a quick look?

**Comment by bx80** [comment]
I was able to recreate this by installing PHP5.6 and running `/usr/bin/php5.6 core/testMinimumPhpVersion.php` which returned the error:

`PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/matomo/core/testMinimumPhpVersion.php on line 128`

Removing the type hints resolved the error and allowed the check to instead fail because of an unsupported PHP version:

`
Error in Matomo: To run Matomo you need at least PHP version 7.2.5
Unfortunately it seems your webserver is using PHP version 5.6.40-64+0~20230107.71+debian11~1.gbp673146.
`

I've create a PR with this fix. 

@zigojacko Unfortunately this fix will still not allow you to run the Google Analytics Importer on PHP 5.6. I'm not too familiar with the importer code, but based on the [requirements](https://matomo.org/faq/general/requirements-for-the-google-analytics-import/) it sounds like the it needs to be able to `exec()` / `shell_exec()` a supported command line PHP version (7.2.5+) in order to work.

It looks like a similar issue was resolved [here](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues/174) by setting a path variable on the server. There may also be more useful information in the [Google Analytics Importer repository issue list](https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/issues)

**Comment by zigojacko** [comment]
@bx80 Thanks for this. I'm not actually sure how to move forward with this then because the domain is configured to run PHP8 and this works fine - as can be confirmed in the system check:

![Screenshot_6](https://user-images.githubusercontent.com/849735/218745864-e07beb6e-f058-4990-88c5-5ef8990f4932.jpg)

Different domains running on the same server use different PHP versions (although none require 5.6 specifically) but it means that explicitly setting the PHP path in a global PHP configuration is not a solution.

I'm not sure why this Google Analytics Importer plugin is trying to run things with PHP 5.6 🤷‍♂️

**Comment by sgiehl** [comment]
I guess it will try to find a php version that matches the requirements or falls back to simply using `php` or similar.
If your system has multiple php version installed it might help to configure the php binary to use in `config.ini.php`.
You can set the flag `php_binary_path=path/to/php` under `[General]`. Maybe that helps to solve your issue.

**Comment by zigojacko** [comment]
@sgiehl thanks for the suggestion but after specifying this in the config.ini.php to this:

`/opt/plesk/php/8.1/bin/php`

![Screenshot_10](https://user-images.githubusercontent.com/849735/218767266-b72e0192-d7f2-4683-b387-3cc06b3a2b74.jpg)

Then on the System Check page, the PHP_BINARY path remains the same as it was before.

![Screenshot_9](https://user-images.githubusercontent.com/849735/218767238-26b2479e-594d-4c47-aa85-d63baa6bd737.jpg)

**Comment by sgiehl** [comment]
The one in the system check is the value of the `PHP_BINARY` constant, that is automatically defined by the running php process. So that can't change due to the config value. But the task running to import google analytics data might now use the correct binary. Maybe try to run the import again and check if it works now or if the error message changed...
If not maybe try to find some help on our forum or try creating an issue for the GoogleAnalytics importer plugin here:
https://github.com/matomo-org/plugin-GoogleAnalyticsImporter/
I'm actually not very familiar with the plugin, so I guess they can help you better there...

**Comment by zigojacko** [comment]
@sgiehl ah okay, got it. Unfortunately this did not make a difference and we still get the error as reported in the log after running the import (which by the way does seem to import the data from the account as far as I have checked so far).

Edit: Actually sorry, in this instance, in the backend it showed this message this time:-

Killed: It looks like the import job was terminated. If you didn't do this yourself, then your host probably does not like long-running PHP processes. The import job will start again within the next hour so the import will still continue. If the import speed is still slow overall (check back in a day to see), then view the user guide for more information and workarounds.

-

This may have happened before to be honest if it just resumes again itself. I've no idea what is going on really... 😂

**Comment by sgiehl** [comment]
@zigojacko Ok, so the import seems to run now with the correct PHP version. I'll close this issue then, as it seems solved.
If you have further problem with the GA Importer, please try to get some help on our forums or create an issue in the plugins repo.

**Comment by Stevie0130** [comment]
Hi @sgiehl  I have the same problem with the long-running PHP processes. I have set the max_execution_time to 0 and memory_limit to 512M. However, I still receive the error message. I am currently using PHP version 8.2.13. But I had the same problem with 8.1 and 8.0 as well. What can I do? I just can't get the importer to work. What was your solution? Does anyone have an idea?
