### ISSUE TITLE
PHP 8.1 warning in GridGraph.php   Deprecated - Implicit conversion from float-string "39.15" to int loses precision

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20357]
See below warning we got after trying to upgrade Cloud to PHP 8.1:

> /var/www/html/plugins/ImageGraph/StaticGraph/GridGraph.php(143): Deprecated - Implicit conversion from float-string "39.15" to int loses precision - Matomo 4.13.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) #0/plugins/ImageGraph/StaticGraph/GridGraph.php(143),#1/plugins/ImageGraph/StaticGraph/Evolution.php(24),#2/plugins/ImageGraph/API.php(506),[internal function]: Piwik\Plugins\ImageGraph\API->get(),#4/core/API/Proxy.php(244),#5/core/Context.php(28),#6/core/API/Proxy.php(335),#7/core/API/Request.php(267),#8/core/ReportRenderer.php(277),#9/core/ReportRenderer/Html.php(175)

I don't think I have more information unfortunately.

**Comment by sgiehl** [comment]
@tsteur that one is caused by performing an integer operation on a string that contains a float. I'll prepare a PR to fix that.
I'm pretty sure we will have more and more of such issues with the next PHP versions. PHP is getting more and more type safe, so it only allows to perform certain operations with specific variable types (without triggering warnings). Matomo is handling everything very lax and often doesn't care about types. I'm trying to push everything into a more type safe handling, but it will take a long time to finish that.
