### ISSUE TITLE
Invalid data sent in uadata array, causes complete tracking failure in Queued Tracking

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#20361]
We have a Matomo user who encountered an error a few days ago that caused their Queued Tracking queues to return errors, thereby not being able to process the queue and increase used memory to the point of alerts being sent.

When they investigated further they found that this error was being caused by invalid data being sent in the `uadata` array:
```
 'uadata' =>
array (
0 => '{}","?fa_vid',
1 => '{}"],"send_image":0}',
),
```

There are two issues that likely need to be addressed or investigated with this issue:
1. We need to figure out how the invalid data was passed into the array
2. Prevent such an issue from causing a tracking failure (Potentially by validating the data sent in the `uadata` array before processing it).

I've asked the user if they know what caused the initial invalid data in the array or for a URL that we can use to try and replicate this issue and will update this when I receive more information.

This seems like a similar issue to #20189

**Comment by sgiehl** [comment]
@Starker3 I guess this is actually the same issue as here: https://github.com/matomo-org/plugin-QueuedTracking/issues/194
We has applied some possible fixed around that, so would be good to know which version of Matomo and the plugin they are using.

**Comment by kgogolek** [comment]
I'm the customer who had this issue. Our Matomo version is  4.13.3 and Queued Tracking version was: QueuedTracking (v4.0.2). We should probably upgrade that but the issue was actually with the core component and was introduced by the addition of uadata and the fact that matomo throws an error if uadata is not json, which is easy to abuse on a analytics system with a public endpoint. What helped us is applying patches from this ticket to Tracker/Request.php 
https://github.com/matomo-org/matomo/issues/20189
