### ISSUE TITLE
Doubled QueryString on Login

### ISSUE THREAD

**Issue by tassoman** [piwik/piwik#20378]
I didn't found anything on the forum but there's a bug during login who appends doubled QueryString in the url.

## Expected Behavior
Opening: https://demo.matomo.org/ 
should redirect to: https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday
## Current Behavior
Opening https://demo.matomo.org/
Redirects to: https://demo.matomo.cloud/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1

## Context

I was debugging my custom Login Plugin, wondering about some bug I've added in. But I can see it does itself.  
Happens while loading the dashboard.

## Your Environment

* Matomo Version: 4.x
* PHP Version: 8.1
* Server Operating System: Ubuntu
* Additionally installed plugins: NONE
* Browser: Any
* Operating System: Ubuntu

**Comment by bx80** [comment]
Thanks for drawing attention to this @tassoman, it's not so much a bug as a quirk in the way the URLs are built in Matomo, it won't cause any functionality to break and at the moment is expected behaviour.

There is an [open issue](https://github.com/matomo-org/matomo/issues/7558) to simplify the URLs by removing these duplicated values, I'll link this issue and then close it as a duplicate.
