### ISSUE TITLE
Language is not correctly detected automatically by Matomo

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20374]
Say you have a language header `zh-CN,zh;q=0.9` and call `Common::extractLanguageAndRegionCodeFromBrowserLanguage()` then Matomo will say it is an invalid language code when it should detect `zh-CN`. As a result, the Matomo UI may not be shown in the correct language and on the Cloud they are receiving emails and UI in English when it should be `zh-cn`.

Similar eg for `pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,ru;q=0.6`.

**Comment by bx80** [comment]
Looks like the regex in `Common::extractLanguageAndRegionCodeFromBrowserLanguage()` should be case insensitive, e.g. `(?:^|,)([a-z,A-Z]{2,3})([-][a-z,A-Z]{2})?` instead of  `(?:^|,)([a-z]{2,3})([-][a-z]{2})?` or alternatively we force the `$browserLanguage` variable to lower case before attempting a match.

**Comment by sgiehl** [comment]
@bx80 we are always using lower cased languages for matching. The problem is, that we are using the wrong method for detection. In addition we do not handle special language codes, that include the script, like `zh_Hans_CN` at all.
Will prepare a fix for that.
