### ISSUE TITLE
Migrate from Matomo WordPress to Matomo Cloud

### ISSUE THREAD

**Issue by Birkaransingh94** [piwik/piwik#20383]
Feature request for migrating data from Matomo Wordpress in Matomo Cloud, but without doing the migration Wordpress > On premise > Cloud.

Thanks.

**Comment by bx80** [comment]
Could you provide a bit more information about this @Birkaransingh94? What is the current process? How would you see the new process working?

**Comment by Birkaransingh94** [comment]
Hey @bx80 
The current process is to migrate data from Matomo wordpress to Matomo on-premise. Here:
https://matomo.org/faq/wordpress/how-do-i-migrate-all-my-data-from-matomo-for-wordpress-to-matomo-on-premise/

And then from Matomo on-premise to Matomo cloud. 
https://matomo.org/migrate-to-matomo-cloud/

New process: Directly migrate from Matomo Wordpress to Matomo Cloud.

**Comment by bx80** [comment]
Thanks for the extra info @Birkaransingh94 . 

So currently the migration plugin is used to directly copy the tables from the Matomo for WordPress tables to another database host (on premise). Then a mysqldump is taken of that database and uploaded to Matomo cloud via FTP, finally it's imported to the Matomo cloud database by support staff.

>New process: Directly migrate from Matomo WordPress to Matomo Cloud.

I still need a bit more detail than that to turn this into something actionable :smiley: 

Is this something that you would expect to be done via support staff on the command line? Technically minded users on the command line? Non-technical users via a UI wizard? 

To be able to directly copy the tables from Matomo for WordPress straight into the cloud instance database would require that a database had already been created on cloud and that this database endpoint was exposed for public access. I suspect that wouldn't be a viable option due to the security risks involved and potentially poor or unreliable import performance over the internet.

For hosting with shell access, would it not be already possible to do a mysqldump of just the relevant tables from the WordPress database and then upload that to Matomo cloud via FTP thus avoiding the need for an intermediate database?

Another option which could work for WordPress hosting without shell access would be to have an option for the Migration plugin to generate a database dump and upload it via FTP using user supplied credentials. Is this the sort of outcome you are looking for? If so this issue would probably be better located in the Migration Plugin repository.

**Comment by sgiehl** [comment]
@Birkaransingh94 @bx80 This is not an issue that needs to be handled in core. As you mentioned there is an easy way to migrate from wordpress to Matomo on premise and also from on Premise to cloud.
If that isn't possible from Wordpress to Cloud, I guess that's something the Wordpress team might need to solve or maybe the plugins team need to adjust the migration plugin so it's able to directly create a database dump that can be imported to cloud or similar.
Guess it's better to create an internal issue for that, as it's unrelated to the open source work here in core.
