### ISSUE TITLE
Date Range report invalidation through API returns error

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#20400]
When using the API endpoint to invalidate reports: `CoreAdminHome.invalidateArchived`
And invalidating for a date range: `period=range&dates=2023-01-01,2023-02-24`

The following error is returned:
```
<result>
<error message="The date '2023-01-01' is not a correct date range. It should have the following format: 'lastN', 'previousN', 'YYYY-MM-DD,YYYY-MM-DD'."/>
</result>
```

**Comment by bx80** [comment]
From a quick look at the relevant code it seems that `CoreHomeAdmin/API::getDatesToInvalidateFromString()` is exploding the supplied datestring based on a comma delimiter. This means it's trying to create a range for only the first part of the date range. I've created a PR to fix this.

**Comment by sgiehl** [comment]
@Starker3 while implementing the changes it turned out that ranges are actually already supported by the API method.
But ranges are currently expected to be passed as array. So something like this should already work:
`period=range&dates[]=2023-01-01,2023-02-24`
For Matomo 5 we will add some changes, so it also works when passed as string.
