### ISSUE TITLE
TSV export reports takes long time to process

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#20411]
For some reports, when doing exports to TSV, it takes so long time that it times out, doing the same export to json doesn't time out.
Could this be code related? I see no reason why it should take more time to export to TSV (I would though understand if it was the opposite, if json would time out).

Before digging into this, is this a known issue?

Running:
Matomo version: 4.13.3
PHP version: 8.0.28 

Number of rows in report: 76258
Period to export: month
Flat export.
TSV.

**Comment by bx80** [comment]
Hi @mikkeschiren, that's good question.

Table data is exported using the render classes in `core/DataTable/Renderer/`

Most of the work for rendering json is being done by the `json_encode` function which is built into PHP, implemented in C and is very quick.

The TSV renderer is just a wrapper for the CSV renderer, which needs to iterate over each row and column in the report in order to generate the output. This is implemented in PHP and also includes additional formatting checks for each value.

So it's probably to be expected that TSV will be slower to export than JSON.

There might be changes that could be made to the CSV render to improve performance. Can you give an idea of the difference in performance that you're seeing? How long to export the same report in JSON vs TSV?

**Comment by mikkeschiren** [comment]
Ah, I see, yes then JSON would be quicker. I will collect some data to compare JSON vs TSV.
