### ISSUE TITLE
Check how much  Matomo app performance is improved when using scripts defer loading

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#20460]
Proposed steps:
- Timeboxed to 2h
- Assess whether using the code in https://github.com/matomo-org/matomo/pull/19514 will actually help our performance.
- Let's test the PR and verify the assumption that it improves page load time and makes Matomo app faster in the browser. 
- If the PR doesn't work anymore, report back in the PR with the problems you found. 
- Measure back how much (eg. on Chrome and Firefox + Also measure on a "Slow network") - 

Note:
- it's a requirement for 5.0.0-Beta1 that we investigate this. As it might impact plugins which need to be tested.

**Comment by sgiehl** [comment]
Without having looked or tested this in detail I would assume that it does not really improve the performance that much. We are already loading the assets shrinked into a few files only, so once those files are loaded everything is rendered and Matomo works. Loading the scripts deferred might give the user the feeling that it is a bit faster initially, as some parts might be rendered even though the defered scripts were not yet loaded. But the app won't be functional till all scripts are loaded.
And this actually only affects the very first vie of Matomo. Afterwards all scripts should be cached and would be parsed/rendered immediately.
Or did you see any significant improvements while creating the PR @diosmosis ?

**Comment by diosmosis** [comment]
@sgiehl Loading the largest chunk of JS *synchronously* means the browser waits before even parsing the rest of the page, let alone starting the network requests for the rest of the vue code chunks. This is of course about when the files are not cached, if cached the wait will be momentary.

I did not get to do any testing since at the time, the vue code (with premium plugin changes) was not available on demo2. I was planning on testing with https://web.dev/measure, which tests using a slow network.
