### ISSUE TITLE
Analytic tools do not work

### ISSUE THREAD

**Issue by honghainguyen777** [piwik/piwik#20462]
Hey guys!

First of all, I would like to send you my wishes for health and success. Sorry to post my question here! The forum only allows one media link per post for new members :).

I am a newbie to Matomo. Currently, I'm facing a problem in that all the analytic tools that we have for our Matomo pages do not work. For example, the Visits Over Time and the Visits Overview sections are empty (see images below). Even though, the Visits in real-time and tracked Actions are there.
![image](https://user-images.githubusercontent.com/59792233/225015124-641bc8cf-b705-4431-9bc8-84413257f704.png)
![image](https://user-images.githubusercontent.com/59792233/225015207-5895252f-76bf-4d42-810d-246548f7dec4.png)

It happened when my colleague enabled the "Heatmap & Session Recording", "Users Flow", "Cohort" and "A/B Testing" Plugins. They are on a long vacation now but we really want to have the data to be displayed correctly.

On the administration page, we have a warning: `The PHP version 7.3 you are using has reached its End of Life (EOL). You are strongly urged to upgrade to a current version, as using this version may expose you to security vulnerabilities and bugs that have been fixed in more recent versions of PHP.` -> To be honest, I don't know how to upgrade it yet.

Besides that, on the Diagnostic/System Check tab, we see that we have some "critical issues".
![image](https://user-images.githubusercontent.com/59792233/225015294-9cf0b259-f83a-4ca9-b611-853e5c489b47.png)

The errors reported on the page are
![image](https://user-images.githubusercontent.com/59792233/225015360-cce15b33-2f57-439e-8642-e4dc6d2bab31.png)
![image](https://user-images.githubusercontent.com/59792233/225015433-e618b636-09bb-4f77-bd2f-ba6a0a4efd0a.png)

Again, I am an absolute newbie here and I would love to be helped with solutions using the administration pages. If it is not possible, I will try to learn how to connect to Matomo and use the command line (Windows).

My Environment:
* Matomo Version: 4.13.3
* PHP Version: 7.3
* Additionally installed plugins: "Heatmap & Session Recording", "Users Flow", "Cohort" and "A/B Testing"
* Browser: Chrome
* Operating System: Windows 10 - 64 bit

Thank you so much!

Best wishes,
Hai

**Comment by bx80** [comment]
Hi @honghainguyen777,

It looks like the scheduled archiving process is not running on your Matomo install, which is why non-real time data is not being shown. This [guide](https://matomo.org/faq/on-premise/how-to-set-up-auto-archiving-of-your-reports/) explains how to set up the scheduled archiving process, which unfortunately does require configuration via the command line.

If your site doesn't have a lot of traffic then an alternative might be to use the 'Archive reports when viewed from the browser' setting available under Administration > System > General Settings.

Hope that helps!
