### ISSUE TITLE
Error fetching data from API in Looker Studio, SyntaxError

### ISSUE THREAD

**Issue by jwhWHU** [piwik/piwik#20506]
## Context
Currently unable to import data in Looker Studio due to the following error:
"Error fetching data from API. Exception details: SyntaxError: Unterminated string in JSON at position 52377581"

Already increased memory capacity configured for the PHP-processes, as that was originally the error message. 

## Expected Behavior
We should be able to display our data in Looker Studio via the connector we are utilizing. 

## Current Behavior
Error message

## Your Environment
* Matomo Version: 4.14.1
* PHP Version: 7.4.33
* Server Operating System: Debian 11
* Browser: Chrome
* Operating System: Windows 10

**Comment by sgiehl** [comment]
@jwhWHU I'm not very familiar with Looker Studio, but which API are you trying to import? And did you try to fetch the API response manually? It's hard to see if the problem is, that Matomo returns something invalid or if e.g. Looker Studio can't parse the content as it's too long. Maybe using XML instead of JSON could work?

@diosmosis could you maybe give a hint here? I guess you worked with Looker Studio lately.

**Comment by diosmosis** [comment]
Hi @jwhWHU there's a 50 MB limit in Google Apps Script for the amount of data that can be requested via HTTP request and it looks like the connector you're using is hitting that limit, you may want to bring it up with the author or find a way to request less data (eg using the `filter_limit` parameter). Also do note that there is currently no officially supported Looker Studio connector for Matomo, but we are currently working on one.

**Comment by jwhWHU** [comment]
@diosmosis clarified it with the connector and that was indeed the issue. Thank you for the suggestion.
