### ISSUE TITLE
Clicking "no" in users manager when changing permission doesn't reset the role setting

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20531]
## Context
When selecting "no" when editing a user role in Matomo admin it doesn't change back the role setting.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/273120/228703130-4270f4a3-63d0-4f49-b0b5-c642b0b63ce5.png">

## Steps to Reproduce (for Bugs)
* Go to users manager
* Click on Edit a user
* Change the role, eg from No access to Write
* Click on "No"
--> It will keep the newly selected role . It looks like the role was changed despite clicking on "No" (or maybe it actually even did change it)

## Expected Behavior

--> It should switch back to the previously role that the user actually has.

**Comment by sgiehl** [comment]
It doesn't set the role, but it indeed doesn't reset the select when clicking 'no'. To me this looks like a regression from the vue migration.

**Comment by sgiehl** [comment]
@diosmosis It looks like the code actually does try to reset the value, but the select box isn't updated correctly. Do you maybe have a quick idea how to fix this?

**Comment by diosmosis** [comment]
@sgiehl this is the vue issue where if we don't modify the model value, it still keeps the changed value in the input, because vue won't detect the lack of a change. It was worked around w/ this: https://github.com/matomo-org/matomo/blob/5.x-dev/plugins/CorePluginsAdmin/vue/src/FormField/FieldText.vue#L76-L87 (using an "abortable" modifier, and then doing `event.abort()` in the case we don't actually want to change anything). There's an example of it's use in ManageFunnel.vue.

I can fix this if desired, but it will be a couple days before I am able.

**Comment by sgiehl** [comment]
@diosmosis Thanks for the hint. I did remember that there was a similar problem, but couldn't remember how we solved it. Will try to propose a fix myself.
