### ISSUE TITLE
Swedish-Spanish mixup in the settings

### ISSUE THREAD

**Issue by marcusosterberg** [piwik/piwik#20546]
## Context
The last block in the personal settings (with Swedish settings) have a header in Swedish:
> Exkludera spårning av dina besök

Followed by text *in Spanish*, I guess:
> Sus visitas no son ignoradas por Matomo (la cookie de ignorar a Matomo no fue encontrada en su navegador).

Followed by a link text in Swedish:
> Klicka här för att sätta kakan som exkluderar dina besök spårade av Matomo för webbplatsen

## Expected Behavior
A consistent language. The language codes might have been mixed up? "se" and "es"?

## Your Environment
* Matomo Version: 4.14.1
* PHP Version: 8.2.4
* Browser: Most recent Brave
* Operating System: Most recent Macos

**Comment by Findus23** [comment]
That doesn't seem to be a bug in Matomo, but the actual translation string is incorrect:
https://hosted.weblate.org/translate/matomo/plugin-usersmanager/sv/?checksum=5176e78d41470240&q=Sus+visitas+no+son+ignoradas+por+Matomo&sort_by=-priority%2Cposition#nearby

And apparently it has been since 2016:

https://github.com/matomo-org/matomo/pull/9640/files#diff-ed90e132174585bfcbe00e1b79a8e8b10909b943ed23776811db2c9d14c87146R69

**Comment by marcusosterberg** [comment]
@Findus23 one of these days I'm actually going to have the time to proofread all Swedish translation files. There are some less obvious deficiencies than a completely different language.

**Comment by Findus23** [comment]
In case you want a quick scan, you could take a look at all Swedish translations where Weblate's checks find an issue:
https://hosted.weblate.org/checks/?lang=sv&project=matomo

**Comment by marcusosterberg** [comment]
I'm on it, looking through the user interface.

**Comment by sgiehl** [comment]
This will be fixed with #20541. But as we already switched to working on our next major release, the changes will only be included in Matomo 5.
