### ISSUE TITLE
Upgrade 3.x -> 4.14.1 fails in upgradephp/upgrade.php

### ISSUE THREAD

**Issue by andreaswolf** [piwik/piwik#20605]
## Context

I'm running Matomo 3.x in a dockerized environment, and am trying to upgrade to 4.14. The installation is basically empty, I started from a fresh database.

## Expected Behavior

Upgrade should run smoothly

## Current Behavior

I get an empty page in the browser and `./console core:update` silently fails.

After manually setting `display_errors` to `On`, I get this error:

```Fatal error: Array and string offset access syntax with curly braces is no longer supported in /var/www/html/libs/upgradephp/upgrade.php on line 194```

## Possible Solution

Upgrade the upgradephp library to work with PHP 8.1, or use PHP 7.4 for the Docker image if Matomo is not compatible with PHP 8 in general.

## Steps to Reproduce (for Bugs)

(I did not test it with exactly these steps, but that is basically what our project env does)

1. Start a docker-compose environment with a container with matomo:3.14.1-apache as the image
2. Setup Matomo to a state where it accepts tracking for one site
3. Change the image to matomo:4.14.1-apache
4. Do `docker-compose up -d` 
5. Try accessing the Matomo web UI, or run `docker-compose exec -u www-data <container name> /var/www/html/console core:update`

## Your Environment

* Matomo Version: 4.14.1 (official Docker container 4.14-apache, image ID 7dfa45a29098)
* PHP Version: 8.1.18
* Server Operating System: Ubuntu 22.04 running Docker 23.0.3
* Additionally installed plugins: –

**Comment by bx80** [comment]
Hi @andreaswolf,

Thanks for reporting this. The upgradephp library was [updated](https://github.com/matomo-org/matomo/pull/15204) to fix this in November 2019 and the change was released in [Matomo 3.13.1](https://matomo.org/changelog/matomo-3-13-1/)

I checked the `matomo:3.14.1-apache` docker image with `docker exec -ti matomo-3.14.1-container sed '194!d' /var/www/html/libs/upgradephp/upgrade.php` and it shows the fix is present. So it would seem that the fatal error was thrown by an older version of Matomo.

Could you check if your 3.x docker image is older than 3.14.1? 

If you are starting with a fresh database then it might be easier to use a new `matomo:4.14.1-apache` image rather then trying to upgrade.

The [Matomo docker repository](https://github.com/matomo-org/docker) may have more information of docker specific issues.

**Comment by andreaswolf** [comment]
Ah, thanks for checking.

Upon further inspection, I realized that the Docker image does not contain the Matomo sources in `/var/www/html`, but copies them in the entrypoint script. Apparently, that did not happen here.
After removing the matomo.php file with `docker-compose exec -u www-data statistics rm /var/www/html/matomo.php` and restarting the container, the sources were copied.

I'll add a hint to our local docs that we must remove matomo.php when upgrading the image, so the sources are copied. Not sure if this could be automated somehow, e.g. by performing a version check in the entrypoint script (instead of the `[[ -e matomo.php ]]`?

**Comment by sgiehl** [comment]
@andreaswolf In this case maybe create a new issue in the docker container repo, as this is unrelated to Matomo itself though. I'll close the issue.
