### ISSUE TITLE
Please update Matomo 5.0.0-b1 to a newer version

### ISSUE THREAD

**Issue by prk2331** [piwik/piwik#20623]
Hi Team, 

Can you please guide
I am getting this error. I downloaded the matomo from this git repository (5.x) version because I just wanted to enable the development mode, and this would install and work successfully, but when I tried to import this plugin from matomo UI,
    https://github.com/EmreDurdu/MatomoKafka

     This gives me this error:
                  **Please update Matomo 5.0.0-b1 to a newer version, Matomo >=4.3.1-stable,<5.0.0-b1 is required.**

     I recently cloned this repository with a default branch of 5th version, then why this is showing me **Please update Matomo** 
      Matomo 5 >=4.3.1-stable      why this is not considering ?
      
 Thanks

**Comment by prk2331** [comment]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/95373944/233987144-84fa6da2-4c79-4482-b57c-20f9fe0a9323.png">

**Comment by michalkleiner** [comment]
Hi @prk2331,

thank you for posting to Matomo's issue tracker.

The error message you're seeing is actually coming from the plugin you're trying to install since it doesn't have a 5.x compatible version yet. Matomo 5.0 hasn't been released yet, so that's ok. The latest stable version at the moment is 4.14.2 which the plugin supports.

I can see how the message might be a bit misleading since the version of Matomo core is actually newer than the version the plugin requires, however it still doesn't meet the plugin's requirements.

You don't need to install Matomo from git to be able to enable the development mode, you can do that by installing the stable 4.14.2 version and then following the [steps to enable development mode as outlined in this guide](https://developer.matomo.org/guides/getting-started-part-1#enable-development-mode).

If you want to install from git, you can use the 4.x branch instead.

If that still doesn't work for you, I would recommend asking a question/seeking help through the [Matomo forum](https://forum.matomo.org/).
