### ISSUE TITLE
Warning: Undefined array key "method" in PrivacyManager.php

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#20651]
Below warning happened 26 times in the last 3 hours alone:

/var/www/html/plugins/PrivacyManager/PrivacyManager.php(202): Warning - Undefined array key "method" - Matomo 4.14.3-b1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) #0/plugins/PrivacyManager/PrivacyManager.php(202),[internal function]: Piwik\Plugins\PrivacyManager\PrivacyManager->shouldDisablePostProcessing(),#2/core/EventDispatcher.php(147),#3/core/Piwik.php(871),#4/core/API/Request.php(696),#5/core/API/Request.php(227),#6/plugins/API/Controller.php(45),[internal function]: Piwik\Plugins\API\Controller->index(),#8/core/FrontController.php(637),#9/core/FrontController.php(169)

I don't have more information on this.

**Comment by michalkleiner** [comment]
Hi @tsteur,

thank you for reporting this. Looking at the code, I can see how the warning can happen, though I think it's mostly through an incorrect or malformed (intentionally or by accident) request since it relates to the PrivacyManager.

I will shortly push a small PR making sure the warnings are not issued for incorrect requests.

**Comment by michalkleiner** [comment]
PR open at https://github.com/matomo-org/matomo/pull/20653
