### ISSUE TITLE
High availability question on sessionId ?

### ISSUE THREAD

**Issue by prk2331** [piwik/piwik#20668]
Team,
I raised a question on SessionId, but Philippe told me that this feature is not available.

https://forum.matomo.org/t/where-is-the-visitor-id-and-session-id-in-query-params-when-event-goes-to-matomo-php/50930/4

Then, you are maintaining the session on the backend side only when any event goes to the Matomo collector.
After sending every event from the front-end, I saw in the Chrome network console that VisitId or sessionId is not passing to the backend, that this event is for this sessionId only, and if inactivity completes for 30 minutes, then a new session ID would be passed to the backend.
Frontend is not aware that this event for this session ID only ?

Thanks

**Comment by sgiehl** [comment]
@prk2331 That depends. If you allow the javascript tracker to use cookies it will create some sort of visitor id, which will be stored in the cookie. This will be sent with the tracking requests. If a visit can be found using this id, actions/events will be attached to it. Otherwise it will fall back to find the visit by calculating a config hash based on some visitor details like browser, browser plugins, screen resolution,...
In case you want to ensure that visitors are matched correctly you can consider using the userid feature, if you are able to identify the visitors.
