### ISSUE TITLE
A user with a view access can write an annotation

### ISSUE THREAD

**Issue by Chardonneaur** [piwik/piwik#20716]
Hi team,
someone with a view access can write an annotation.
I think it could either make sense to remove this possibility or to add within https://developer.matomo.org/guides/permissions that someone with a view access can write... annotations.

**Comment by bx80** [comment]
Hi @Chardonneaur,

Looking at the [relevant code](https://github.com/matomo-org/matomo/blob/6a4d9268c799d3c75fc737be271e4fa8cf1b6709/plugins/Annotations/AnnotationList.php#L443) it looks like this behaviour might be intentional, but maybe this should be re-evaluated?

I'll pass this on to the product team to decide if annotations should be able to be created by users without write access :+1:
