### ISSUE TITLE
SitesManager.updateSite in OpenAPI

### ISSUE THREAD

**Issue by 786659214** [piwik/piwik#20793]
![9c7d3dd8711d2f94160c12634150c8e89237ccaff86806c2fdbbd5f8ebc3d327QzpcVXNlcnNcNzg2NjVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQyODA1NjM3M192MlxJbWFnZUZpbGVzXDE2ODUwOTA4OTM3NjhfQUVDMkFERTAtNUFERC00ZDRmLTk0OTktQzc2Nzc3REE3RjBELnBuZw==](https://github.com/matomo-org/matomo/assets/49685173/7e911653-866a-4b30-a912-dc8397d59ffc)
![ea446851b025d7805c4296ad1d34f2d7e938650b32acafacac6dfbcc2e17d805QzpcVXNlcnNcNzg2NjVcQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDQyODA1NjM3M192MlxJbWFnZUZpbGVzXDE2ODUwOTA5NTExNTRfRkRDOTVDNUQtRkIzRi00MTQzLUE0QzAtMkJEM0M5RTZDNzhGLnBuZw==](https://github.com/matomo-org/matomo/assets/49685173/8a76fa91-31d4-497a-b318-6bbd6f0e0517)
在使用Open API的过程中，SitesManager.updateSite无法修改main_url，麻烦排查一下问题，谢谢

**Comment by michalkleiner** [comment]
Hi @786659214, can you please describe what the problem is in English?

**Comment by 786659214** [comment]
@michalkleiner When I was using Matomo's open API and using SitesManager.updateSite to call and modify the website interface, I found that the main_ When modifying my website link with the URL, I found that I couldn't update matomo_ The main of the site table_ The URL field, but if siteName is modified, the name field can be modified normally.If there are any issues with the English expression of this paragraph, please directly copy it to Baidu Translator for viewing

**Comment by 786659214** [comment]
When I was using Matomo's open API and using SitesManager.updateSite to call and modify the website interface, I found that the main_ When modifying my website link with the URL, I found that I couldn't update matomo_ The main of the site table_ The URL field, but if siteName is modified, the name field can be modified normally.If there are any issues with the English expression of this paragraph, please directly copy it to Baidu Translator for viewing
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michal ***@***.***&gt;; 
发送时间: 2023年5月26日(星期五) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [matomo-org/matomo] SitesManager.updateSite in OpenAPI (Issue #20793)






***@***.***，可以请你用英文描述一下是什么问题吗？

—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.

**Comment by 786659214** [comment]
@michalkleiner hello，May I ask when this problem can be fixed。

**Comment by michalkleiner** [comment]
Hi @786659214, the reported behaviour is not a bug.

The API doesn't accept `main_url` as a field to be updated. Instead, the SitesManager accepts a list of urls in a field labeled `urls` where the first URL in the list is the main URL for the site and the others are added as aliases.

In your installation, you can check the API reference for all plugins, a screenshot of the `SitesManager.updateSite` is below with the list of accepted fields. 

![SitesManager updateSite](https://github.com/matomo-org/matomo/assets/233342/31effc0e-5498-42cf-baa3-2fa0a9d7dba9)

Give that a go. It's possible you may need to URL encode the domains as well, so that `https://example.com` would become `https%3A%2F%2Fexample.com`.

**Comment by 786659214** [comment]
@michalkleiner Thank you very much
