### ISSUE TITLE
The problem that the region cannot be displayed ！

### ISSUE THREAD

**Issue by yidisha** [piwik/piwik#20854]
Why can't the relevant information of the region be displayed, and the boundary of the region is not displayed at the same time, but the city information can be displayed, how to solve it?
![1](https://github.com/matomo-org/matomo/assets/117683648/d46eda11-321b-43fd-9bc5-23bbff5acdcc)

**Comment by sgiehl** [comment]
Our map is actually quite outdated, so some data might not be correctly displayed. See #11929 
In addition the region / city information depends on the geoip database you are using. In case of a db-ip lite database it's a known problem that some regions are not detected correctly, due to inaccuracy in their databases. Matomo 5 will include some improvements to handle that better.
