### ISSUE TITLE
Getting Database error while on the installation

### ISSUE THREAD

**Issue by AkshayraviC09YC47** [piwik/piwik#20907]
Hello team, im getting this error when i tried to install matomo via docker-composer.yml, any idea why this issue is causing

`Could not connect to the database server: SQLSTATE[HY000] [2002] Connection refused `

<img width="1188" alt="Screenshot 2023-06-18 at 11 16 27 PM" src="https://github.com/matomo-org/matomo/assets/58636452/8161becc-7fbb-4007-87c6-537a630dcb33">

**Comment by michalkleiner** [comment]
Hi @AkshayraviC09YC47,
since we don't provide custom installation support in the issue tracker for the Matomo product here, I suggest you raise the question in the community forum at https://forum.matomo.org/.
Brief look at your docker-compose file suggest you expect the db to be at 127.0.0.1 which won't be correct as it's running in a separate container with a different IP. Remove the env variables from the matomo service, spin up the containers, find out what the IP is from your docker tooling and use that when running the installation. Or for the host env variable, use the word `db` instead of the IP since that should be honoured from inside the matomo container.
Alternatively, check the setup here — https://github.com/libresh/compose-matomo/blob/master/docker-compose.yml
