### ISSUE TITLE
Add Region dimension to custom reports

### ISSUE THREAD

**Issue by paul-buttimore** [piwik/piwik#20949]
Customer has requested that region should be added  as a dimension in custom reports
![image](https://github.com/matomo-org/matomo/assets/107327172/ab238716-15ca-4db0-9f6a-47d6010034bb)

**Comment by michalkleiner** [comment]
Hi @paul-buttimore,
thank you opening the issue. This Github repository is for development issues and improvements relating to the core Matomo application, so for support queries and feature requests on the Custom Reports premium plugin we'd recommend to contact the dedicated support team who will put the suggested enhancement to the product owner for prioritisation. Appreciate your understanding!

**Comment by sgiehl** [comment]
Anyway this kind of dimension can't currently be used for custom reports as it can't be used stand alone. The region dimension contains a two letter region code. But that region code can only refer to a region name together with the country code. Otherwise they wouldn't be "unique". So this might need some sort of virtual dimension which would combine country and region code or similar.

**Comment by michalkleiner** [comment]
Apologies @paul-buttimore, I learn that the dimensions are provided by the core product, so the issue makes sense here. The team will discuss this with the product owner and prioritise accordingly.

**Comment by paul-buttimore** [comment]
had another request from a cloud customer for region dimension in custom reports

**Comment by AltamashShaikh** [comment]
@paul-buttimore We enabled the `region` dimension and should be released in the new version of Custom Reports next week.
Its advisable to use the region dimension with country for accurate results.
