### ISSUE TITLE
Visit count in matomo is not capturing the data when we try with edge,safari,chrome .However it is capturing when we try logging from the firefox. Kindly check and update

### ISSUE THREAD

**Issue by anpaidip** [piwik/piwik#20974]
## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Matomo Version:
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

* Browser:
* Operating System:

**Comment by sgiehl** [comment]
Hi @anpaidip. I'm sorry to hear that you are having trouble with tracking data. Unfortunately it can have many reasons why the tracking might not work for you in certain browsers. Most commonly this is due to ad blockers, a do-not-track configuration or similar stuff. Anyway, this problem is most likely caused by your server or machine setup.
We don't have time to investigate such specific problems here in detail. Maybe try to get some help with investigating your issue by searching and/or asking on our forums.
