### ISSUE TITLE
Warning: Deprecated - Creation of Dynamic Property 

### ISSUE THREAD

**Issue by naivedeveloper95** [piwik/piwik#21112]
![image](https://github.com/matomo-org/matomo/assets/15083393/02a796ec-76ce-48e1-972e-a658cde68933)

How do I resolve this error / warning?

**Comment by michalkleiner** [comment]
Hi @naivedeveloper95. It looks like you are not using Matomo on-premise or Matomo cloud, it seems like you are using Factoreal platform. We're sorry but we are not able to support other vendor products here, please raise the issue with your platform/product provider.

**Comment by naivedeveloper95** [comment]
@michalkleiner No. It is actually Matomo on-premise branded as Factoreal using the white label plugin. This is a customer facing matomo on-premise platform where this warning is coming up for our customers.

**Comment by michalkleiner** [comment]
Thanks for the clarification, @naivedeveloper95.
This issue is a duplicate of #20845 and has been fixed in the 5.x branch and will be available when 5.0.0 is released in a few weeks. Since it is not a security issue, we are not planning on backporting the fix into the 4.x release line. For the time being you can disable deprecation warnings by adjusting your PHP settings.
