### ISSUE TITLE
real-time map not display

### ISSUE THREAD

**Issue by FikaFine12** [piwik/piwik#21138]
## Context

Real-time map in my dashboard not display information (the orange bubble), the map below display "No visits displayed, as no visits for this period has correct (latitude and longitude) geolocation info. Resolve this issue by using a GeoIP geolocation provider with a GeoIP city database. (Though unlikely) IP addresses could still be impossible to geolocate."
I enabled Geolocation in "System->Geolocation" already, and try both Standard and DBIP / GeoIP 2 (php), 
In path of matomo/misc, I have GeoLite2-City.mmdb
In System -> Geolocation -> Setup automatic updates of geolocation databases, at "Location Database" I put url Maxmind like this "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&suffix=tar.gz&license_key=my license key" 
but till now, see nothing change
  
## Environment

* Matomo Version: 4.15.1
* PHP Version: 8.2.8
* Browser: Chrome

## Matomo
![1691572612237](https://github.com/matomo-org/matomo/assets/89577569/c1e605ca-e5aa-4d82-bb82-92eb43feca66)
![1691572851790](https://github.com/matomo-org/matomo/assets/89577569/3077ff20-f873-476e-862c-529e4c6238e2)
![messageImage_1691485763685](https://github.com/matomo-org/matomo/assets/89577569/66f574f3-9938-40a8-92d8-111d3ebe2a71)

**Comment by michalkleiner** [comment]
Hi @FikaFine12, we are sorry to hear that you are having trouble with displaying the geolocation information. Unfortunately there can be more reasons why this might not work for you. Most commonly there's no data for the given location/period. This problem is most likely unique to your particular configuration and set of data. You might be able to get some help with investigating your issue by searching and/or asking on our forums at https://forum.matomo.org/. Please do feel free to reopen the issue if you can provide clear replication steps that something is a bug and not working as expected. Thank you for your understanding.
