### ISSUE TITLE
Can't connect to Matomo (NGINX 499 Error)

### ISSUE THREAD

**Issue by TaraStewardson** [piwik/piwik#21257]
Hi, I am setting up an instance of matomo on a linux server. I am using ansible to deploy Matomo, MariaDB and NGINX. 

I have based my ansible script off of the docker-compose (https://github.com/matomo-org/docker/blob/master/.examples/apache/docker-compose.yml). 

When I try to access Matomo (at https://localhost/), first it shows certificate untrusted page (this is expected), but I cannot click proceed (as in, I can click it but nothing happens).

The Matomo and MariaDB logs look normal. 
The NGINX logs show: 

IP.IP.IP.IP - - [13/Sep/2023:06:23:47 +0000] "GET / HTTP/1.1" **499** 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/IP.IP.IP.IP" "-"

2023/09/13 06:24:47 [error] 27#27: *77 upstream timed out (110: Connection timed out) while connecting to upstream, client: IP.IP.IP.IP, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://IP.IP.IP.IP:9000", host: "ednpas8252"

IP.IP.IP.IP - - [13/Sep/2023:06:24:47 +0000] "GET / HTTP/1.1" **504** 569 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/IP.IP.IP.IP" "-"

I have some config in a config.ini.php file that I am supposed to add after the manual install, if I add the config.ini.php file then https://localhost/ shows a database error for Matomo (expected as well, since database tables creation hasn't occured, but confirms that it is not a connection problem between matomo & nginx).

I have searched the web and cannot find any examples of this - https://github.com/matomo-org/matomo/issues/5869 looks similar but was never answered.

I can provide all my code but am not sure which parts are needed (config.ini.php, global config file, ansible task, nginx config) - let me know which ones would be helpful in identifying the issue.

**Comment by michalkleiner** [comment]
Hi @TaraStewardson, we are sorry to hear that you are having trouble with setting up your Matomo using the docker configuration. Unfortunately there can be more reasons why this might not work for you. Usually this would be either nginx config issue or, if you can't click on a Proceed button in your browser telling you about an invalid certificate, it might be a browser issue as well. As this problem is most likely unique to your particular configuration, we don't have time to investigate such specific problems here in detail. You might be able to get some help with investigating your issue by searching and/or asking on our forums at https://forum.matomo.org/.
