### ISSUE TITLE
Matomo update check times out at times

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#21259]
I tried to upgrade to the latest Matomo 5RC a few times by running the update check and Matomo wouldn't suggest the latest Matomo 5 RC update is available.

I started debugging why that is and noticed we have a 2 second HTTP timeout in https://github.com/matomo-org/matomo/blob/5.0.0-rc2/core/UpdateCheck.php#L71

However, https://api.matomo.org/1.0/getLatestVersion/?piwik_version=5.0.0-rc1&php_version=8.1.14&mysql_version=8.0.26&release_channel=latest_5x_beta&url=http%3A%2F%2Fmyest.com%2F.%2Fconsole&trigger=&timezone=Europe%2FLondon took 4 seconds to execute.

5-10 minutes later the request took less than 2 seconds and only few hundred ms. 

I'm not sure why the request took so long at times and if there has been a regression in performance and/or if it makes sense to increase the timeout so that when people do want to upgrade, it won't falsely say there's no update available

**Comment by bx80** [comment]
There was an automated test for api.matomo.org in core which had a two second timeout and started to fail fairly regularly a few months back, it was put down to github test runner latency and the test timeout was increased to 5 seconds, but perhaps there was an api regression around that time. The test hasn't failed since we increased the timeout, so it might be enough to just increase the update check timeout to 5 seconds, it's not going to make any difference if the check completes quickly and it'd be better to occasionally wait a few more seconds rather than have no update option. :+1:

Cloudwatch stats for api.matomo.org recent avg/max response times might also be worth a look to see if there have been any changes, if we have them.
