### ISSUE TITLE
GDPR tools search with "not" operators for continents doesn't work correctly

### ISSUE THREAD

**Issue by utrautmann** [piwik/piwik#21287]
In the GDPR tools, searching by **_continent_** does not correctly respect the "not" comparison operators.
If I use "not contain" or "is not" a search is apparently made that corresponds to the comparison "contains" or "is"

See the screenshot.
![grafik](https://github.com/matomo-org/matomo/assets/25771066/af3ef7b2-0b2e-4b02-9778-7be34faa5929)

I'm using Matomo 4.15.2 and the Maxmind database.

**Comment by sgiehl** [comment]
Hi @utrautmann 
Thanks for creating this report. The continent actually isn't stored in the database. When using a segment on it we convert the continent code to a list of countries and use those instead. So instead of looking for a continent it will search for all visits in one of the countries. Maybe negating that isn't handled properly. Guess we need to investigate that in detail.

**Comment by michalkleiner** [comment]
@utrautmann can you please help me understand how does 'AMN' relate to US or Canada or North America? Is it some code or should it be a part of a string somehow or something else? Thanks!

**Comment by heurteph-ei** [comment]
Hi @michalkleiner 
I think this is just a test case, as `AM` should return US, Canada, etc. (as it does, because is returns all), but `AMN` should return... Nothing! (but unfortunately does...)

**Comment by michalkleiner** [comment]
@heurteph-ei but in the screenshot the operator is "does not contain" and "AMN" as the value, which I think is a correct behaviour to return US or Canada as neither does contain that string. Which is why I'm asking.

**Comment by sgiehl** [comment]
The segment is for continents, not for countries. `ANM` is short for `North America`. See https://github.com/matomo-org/matomo/blob/4.x-dev/core/Intl/Data/Resources/continents.php#L14-L24
The mapping of countries to continents can be found here: https://github.com/matomo-org/matomo/blob/5.x-dev/core/Intl/Data/Resources/countries.php#L59
And `Canada` and `USA` should be within `North America`

**Comment by michalkleiner** [comment]
Thanks for the explanation @sgiehl!

**Comment by Stan-vw** [comment]
Just did some testing, and thought it's probably a better example to use a continent whose code is part of it's name. The attached screenshot seems reasonably conclusive that indeed "does not contain" is not working:
![Screen Shot 2023-10-24 at 8 44 26 AM](https://github.com/matomo-org/matomo/assets/52564377/2ee6bf52-ffca-4b0c-a01d-2968d1ec45f3)

At the same time, "is not" doesn't seem to work either:
![Screen Shot 2023-10-24 at 8 46 39 AM](https://github.com/matomo-org/matomo/assets/52564377/05a58db6-31e6-4cc2-b7f8-1f7278f9875a)

The `starts with` doesn't work either:
![Screen Shot 2023-10-24 at 8 52 17 AM](https://github.com/matomo-org/matomo/assets/52564377/9bd00144-ab2e-4b99-a502-ce2ec4a5f9dc)
(note that we have data for Asian and African countries, which do show up when we search for "containts afr/asi")


---
On a separate note, I think it's really weird that the user can only use continent codes, rather than the name. For example:
![Screen Shot 2023-10-24 at 8 48 57 AM](https://github.com/matomo-org/matomo/assets/52564377/3ba885b6-4b2b-473c-9f94-5e3ffc3c4848)
@mattab what's the logic behind only allowing continent codes?

**Comment by mattab** [comment]
No particular logic, it's more a bug/missing feature/historical

**Comment by Stan-vw** [comment]
Note that all the issues with the selector aren't limited to GDPR tools, as this feature directly links to the segment creator. Hence, all issues here are very likely/almost certainly also issues with the global segment creation.

Making changes to that needs a lot of testing, to make sure we don't break users' existing segments.
Note: in case someone has "exploited" these bugs to create their segments: they'll likely be affected. That's an accepted impact though, but we should make a note in the breaking changes notes.

**Comment by mneudert** [comment]
The [`Continent`](https://github.com/matomo-org/matomo/blob/2ce56ce7dbb93573a21e41a2ca89920a9262a57c/plugins/UserCountry/Columns/Continent.php#L25) column uses [`UserCountry::getCountriesForContinent`](https://github.com/matomo-org/matomo/blob/2ce56ce7dbb93573a21e41a2ca89920a9262a57c/plugins/UserCountry/UserCountry.php#L77) via an SQL filter to build the segment. The filter does respect the `$matchType`, but the returned value will be used for an [`IN ()`](https://github.com/matomo-org/matomo/blob/2ce56ce7dbb93573a21e41a2ca89920a9262a57c/core/Segment.php#L483) query. Taking the `$matchType` into account when building the filter return should allow support for all match operations.

**Comment by randy-innocraft** [comment]
This issue is a duplicate of [13185](https://github.com/matomo-org/matomo/issues/13185) and the status will be tracked as part of that ticket. Closing this one for now.
