### ISSUE TITLE
All Visits Segment filter not showing options

### ISSUE THREAD

**Issue by Dyber1** [piwik/piwik#21416]
When in the Visitors > Organisation Name tab, I can see a list of the 33 organisation names, with activity against each (i.e visits etc). When I create a segment in the All Visits filter, and filter by Organisation Name, in the dropdown list only 26 results are shown, and when I search for the 7 org names that are not shown there are no results. I have also tried filtering by the org ID and the IP address of the user in that org but there are not results. This means at the moment I cannot create segments for my sales team by their organisations, as not all organisations can be filtered by

**Comment by bx80** [comment]
Hi @Dyber1, thanks for reaching out. 

The Organisation Name you see under the Visitors menu will be provided by a custom dimension, as organisation is not a standard dimension in Matomo.  Is there anything different about the missing 7 organisation names, such as names containing quotes or accented characters? Even if an organisation name is not provided in the segment editor drop down it should still be possible to type the exact value, could you check if this works for you?

**Comment by Dyber1** [comment]
Hey,

No they've not got any accents or special characters in, and don't appear
as you type their names. We've also got organisation ID as well, but the
same thing occurs with that too, which is odd as its just an integer. It's
the same orgs not showing each time, but as mentioned they do appear under
both the visitor reports that show by org name and org ID. In the segment
filter, I type in Organisation Name to find the field, and there's only
one, we've not duplicated the field by accident

**Comment by bx80** [comment]
Hi @Dyber1, 

Only [values used in the last 500 visits](https://github.com/matomo-org/matomo/issues/6438) will be included in the segment editor values dropdown list, so it is possible that the missing seven organization names have not been tracked recently. It should be possible to just type in the exact organisation name to create the segment, the dropdown is only there as a convenience for common values, it's not required to pick an item from the dropdown list in order to proceed with creating the segment.
