### ISSUE TITLE
Custom dimension missing in website view

### ISSUE THREAD

**Issue by powerriegel** [piwik/piwik#21527]
I have created a custom dimension using a RegEx to filter Solr Facets out of the URL. This dimension works for "all websites" and can be found under Actions at the bottom of the list. 

But when I limit to only one website, the report is missing. I cant find a way to activate this report for all single websites. 

Matomo 4.15.1 on PHP 8.2

![Screenshot 2023-11-13 at 11-52-26 Benutzerdefinierte Dimensionen - Administration - Matomo](https://github.com/matomo-org/matomo/assets/11870663/0c44804d-6409-4855-9d8f-a7beeeadfb95)
![Screenshot 2023-11-13 at 11-53-00 BOSS alle Sichten - 2023-11-13 - Webanalytik-Berichte - Matomo](https://github.com/matomo-org/matomo/assets/11870663/dc738613-e2b4-4365-be1d-929bac539e67)
![Screenshot 2023-11-13 at 11-53-31 Ev  Landeskirche Württemberg - 2023-11-13 - Webanalytik-Berichte - Matomo](https://github.com/matomo-org/matomo/assets/11870663/d099e52d-145c-4ed1-b983-7c92a86604cb)

**Comment by powerriegel** [comment]
No further responses, yet? This is really as show-stopper, as I can't use custom dimensions for our customers.

**Comment by sgiehl** [comment]
@powerriegel Sorry, looks like you didn't use one of our issue templates to create this report. Otherwise it would have automatically added a `to triage` label. Therefore your issue slipped through our triage process.

To answer your question: Custom dimensions are actually bound to a specific website. You can configure those in the administration for each website separately (by choosing the website in the selector).
In all reports built across all websites custom dimensions should actually be missing, as they can differ between websites, and therefor can't be aggregated.
You can find more information around custom dimensions here: https://matomo.org/guide/reporting-tools/custom-dimensions/

**Comment by powerriegel** [comment]
Thanks a lot, I didn't notice that the Dropdown applies to the settings, too.
