### ISSUE TITLE
[Bug] What's New popover doesn't stay dismissed

### ISSUE THREAD

**Issue by Starker3** [piwik/piwik#21589]
### What happened?

What's new popover shows up after a few days after clicking "Don't Show Again" with the same data/information as previously shown

### What should happen?

The popover should remain dismissed until there is something new

### How can this be reproduced?

Install Matomo 5.0-rc8, login for the first time after updating and click "Don't Show Again" then check again after a few days for it to pop up again.

### Matomo major version

Matomo 5

### Matomo minor or patch Version

rc8

### PHP version

8.0.30

### Server operating system

Debian

### What browsers are you seeing the problem on?

Firefox

### Computer operating system

Mac OS/Ubuntu

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by Stan-vw** [comment]
just to check, isn't this simply how Matomo deployments work: the What's New entries ship with a version, not on a server-based time. Therefore, everytime we move cloud from Matomo 4 to Matomo 5 everyone will see this again, which is why you've seen it multiple times now (we rolled back and reinstalled Matomo 5 a few weeks later). Correct?

also, unless I missed it, it doesn't sound like we'll move cloud back to Matomo 4 so you shouldn't get it again

**Comment by Starker3** [comment]
@Stan-vw indeed, but this was with an on-premise install of rc8 that was updated a few days ago, the popover appeared immediately after the update and was dismissed with 'Don't show again' but it appeared again today with no changes being made to the Matomo install.

**Comment by Starker3** [comment]
Actually, it seems the notification (Not specifically the popup) seems to not dismiss correctly when clicking "Don't show again". Clicking that and reloading the page the notification badge appears again:
![image](https://github.com/matomo-org/matomo/assets/20905821/a7226be9-7593-4650-9527-defe6e5d3ec0)

**Comment by sgiehl** [comment]
I guess I found the reason why that happens. When the button is clicked a request is sent to dismiss the changes and modal is closed. Due to a bug (https://github.com/matomo-org/matomo/issues/21511) all ongoing requests are canceled when the popover is closed. So depending if the requests to dismiss the changes was already processed or not it might get aborted and the changes remain visible on reload. I'll prepare a fix for that specific problem.
