### ISSUE TITLE
[Bug] No Data screen for SPAs contains hidden space in variables

### ISSUE THREAD

**Issue by 9joshua** [piwik/piwik#21594]
### What happened?

The Tag Manager variables included in the SPA tab of the No Data Screen, such as {{PageTitle}}, contain an invisible space between the first two curly brackets. If this text is copied and pasted into a Tag, the character remains and will break tracking...
![Screenshot from 2023-11-24 20-22-21](https://github.com/matomo-org/matomo/assets/20234985/8e72bdad-3f88-4c09-aded-a68660650ac2)

![Screenshot from 2023-11-24 20-23-08](https://github.com/matomo-org/matomo/assets/20234985/168519b2-c454-4f4d-bafd-ce4829da6f5c)

![image](https://github.com/matomo-org/matomo/assets/20234985/f7677c58-5243-4e57-bae4-eadc54f71d5b)

![Screenshot from 2023-11-24 20-51-49](https://github.com/matomo-org/matomo/assets/20234985/6fdfc90c-3d1a-49cf-9c46-bd3cf6185130)

### What should happen?

Remove the invisible characters so that cutting and pasting the variables works as expected.

### How can this be reproduced?

1. Create a new website
2. Go to the No Data Screen
3. Select the SPA tab
4. Copy and pasted any {{}} variable into an IDE

### Matomo major version

Matomo 5

### Matomo minor or patch Version

5.0.0-rc8

### PHP version

8

### Server operating system

NA

### Computer operating system

NA

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Guess that happens due to our sanitizing of html strings. Double brackets are replaced with an invisible whitespace between here:
https://github.com/matomo-org/matomo/blob/b182f0e716f12511b7f05c94281b766248279d1a/plugins/CoreVue/polyfills/src/index.ts#L47

I would guess the main reason for doing that might have been the possible problems with angular js during the migration. Not sure if we could simply remove that now. Maybe vue.js doesn't have problems there.

@diosmosis Do you think we could simply remove that replacement, or would there still be possible security related problems?

**Comment by diosmosis** [comment]
@sgiehl it shouldn't be necessary, vue doesn't parse HTML and apply templating (unless you take html and put it into a component definition), it just sets the inner HTML property (where we use vueSanitize/$sanitize). We still have the angularjs XSS tests, so you can also verify by removing it, building the polyfills again and running the UI tests.

**Comment by sgiehl** [comment]
@diosmosis Thanks for confirming that 👍
