### ISSUE TITLE
[Bug] cannot run ./console after update to v5.0

### ISSUE THREAD

**Issue by JanMalte** [piwik/piwik#21788]
### What happened?

Upgraded from v4.16 to v5.0 using docker setup
Web GUI is working but the `console` script is exiting without error and exit code `255`

```
Fatal error: Cannot override final method Piwik\Plugin\ConsoleCommand::execute() in /var/www/html/plugins/CoreConsole/Commands/GenerateAngularComponent.php on line 27
```

### What should happen?

The `console` script should output the help message

### How can this be reproduced?

`docker compose exec app php ./console`

### Matomo version

5.0.1

### PHP version

8.2.14

### Server operating system

Docker running on Ubuntu

### What browsers are you seeing the problem on?

Not applicable (e.g. an API call etc.)

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by JanMalte** [comment]
I've found the issue #21775 and deactivated and uninstalled any third-party plugins.

This didn't changed anything.

I do not find any log or error message, so I do not have any idea where to look at.

**Comment by sgiehl** [comment]
@JanMalte It's hard to help without any further details on the exact error. I guess for some reason the error reporting is disabled on your box. Otherwise console would output the error that occurs, or it would be logged somewhere. I guess this might be due to the way your docker machine is set up.

Unfortunately we aren't able to handle setup specific trouble shooting here on GitHub, as we use this issue tracker only for feature requests and bug reports. Please try to find some help on our forums at https://forum.matomo.org
Once you were able to find the detailed error and it's clearly caused by Matomo itself, feel free to create a new report.

**Comment by JanMalte** [comment]
@sgiehl I've updated the issue a few minutes ago and added the releveant error message.

As the error messages states something about `plugins/CoreConsole/Commands/GenerateAngularComponent.php`, I think this might by a matomo bug/issue.

**Comment by JanMalte** [comment]
Thanks for the hint.
I've found the issue in the forum, including a fix:
https://forum.matomo.org/t/update-matomo-4-16-0-5-0-0-error/54668

**Comment by sgiehl** [comment]
In that case, this is actually a duplicate of https://github.com/matomo-org/matomo/issues/21718
