### ISSUE TITLE
Add TikTok as a Social Network channel type

### ISSUE THREAD

**Issue by rcontiuk** [piwik/piwik#21796]
Currently TikTok is shown as "Websites" but it should be included in Social Network channel type.

**Comment by sgiehl** [comment]
This has been added over a year ago in https://github.com/matomo-org/searchengine-and-social-list/pull/83
The list should be updated automatically in Matomo periodically if a connection to the internet is possible.
Otherwise the list will be update with a Matomo update.

To check the list of social networks configured you can also use my plugin: https://plugins.matomo.org/ReferrersManager
