### ISSUE TITLE
Please add TestRunner to plugins.matomo.org to simplify CI-workflow

### ISSUE THREAD

**Issue by mikkeschiren** [piwik/piwik#21898]
## Summary
If you download the  recommended release from https://builds.matomo.org some plugins that are in the git repo are not preseent, it seems that all plugins missing, except TestRunner, could be download via the api. 
To simplify CI workflow where TestRunner could be needed to test the Matomo installation, please distribute TestRunner through the api so it could be downloaded, like:

```
curl -f -sS "https://plugins.matomo.org/api/2.0/plugins/TestRunner/download/latest?matomo=5" > TestRunner.zip
```

**Comment by michalkleiner** [comment]
Hi @mikkeschiren, thanks for opening the issue.

The TestRunner plugin is removed from the build package [here](https://github.com/matomo-org/matomo/blob/5.x-dev/.github/scripts/build-package.sh#L115-L117) in the CI script.

You can always download it from Github for the given tag you got your build for, the build is based on the Github tag so it's the same as if it was a part of the package.
I don't have the history on why it is being removed from the builds, so I'll have to defer to others to provide more context.

What other plugins are being removed that can be downloaded from the plugins marketplace? If any, those would be free plugins that have their own repository and are standalone plugins. The TaskRunner is a plugin that doesn't have a separate repository and is not a git submodule, so I'm not sure it'd be easily possible to allow for its download from plugins.matomo.org as it stands.

Could you tweak your CI to get the plugin from Github instead? There should be a way how to just get a folder without cloning the whole repo using (a bit unconventional) SVN access to Github — https://stackoverflow.com/a/18324458.

@sgiehl / @tsteur would you have some more info on why we are removing the TestRunner from the build (instead of just disabling it) and can we possibly start including the code for it again?

**Comment by mikkeschiren** [comment]
Today, we need to download the official release, the plugins needed and the git repo to get a proper CI-workflow for testing. It's not a big deal, but it seems unnecessary. But if there are good reasons for it to be that way, I will not argue with that. I can understand that some of the plugins that are more oriented against testing don't have releases, so that can make sense. But it complicates testing.

**Comment by sgiehl** [comment]
Test sources might always contain insecure content, therefor our official build does not contain any test related files on purpose. This also includes the TestRunner plugin. That plugin actually only provides some commands to run tests. But without the test sources being present the plugin is actually almost useless.
If you want to run tests for your plugins you may need a full git checkout with all tests sources. 
For GitHub hosted plugins the most easy way to run tests is using a GitHub action. We even provide a command to generate a action that does everything automatically. See https://developer.matomo.org/guides/tests-github

**Comment by mikkeschiren** [comment]
Yes, I know this. The issue is that we would prefer a testable release, built from the official release, that's the need. We do solve this with some copying and moving around of the pieces, it's ok, but would prefer a simpler solution.

**Comment by sgiehl** [comment]
Can't you simply checkout the tag of a release?

**Comment by mikkeschiren** [comment]
> Can't you simply checkout the tag of a release?

Yes, but becuase of the differences between downloaded release and and what is in the git repo it is many steps to things right, like for using composer you need to:

```
        curl https://builds.matomo.org/matomo-${MATOMO_VERSION}.tar.gz -o matomo.tar.gz; \
        tar xvf matomo.tar.gz; \
        curl https://raw.githubusercontent.com/matomo-org/matomo/${MATOMO_VERSION}/composer.json -o matomo/composer.json; \
        curl https://raw.githubusercontent.com/matomo-org/matomo/${MATOMO_VERSION}/composer.lock -o matomo/composer.lock; \
```
And after that the plugins from the api, and then checkout the git repo in another place, to copy in TestRunner and other things, it is a bit messy in CI world.

We did use the Git repo first as a base, but then we needed to delete test files instead...
I know we are talking about a edge case here, but in any cases, it gets messy :)

**Comment by sgiehl** [comment]
I still can't see a reason for using a production release for testing. Unless you want to perform some sort of black box testing.
For all other cases I would prefer using a git checkout and install the dependencies (composer / npm) manually. 
In a release all dependencies required for testing would be missing and the TestRunner plugin would not work unless you install those dependencies manually.

**Comment by mikkeschiren** [comment]
Our requirement is that a production release needs testing, meaning, when we build the release, we are testing them with different tools, and in the end we remove the testing dependencies. We do this more or less for all applications we deploy. Like in this case - we are addding plugins that doesn't exist in the downloaded release, community plugins, our plugins and premium plugins, that we want to cover with both the testing that is done in the main Matomo repo, custom tests for community plugins, premium plugins etc.
