### ISSUE TITLE
[Bug] Get Column not found: 1054 Unknown column 'capture_manually' in 'field list'" error when trying to install purchased plugin

### ISSUE THREAD

**Issue by jonbellard** [piwik/piwik#22031]
### What happened?

We have had to redeploy our self hosted matomo instance because the 5.0.0 rc3 branch seemed unreliable. So we have redeployed to the latest matomo version within docker and restored the database. 

When trying to install our previously purchased Heatmap and Session Recording Plugin, the platform immediately errors with the following:

![image](https://github.com/matomo-org/matomo/assets/164169420/a52273cb-5ff8-4c93-a465-c9017e0e6166)

This renders the whole application unusable. 

### What should happen?

The plugin should be installed and activated as expected. 

### How can this be reproduced?

Not Sure

### Matomo version

Latest, 5.0.3

### PHP version

PHP version: 8.2.17

### Relevant log output

```shell
An exception has been thrown during the rendering of a template ("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'capture_manually' in 'field list'").
```

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by michalkleiner** [comment]
Hi @jonbellard, sorry to hear you encountered an issue while reinstalling the Heatmap and Session Recording plugin. As that's a premium plugin, please contact Matomo support directly, and the team will be happy to help you.
At a guess, it's likely that some files were left from the old install or not replaced correctly from the old install, and/or that some migrations didn't run as expected. Support will be able to help you with that. I'll close the issue here for now but please feel free to reopen it if the issue turns out to be with Matomo core itself (rather than the plugin). Thank you for your understanding.

**Comment by asishpmathew** [comment]
Fix: ALTER TABLE `matomo_site_hsr` ADD COLUMN `capture_manually` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;
