### ISSUE TITLE
Allow providing a custom database port when setting up Matomo (through installation form and env variable)

### ISSUE THREAD

**Issue by frapell** [piwik/piwik#22051]
## Summary

I am trying to install matomo using the official docker image, using a hosted mysql database with a custom port (ie. not 3306), and I am unable to connect to it, mainly because there is no way to provide the port to connect to...

I saw this PR https://github.com/matomo-org/matomo/pull/13676 which includes a bunch of env vars, but no `MATOMO_DATABASE_DBPORT` or similar. I tried using `host:port` with the `MATOMO_DATABASE_HOST` variable, but that doesn't work.

I also found this https://github.com/matomo-org/docker/issues/172 from 2019, but I guess it is not a desired feature to have?

Is there a quick workaround I could try?

**Comment by sgiehl** [comment]
@frapell you could maybe use the https://github.com/matomo-org/plugin-EnvironmentVariables plugin, which should allow to provide additional configs as env variables.

Besides that I don't have an idea. The problem is, that even the default Matomo installation process currently does not allow to provide a custom database port, but always assumes the default port. So this would be something we need to change aswell.

**Comment by sgiehl** [comment]
We have investigated this issue again and providing a custom database port is already possible by appending it to the hostname. See this FAQ for details: https://matomo.org/faq/how-to-install/faq_151/
