### ISSUE TITLE
[Enhancement] "Pause" website data collection / aggregation to save ressources

### ISSUE THREAD

**Issue by SW-Vincent** [piwik/piwik#22108]
I'd like to have an option to "pause" data collection and aggregation for a website.
Many of my customers have closed website for which they'd like not to lose their data BUT they are at the same time restrained by the forfait limit (number of websites, goals, custom reports, segments, custom dimentions, etc.).
It then would be useful to pause a website, if it leads to keep data "as it is" until the date it was paused and stop counting some elements of the billing, si they can be used for active websites without deleting previously aggregated data.

As you can see, this is quite specific to Cloud users.

Edit : as simply storing data implies a cost for Matomo, maybe there could be a "paused websites" row (ex : 5) within the billing.

## Your Environment

* Matomo Version: Cloud
* PHP Version:
* Server Operating System:
* Additionally installed plugins:

**Comment by Chardonneaur** [comment]
@SW-Vincent damned, this guy is really good at finding useful enhancement feature :)

**Comment by michalkleiner** [comment]
Thanks for the suggestion, @SW-Vincent.
Since this mostly relates to Cloud instances and Cloud users, I will close the issue here but will reassign the issue locally to the product team looking after cloud enhancements for their consideration. In future, for issues relating to Matomo Cloud you may send your suggestions to us using the [Contact Us](https://matomo.org/contact/) form. Appreciate that!
