### ISSUE TITLE
Disable "all" filter in Visitor Log

### ISSUE THREAD

**Issue by iwm-donath** [piwik/piwik#22413]
We have a high traffic Matomo installation on-premise. The Visitor Log fails to load when a user selects "all" in the bottom-right dropdown. I know I can [reset the visualisations settings](https://matomo.org/faq/troubleshooting/faq_21433/), but I'd like to disable the "all" option.

**Comment by randy-innocraft** [comment]
Hi @iwm-donath. Thank you for creating the issue and bringing this to our attention, that's very appreciated. We have reviewed and triaged the problem internally. Our team will prioritise this, and we will update you on the progress here when we have an update to share. If you have any further information or questions, please feel free to add them here.

**Comment by sgiehl** [comment]
Hi @iwm-donath. We had another look at your report. 
The visits log actually should not have a limit option for `All` anymore since a version released in 2018. 
In general there is a config option that applies to all reports to configure the options available for limit selection: `datatable_row_limits`
This one is also applied to the visits log - but there `-1` should be remove from the list.

**Comment by iwm-donath** [comment]
Thanks, setting this in my config.ini.php did the trick:

> [General]
> datatable_row_limits = "25,50,100,250,500"
