### ISSUE TITLE
Sudden drop in tracking on 31/07 and no tracking since 08/08

### ISSUE THREAD

**Issue by Mathildejck** [piwik/piwik#22497]
Hello guys, 
My new website has been connected to Matomo since dec 2023. No issues to report, tracking was perfect. All of a sudden on 31/07, the reported visits dropped and I have no visit report at all since yesterday 08/08. 
It's all in order on Google Analytics so it doesn't seem to be a trafic issue. 
All the setup is also in order on my website, we haven't changed anything. 
Can you help ?
Huge thanks, 
Mathilde
![Capture d'écran 2024-08-09 090905](https://github.com/user-attachments/assets/874def1f-c24e-4694-9900-cdf59e58f689)

**Comment by sgiehl** [comment]
Hey @Mathildejck,
we are only handling feature requests and bug reports here on GitHub.
For support requests please use our forums at https://forum.matomo.org/ or message our Support team.

To identify the problem you could
* check if the visits log still contains data (if it does, it might "only" be an archiving issue)
* If no data is tracked at all, this could be caused by a lot of reasons. You could help by checking, if tracking requests are still correctly sent from your website (browser console should show the request, and if it has problems) and if your webserver still processes those tracking requests (e.g. no errors in error log).
