### ISSUE TITLE
Adjusting editor rights

### ISSUE THREAD

**Issue by PierreWiding** [piwik/piwik#22635]
Hi
I am admin in our account and i would like to adjust the editor rights so that they can create heatmaps. How do i do that?

**Comment by sgiehl** [comment]
Hi @PierreWiding,

Adjusting the existing permission levels is currently not possible. This will be handled as part of #21175.

Also for questions like this, please use our forums at https://forum.matomo.org or get in touch with our support if the issue is related to a premium plugin. The issue tracker on GitHub is only for bug reports and feature requests.

Cheers
