### ISSUE TITLE
[Bug] First run unable to pass systemCheck

### ISSUE THREAD

**Issue by TakaShirowa** [piwik/piwik#22871]
### What happened?

In a Windows environment, I installed Matomo on Nginx, and when I first run it and enter the welcome page, I encounter an error when I click the "Next" button. The screenshot is of the extensions I have configured in PHP. As I am not a PHP developer, I am not quite sure what is causing the error.
![1_20241217104716](https://github.com/user-attachments/assets/628ed453-5d8d-4101-85f9-06c7226fc8fc)
![2_20241217104814](https://github.com/user-attachments/assets/7f374e72-0582-4b28-9270-2343f7c4780c)
![3_20241217104843](https://github.com/user-attachments/assets/619cef95-8061-4590-b782-606589594919)

### What should happen?

I hope to run Matomo normally.

### How can this be reproduced?

None

### Matomo version

5.2.0

### PHP version

8.4.1

### What browsers are you seeing the problem on?

Microsoft Edge

### Computer operating system

windows11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by sgiehl** [comment]
Hey @TakaShirowa,
Sorry to hear you are having trouble with setting up Matomo. 
The problem most likely is caused by the way PHP is set up.
Unfortunately we are not able to provide support for system related set up problems here on GitHub. 
Please try to find some help on our forums at https://forum.matomo.org. This issue tracker is only used for detailed bug reports and feature requests.

Nevertheless some hints that might help to trace down the problem:
* Check your error log if there are any errors that might point to a missing extension or message that helps to find the root cause of your error
* Try running `./console diagnostics:run`, this might print possible problems if its working
