### ISSUE TITLE
piwik.js: cross domain POST and automatically setRequestMethod('POST') when request > 2K

### ISSUE THREAD

**Issue by robocoder** [piwik/piwik#2321]
GA starting doing this earlier this month.

We've had setRequestMethod() since Oct 2010, but this is an increasing necessity with the increase in size of tracking requests (e.g., attributeable to first party cookies and custom variables).

**Comment by asafyish** [comment]
We are tracking some pages with unicode text, so when it's encoded it's gets really long (each character is encoded to 4 characters). our get requests length is around 2500 which is way over the 2000 limit. Is there a solution ? I was thinking about using setCustomRequestProcessing and removing some parameters that we don't care about.

**Comment by ashleyyang0610** [comment]
I also got 414 (Request-URI Too Large) error when my event value is too long in trackEvent method.
In this case, I want to record complete RESTful APIs info such as name, body.
It's not a good long-term solution to modify piwik web server request header size since I can't estimate the length of body for each request.
I think it's what I want if it automatically setRequestMethod('POST') when request > 2K, would you please add this as soon as possible or give me some suggestion for fixing this error message?
Thanks.

**Comment by mattab** [comment]
> would you please add this as soon as possible or give me some suggestion for fixing this error message?

We welcome Pull requests :+1: http://developer.piwik.org/guides/contributing-to-piwik-core

**Comment by tsteur** [comment]
I might be working on this one
