### ISSUE TITLE
Show paging in the screen 'Manage websites' to easily manage thousands of websites

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#3838]
Similarly to the "All websites" dashboard, the "Manage websites" admin screen should use paging and could display by default, the first 100 websites.

This feature is useful for websites automatically creating sites and tracking thousands of small-medium sites.

This could use AngularJS similarly to the All Websites rewrite in #4692

Using AngularJS: #4691

**Comment by tsteur** [comment]
Today I tried to open the SitesManager with 3600 sites and it showed nothing for over 5 minutes and Chrome tried to kill the page multiple times. After the page was loaded it was not really useful. The whole time while the page was loading it was also no longer possible to use it since the browser was just too busy. This should be short term or fixed soon. Basically Piwik is not usable when managing many sites

**Comment by mattab** [comment]
were the 3600 sites pre-processed and "on demand archiving" disabled? that's a bit worrying. Moving to `Short term`!

**Comment by tsteur** [comment]
It is the Manage Websites screen so archiving should not be relevant?

**Comment by mattab** [comment]
You're right I'm deleting previous comment

**Comment by ataraxie** [comment]
I'm experiencing the very same issue as @tsteur with only 700 pages. According to my timeline profile, Chrome is busy with scripting for around 1.5 minutes. See http://forum.piwik.org/read.php?2,125306

**Comment by tsteur** [comment]
I think we should definitely work on this issue for 2.13.0 since Piwik becomes unusable with many sites otherwise...

**Comment by ataraxie** [comment]
Please please do so!

**Comment by mattab** [comment]
Moved to 2.13.0 :+1:
