### ISSUE TITLE
Javascript tracker can send tracking API  requests as bulk for better performance

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4910]
There are cases where on the same page one user may call trackPageView() multiple times, or even trackPageView, trackEvent, trackEcommerceOrder, etc.

in these cases in the Piwik.js request handler queue, we should be a bit clever and detect there are several requests queued. Then we send these requests as bulk. 

Advantages:
- Resolves edge cases such as #4909. Indeed if we are able to track all requests from the same user as bulk we will avoid several race conditions (including those we have not discovered yet).
- Faster, less HTTP requests in case users track several requests per page.

Follows up the bug in #4909

**Comment by kachkaev** [comment]
After a few experiments with piwik, I can confirm that the bug still exists. When a mix of events and page visits happen nearly simultaneously, it is likely that they are recorded in the wrong order in the database. The issues seems to be simply caused by different speeds of HTTP requests. Having that ```sendBulkRequest``` already exists in ``piwik.js```, how difficult would it be to fix the processing of a set of ```_paq.push()``` calls?

**Comment by mattab** [comment]
At this point it seems better not to implement this feature, as otherwise it would lead to many POST requests to the Tracking API which is not desired because it would prevent us from [Replaying the tracking requests later on](https://piwik.org/faq/log-analytics-tool/faq_19221/), in case of a Piwik server problem. Wont fix.

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/javascript-react-bulk-sending-events/50498/1

**Comment by sonnd08** [comment]
@mattab What if we store client time for each event and send to Matomo? So we still only need 1 POST request but the time still correct.

Also I would like to have a setting to define which event will not being put in bulk request (Example with `purchase` event, it better being sent immediately instead of waiting for a delay and user close page before events could be sent)?
