### ISSUE TITLE
No options for goal management on the Goal page

### ISSUE THREAD

**Issue by rivadav** [piwik/piwik#6022]
**Problem**
When user is on the Goal page, he cannot edit or remove it from this level. He has to go back to the Goals overview which is not convenient. It's minor problem but can improve users productivity.

**Proposed solution**
We can add management options on the bottom of the page. Combined with easy switching between Goals from the issue https://github.com/piwik/piwik/issues/5977 it'll be easier to manage them contextually.

![goal_page](https://cloud.githubusercontent.com/assets/1769990/3966220/a24aad4e-27a0-11e4-9372-7b466b058204.png)

Wireframes: http://vm8ttr.axshare.com/#p=goal_page

**Comment by tsteur** [comment]
"Goals Management" is also pretty hard to discover in "Goals overview". Does it maybe make sense to add a new item "Goals Management" to the submenu before "Goals overview"? Maybe instead of having "Goals Management" the item could be named "Create Goal" so one can directly create a new goal from the menu, viewing and editing a specific goal is then done under its specific section as suggested in this issue in the screenshot or so. On the other side one does not create a new goal so often.

 Or maybe we move "Gaols Management" somewhere else eg to `Settings` / Admin menu as websites etc. are also configured there?

"Goals Management" is kinda a separate issue but it might affect how we solve the edit goal part. Would be nice to find a way to solve this issue properly.

**Comment by tsteur** [comment]
I think I would go with the attached solution meaning adding a point "Goals Management". This will be a separate page listing all the goals and having the possibility to add a new goal. If there is no goal yet nothing will change and we would still show "Add a new goal" in the submenu. As Ecommerce is more or less only a goal it doesn't really make sense to list it first (neither does it look good). Therefore I would move it after "Goals Overview". It could even make sense (technically) to move "Ecommerce" into "Choose Goal" in case there are many goals but somehow wouldn't to it. Think this one should be easily accessible with one click. 

As the "Goals Management" will have its own page and is easier accessible I don't think we longer need that suggested "edit goal & delete goal" on every goal page. It won't be used often, it doesn't look so good / adds clutter and it would be still not so easily discoverable.

**Comment by mattab** [comment]
This looks good. Feedback
 * Ecommerce was first in the sub-menu because when a website has Ecommerce enabled, then Ecommerce goal report are the most important goal reports for users (in 99% of cases).
 * main menu is called `Ecommerce & Goals` which means Ecommerce is first.
 * It looks like `Goals management` is first sub-menu. But clicking on `Goals` or `Ecommerce & Goals` main menu should load the first submenu item which should be a report. so maybe we have to move `Goals management` out of the first sub-menu? 

> I was thinking would that "Goals Management" page maybe also allow to enable/disable Ecommerce? I don't think anyone would expect this setting there and would be at least still needed under Websites Management

+1

**Comment by tsteur** [comment]
Maybe we need to change the item `Ecommerce & Goals`? If Ecommerce is so important for that person, maybe it could be a separate main item (splitting the two). Meaning "Ecommerce" => click on it would directly show ecommerce report and not have any submenu (maybe later ecommerce log would be separate menu item etc). Goals would be as it is now just without Ecommerce.

It feels and looks weird/wrong not showing Goals Management and Overview first and I think it could make sense to split those two into 2 menu items

**Comment by mattab** [comment]
> If Ecommerce is so important for that person, maybe it could be a separate main item (splitting the two). 

this could work! +1 for trying

**Comment by tsteur** [comment]
@rivadav We do now have "Manage Goals" under the user menu and "Add new goal" always under Goals in the reporting menu. We also link from "Add new goal" to "Manage goals". Do you think this would be ok already? I don't think we actually need an edit/delete link in each goal as this is not done that often I presume.

**Comment by tsteur** [comment]
See comment in last commit:

> Added new attribute edit-url to enriched headline. Setting this will
make the headline clickable, on hover appears a title and pointer to
indicate that it is clickable and to explain what happens when clicking
on it. I think this is more intuitive than showing an edit icon on hover
which would be an alternative. As it is done in enriched headline we
could otherwise change the behaviour easily.
