### ISSUE TITLE
Release Piwik 3.0

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6074]
This ticket is a place-holder for ideas and tasks involved in the release of Piwik 3.0.0.

Release date: To be discussed. What do you suggest?

**Comment by mattab** [comment]
See issues in 3.0.0 milestones for more information about Piwik 3

**Comment by hpvd** [comment]
sorry just found issue today. Even if this is already closed just want to share a strategical thought:

Piwik 3.0 milestone already includes lots of important issues.
When looking at them, I noticed that most of them are work topics "inside" of Piwik.
This is of course good to generate a solid technical basis.

On the other side the normal user is no developer and will hardly notice the changes.

Since 3.0 is a major milestone one should maybe think of giving additionally some great "visible" changes/features, which make normal users
- wanting  to upgrade to 3.0 instantly
- make them talking about great new features
- produces visibility on professional magazines and Websites & start reader discussion

so that the general impression is: 3.0 is a HUGE STEP - not only for technicians but for everyone

=> What do you think of this?

**Comment by hpvd** [comment]
an idea on
**what could these "I want it" features be?**
e.g. for everyone: features in the field of "actions on tracked data" like delete, mark/flag etc.
or
e.g. addressing the big group of the small store owners using piwik: a packet of 2-3 features of the field of ecommerce.
