### ISSUE TITLE
Allow any plugin to extend and display data in the Visitor Log and Visitor Profile

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#6111]
Follow up for #6045 where we made it possible for any plugin to add data to the API. Now we want the plugins to extend Live widget, Visitor Log and Visitor profile.

This can be quite complex as we probably do not want loads of events there. Maybe we can start using AngularJS for this as a proof of concept. As they do not use the dataTable it is easier to rewrite this component. Maybe there are other, better solutions as well.

**Comment by tsteur** [comment]
This will be important for #7131 and #4734 . When a type (eg `Website` or `MobileApp`) disables some reports/dimensions, the related information should not be shown in the Live plugin. For example if referrers information are disabled by a type "MobileApp", no referrer information should be displayed in the Live reports.

**Comment by KaanErturk** [comment]
This would be very much useful in order to extend visitor profile popup for additional information. Right now the only **hacky** way seems to be to add the data to the `$visitor['customVariables']` array, even though the values are limited to 50 chars in the template.

Eventually, it would be great to have a way to add new rows (under the avatar) to the visitor profile popup, like `Summary`, `Location`, etc. That would give plenty of space to use there.

**Comment by mattab** [comment]
Adding tentatively to 3.0.3 milestone, to be fixed along with:

* https://github.com/piwik/plugin-CustomDimensions/issues/28 - Show custom dimensions in Visitor log
* https://github.com/piwik/plugin-MarketingCampaignsReporting/issues/3 - Show campaign tags in Visitor log

Ideally we'd make both Visitor Log and Visitor Profile use same logic so that extending one extends the other too!

**Comment by hpvd** [comment]
+1

**Comment by hpvd** [comment]
would be perfect if this solution not only works for plugins but also for Piwiks "own" base data,
e.g. Content-tracking: display content views and interactions in the Visitor log #6416 https://github.com/piwik/piwik/issues/6416

**Comment by hpvd** [comment]
for reasons, details, ideas regarding extending informations in visitorlog see also #6416

**Comment by hpvd** [comment]
when extending information in visitorlog one maybe should take this into account to give new information the right position:
visitor profile: built image of vistor is distorted https://github.com/piwik/piwik/issues/9507

**Comment by hpvd** [comment]
does this also cover a possibility to extend visitor summary in visitor profile?
would be pretty handy for things like this one:
https://github.com/advanced-online-marketing/AOM/issues/12

**Comment by sgiehl** [comment]
Actually yes, that should be possible by implementing a [VisitorDetails](https://github.com/piwik/piwik/blob/3.x-dev/plugins/Live/VisitorDetails.php) class in the plugin and adding a [ProfileSummary](https://github.com/piwik/piwik/blob/3.x-dev/plugins/Live/ProfileSummary/Summary.php).

**Comment by hpvd** [comment]
many thanks, awesome!
