### ISSUE TITLE
Components (ie, Report, Dimension, Menu, etc. subclasses) should immutable singletons

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6229]
These classes mainly provide metadata regarding plugin extensibility so there's no reason for them to be instantiated outside of Piwik core, nor is there reason for them to be modified outside of the classes themselves. Thus, they should be immutable and object identity should provide object equality (eg, there should only be one instance of each subclass created). They could potentially be stored in a DI container, however, it should be noted that since they do not need to be configured, they should be instantiated automatically and not be referenced in DI config.

**Comment by mattab** [comment]
This will be done as part of the UI & Client side improvements project, where we slowly move logic from server side controllers towards client side controllers (AngularJS), and improving our HTTP APIs so that clients (eg. browser) can do everything with such APIs. Some work is already done in Piwik 3.0 branch, for more info see this issue https://github.com/piwik/piwik/issues/7131
