### ISSUE TITLE
store a report's API method + action and the segment used to get a report in DataTable metadata

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6251]
As title, will simplify code that needs to know what segment/API method was used w/ a report (for example Row Evolution + others).

**Comment by mattab** [comment]
This will be done as part of the UI & Client side improvements project, where we slowly move logic from server side controllers towards client side controllers (AngularJS), and improving our HTTP APIs so that clients (eg. browser) can do everything with such APIs. Some work is already done in Piwik 3.0 branch, for more info see this issue https://github.com/piwik/piwik/issues/7131
