### ISSUE TITLE
modify ViewDataTable so it uses report/dimension/segment metadata classes when possible

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6253]
As title. Instead of using certain ViewDataTable/Config properties (ie, Config::$subtable_controller_action), Report/Dimension/Segment classes should be used (ie, Report::actionToLoadSubtables).

**Comment by mattab** [comment]
This will be done as part of the UI & Client side improvements project, where we slowly move logic from server side controllers towards client side controllers (AngularJS), and improving our HTTP APIs so that clients (eg. browser) can do everything with such APIs. Some work is already done in Piwik 3.0 branch, for more info see this issue https://github.com/piwik/piwik/issues/7131
