### ISSUE TITLE
make all piwik metadata (report/dimension/segment/etc.) available client side as merged/minified asset

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#6256]
Can convert Report/Dimension/Segment classes to JSON structure and store as asset like LESS/JS is now. Can load in client via AJAX by new angularjs service.

**Comment by mattab** [comment]
This will be done as part of the UI & Client side improvements project, where we slowly move logic from server side controllers towards client side controllers (AngularJS), and improving our HTTP APIs so that clients (eg. browser) can do everything with such APIs. Some work is already done in Piwik 3.0 branch, for more info see this issue https://github.com/piwik/piwik/issues/7131
