### ISSUE TITLE
Tests randomly fail on Travis ci with error SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6557]
The goal of this issue is to make sure that the error `SQLSTATE[HY000]: General error: 2006 MySQL server has gone away` will not show again (randomly) in Travis CI.

Example randomly failed build: https://travis-ci.org/piwik/piwik/jobs/39441245

Also discussed in https://github.com/travis-ci/travis-ci/issues/2250

Our FAQ explains to our users how to solve this: [ How do I fix the error “Mysql Server has gone away”?](http://piwik.org/faq/troubleshooting/faq_183/)

**Comment by mattab** [comment]
Another one in https://travis-ci.org/piwik/piwik/jobs/46159944

**Comment by mnapoli** [comment]
From a latest build, the stack trace:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /home/travis/build/piwik/piwik/libs/Zend/Db/Adapter/Pdo/Abstract.php:263
Stack trace:
[...]
#5 /home/travis/build/piwik/piwik/tests/PHPUnit/Framework/Fixture.php(839): Piwik\DbHelper::dropDatabase('piwik_tests')
#6 /home/travis/build/piwik/piwik/tests/PHPUnit/Framework/Fixture.php(295): Piwik\Tests\Framework\Fixture->dropDatabase()
#7 /home/travis/build/piwik/piwik/tests/PHPUni [the stack trace is truncated here unfortunately]
```

We can see that the query that failed is `DROP DATABASE`, which is executed in test's `tearDown()`. So it might be that a test has a query that fails, which breaks the MySQL connection. Then in the tearDown, `DROP DATABASE` fails because of that, and the new exceptions "overrides" the original exception in PHPUnit's log.

I had that kind of things happen in a previous project, we had to test in the database/table still existed before dropping it.

What we could try is wrap the call to `dropDatabase` in a try/catch?

**Comment by RoySegall** [comment]
Well i'm join in about this one. I think there is a problem with memory. Although i tried to increase the max packet size to 64M the size is still 16M. What i did so my test will is to split it.

You can look [here](https://travis-ci.org/openscholar/openscholar/builds/46316520) that the tests failed  and you can see [here](https://travis-ci.org/openscholar/openscholar/builds/46317711) that the matrix passed.

splitting test is a good solution but it's a really good one because each matrix set up the environment. For small projects it's could be good but for large projects like OpenScholar is not a good solution because the set up takes 20 min and you have only two matrix at a time. If someone know how to solve that i'd like to here about it.

**Comment by mattab** [comment]
Since we removed the PHP 5.3.3 build and only run on latest PHP I think this issue is now gone. Please re-open the issue if you still find cases of "mysql has gone away" in Piwik builds
