### ISSUE TITLE
beforeunload is not available in packaged apps

### ISSUE THREAD

**Issue by dareid** [piwik/piwik#6614]
Using Piwik in a packaged chrome app produces the following error when including the piwik.js:

"beforeunload is not available in packaged apps"

Please see https://gist.github.com/dareid/eaf87732c5f79e0dfef1 as an example, load this into chrome as a unpacked extension (also demonstrates #6577)

**Comment by mattab** [comment]
@tsteur any thought about next step on this issue? I'm wondering if it's a bug that we should fix in short term or not

**Comment by tsteur** [comment]
I'd say bugs in piwik.js should be fixed in short term if possible.

@dareid what is the impact of that error? Does it track at all? 

It seems like it already fails when it tries to add the event listener.  A solution would be to just not listen to this event inside a chrome app? Maybe an event `suspend` would work as an alternative.

**Comment by mattab** [comment]
If anyone else experiences this issue, please let us know, we need to know if it's important to fix or not :-)

**Comment by tsteur** [comment]
FYI: By 2018 Google will remove Chrome Apps from Windows, Mac, ... see https://9to5google.com/2016/08/19/chrome-apps-removed-mac-windows-linux/ However, they will remain on Chrome OS

**Comment by mattab** [comment]
> FYI: By 2018 Google will remove Chrome Apps from Windows, Mac,

Since this will be deprecated soon we assume there is nothing to do here. Closing
