### ISSUE TITLE
Live.getCounters times out on very large instance

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6758]
On a very large Piwik instance, there are several performance challenges. One issue is that the Real time counter displayed on top of the Real time visitors widget times out on a very large DB.

Query is:
```
SELECT
                count(*) as visits, COUNT(DISTINCT log_visit.idvisitor) as visitors
            FROM
                piwik_log_visit AS log_visit
            WHERE
                log_visit.idsite in ('2') AND log_visit.visit_last_action_time >= '2014-11-24 10:58:45'
```

the problem likely is the COUNT(DISTINCT) which doesn't scale. 

Possible solution: let user disable the counting of unique users via config file. For example we could reuse the existing `enable_processing_unique_visitors_day` and if it is se to `0` then the Live API would not issue `COUNT(DISTINCT idvisitor`.

**Comment by tsteur** [comment]
I can confirm the problem is caused by `COUNT(DISTINCT log_visit.idvisitor)` but couldn't find a way to speed it up.  FYI: it uses the index `index_idsite_idvisitor`. Using any other index is much slower. The only way would be probably to add another index for this but doubt that's worth it.

**Comment by mattab** [comment]
>  The only way would be probably to add another index for this but doubt that's worth it.

just to confirm, this feature is not worth a new index.

**Comment by tsteur** [comment]
As `enable_processing_unique_visitors_day` is enabled by default I agree that it is not very useful etc. 

The problem is, that the current `getCounter` API method is used for the "last 3 minutes" but also for the "last 24 hours". A query that performs much slower over the last 24 hours might perform fast when only checking over the last 3 minutes.

If we only look at the last 3 minutes in that widget we could write a separate method that is faster for this use case maybe. I reckon in 3 minutes we're talking about max 150k visitors that we have to deal with?  

Currently, querying the unique visitors means it uses the index `index_idsite_idvisitor` and has to check each row for date/time. This is faster when checking over 24 hours. But over 3 minutes we could maybe use the index on `last_action_date_time` reducing the results to check quite a bit. We would need to try this on a bigger instance maybe. A subselect etc. could be faster

**Comment by tsteur** [comment]
Edit: I just verified MYSQL will automatically choose the `index_idsite_datetime` index once the result set is lower (eg < 200k visitors). We do not have to force a different index. So the Counter widget should not be a problem. The RealTime widget as described in the issue should be fast now as well see pull request. All good!

**Comment by mattab** [comment]
well done!
