### ISSUE TITLE
All websites dashboard - improve performance when thousands of websites

### ISSUE THREAD

**Issue by mgazdzik** [piwik/piwik#6809]
Currently on instance with really big number of websites (i.e. 20k+) Multisites dashboard tends to time out. It's caused by loading all sites into JS in one API call.
maybe there should be pagination implemented server-side so each API call only retrieves portion that would be displayed at one time to the user to speed up this view.

**Comment by tsteur** [comment]
FYI: I just performed a test with 4k websites and the problem seems not to be the JS etc. The bigger problem seems to be server side even with browser archiving disabled it takes easily 15 seconds on the server. Even if we do use paging it would still need that time. I'll have a look to see if there's a quick fix possible to make it a bit faster. Maybe we'd have to create an archive for MultiSites.getAll as well (if possible, don't know)

**Comment by tsteur** [comment]
A lot of time is actually spent to generate the datatable, but also a lot of time is spent to format the datatable when having eg 4k rows (= 4k websites). So using `filter_limit=10` would improve performance quite a bit as well. So we probably have to update the dashboard UI to use paging AND improve speed of report generation etc. (eg via archiving MultiSites.getAll)

**Comment by mattab** [comment]
>  Maybe we'd have to create an archive for MultiSites.getAll as well (if possible, don't know)

+1 makes sense!

**Comment by mattab** [comment]
it may be complicated to fix and maintain the feature [Website Groups](http://plugins.piwik.org/WebsiteGroups), but It would be very nice to solve this performance issue for 3.0.0 or before!
