### ISSUE TITLE
Administration/Settings missing

### ISSUE THREAD

**Issue by innoreq** [piwik/piwik#6878]
After upgrading to the current version from 2.3.x, one of the menu entries (probably the administration/settings entry) in the upper right corner is missing (see picture). I reinstalled completely Piwik, but nothing changed (new files, new database, new account).

![bildschirmfoto 2014-12-18 um 15 50 04](https://cloud.githubusercontent.com/assets/9914806/5489938/dc870ed0-86cd-11e4-8590-7caffdcdb1cc.png)

**Comment by tsteur** [comment]
Make sure to follow all the steps in the mentioned FAQ: https://piwik.org/faq/troubleshooting/faq_18485/

If it still does not work, try to update Piwik manually see the steps in https://piwik.org/docs/update/#the-manual-three-step-update  . There will be a new major update very soon which also could fix this problem.

If it still does not work: Contact your host or sys-admin. For some reason your server seems to not deliver HTML files properly.

If this does not help send us credentials to your Piwik installation to "hello at piwik.org" and we'd have a look but we won't be able to do much without having access to the actual server.

**Comment by innoreq** [comment]
I sent you the .htaccess content to the above mail address.

**Comment by mattab** [comment]
Thanks for report. This bug will be fixed in next release as side effect of the new top menu system which will not have a dropdown anymore. I'm closing now pro-actively but @tsteur will get it done 

FYI the new Top Menu, example for a super user
 * Dashboard
 * All Websites
 * Administration
 * $UserName
 * Signout

**Comment by lupa18** [comment]
And you think is better wait to the next release and use admin section by entering its URL ?

**Comment by tsteur** [comment]
You'll most likely have to make sure HTML are served by your webserver anyway as many other components won't work otherwise. In the above screenshot one can see eg the Website Selector is not displayed which means also Sites Management, All Websites Dashboard and many other things won't work. So it is probably not a good idea to just wait for the next release. Have a look at this FAQ: http://piwik.org/faq/troubleshooting/faq_18485/ 

Also in one screen I can see a 403 API response which looks like a server configuration issue as well which needs to be fixed (not a Piwik issue).
