### ISSUE TITLE
Can't finish installing 2.10.0-rc1 (website time zone is not valid)

### ISSUE THREAD

**Issue by rightaway** [piwik/piwik#6904]
In the 'Setup a Website' step of installation of 2.10.0-rc1 I get an error when submitting the form. Blocked at this step, can't proceed past.

```
Please fix the following errors:
    website time zone is not valid
```

This old issue https://github.com/piwik/piwik/issues/2963 looks similar and says it's something to do with permissions, but I'm just trying Piwik out and am using a username of 'root' and blank password to connect to the local 127.0.0.1 MySQL installation. It's using the MySQL superuser so shouldn't have any permission trouble.

UPDATE: Recreating the database and reinstalling seemed to solve this. This may have been caused by me accidentally going back to a previous screen in the installation process. I was on the Setup a Website screen and clicked the back button a few times to check something from a previous step. The browser said the page was expired, and when I tried to go back through my browser history to get back to where I was it started giving me this error. The installation shouldn't be corrupted because of going to a previous page.

**Comment by mnapoli** [comment]
I think we can close this one considering the "edit"?

**Comment by TheNotary** [comment]
The solution to this would be to write a check for each of the install steps to confirm that the database operations haven't been conducted yet.. you may also need to check the config.ini.php file for clues too.  When you think about it, the 'nav bar' that shows the steps to installation is kind of broken in that you can't click through the links to make it work.  

Some of the install steps are in fact simple hyper links which make GET requests rather than POST requests (the best practice for things that make server side changes).  

Is there anyway we can get this re-opened?  I've been bug tracking for quite a while and would be interested in having my fixes applied to upstream if possible.

**Comment by mattab** [comment]
Hello, please use the latest version 2.16.2 where this should be fixed

**Comment by TheNotary** [comment]
Hi @mattab, your name has turned up on my browser more times than I can count over the last week.  I know first/third hand that Piwik is a tough project to hack on, excellent open source work!  It's nice to meet you.  

I'm currently on 2.16.2... it's in a docker container.... I'm still tracking the bug(s?), thought I had it yesterday, but caught a brief case of carpel tunnel and had to switch to read only mode.  I've been using curl commands to simulate the install process, and they're all leading up to either this bug or another one where piwik boasts that it needs to upgrade the database, and then fails due to their being missing columns.  

https://github.com/piwik/piwik/issues/6746

I'm starting to think that the install process may require javascript or perhaps a cookie... or it' needs some `sleep` commands because the db is getting race conditions.  I have a docker repo that isolates the phenomenon if you'd like to take a look at it with my I can upload it, but it's commit history looks like trash atm and is subject to change ><

**Comment by TheNotary** [comment]
I got my stuff working!  I think it needed a couple GET requests that I didn't think were necessary.  I'm going to articulate some code cleanliness issues below and possible move them into a new issue if they can be merged in here:

## /index.php?action=firstWebsiteSetup has a post form that's dependent on the URL to it's GET/show page.  

If you redirect `/` to render `index.php?action-firstWebsiteSetup` you will find that the post button on the form doesn't work.  I believe this is due to the javascript layer stepping in and adjusting the POST path or something.  I'm not 100% on this, I just know that the app works when JS is disabled.

**Comment by mattab** [comment]
> I'm starting to think that the install process may require javascript or perhaps a cookie... 

we actually don't test Piwik without JavaScript / without cookie use case. it's most likely not working. It's not really a priority or supported use case for us, ie. we don't test for it manually or via our automated tests suites. However if you find some issue and submit pull request so that Piwik works without javascript / cookies, we would for sure try to review them and merge them, so to make Piwik more usable by people who cannot use JavaScript for some reason.
