### ISSUE TITLE
Improve device model & brand reports

### ISSUE THREAD

**Issue by sgiehl** [piwik/piwik#6933]
We should try to improve the current reports for device brands and models.

Device models are currently reported without any associations to their related brand. As some device names are ambiguous the current report is not as accurate as it could be.
Instead we maybe should display kind of combined report showing brand and model.

In addition it would maybe make sense to add subtables to the brand report, reporting all models for the specific brands.

**Comment by tzi** [comment]
There is currently two tables: "Device brands" and "Device models".
Like you said, I don't think that "Device models" is usable for now, because of the ambiguous names (201, D802, F220K, etc.).
![device-names](https://cloud.githubusercontent.com/assets/415891/5630338/342d58bc-95bd-11e4-9e3e-52ec7239470d.png)

Adding the device models as the brand subtable seems to be a good solution.
What we have to do with the device model table it-self?

 * Prefix the device model with the brand, to provide the device model order that the device brand grouping removed.
 * Remove the device models table from the device page, if we think it is not usable

I think we should try to have a more consistent device page. For now:

 * The browser brand has no subtable for the browser versions. We only show brower brand.
 * The operating systems are not grouped by brand. We only show operating models.
 * The device brand has no subtable for the device models. We show both device brand and device models.

Cheers,  
Thomas

**Comment by mattab** [comment]
> Device models are currently reported without any associations to their related brand. As some device names are ambiguous the current report is not as accurate as it could be.
> Instead we maybe should display kind of combined report showing brand and model.

Maybe it would be enough to change the `Device Model` report and set the label to `Brand - Model` instead of just `Model` ?

> In addition it would maybe make sense to add subtables to the brand report, reporting all models for the specific brands.

Sounds good, although maybe it could be done as "next step" as already pre-pending the Device Brand to the Model, would be huge improvement I think :+1:

**Comment by mnapoli** [comment]
@mattab should we close this now that the PR is merged?

**Comment by mattab** [comment]
![device model](https://cloud.githubusercontent.com/assets/466765/6953393/8d9b1bea-d925-11e4-984c-17d683d6d35a.png)


Yes, looks good :+1:
