### ISSUE TITLE
Date to load by default does not always work (regression)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6960]
Reported in [forum](http://forum.piwik.org/read.php?2,123269)

>  I have the Piwik set to open a certain site when I login, and also display the data via the current month. 

Issue was reproduced in 2.10.0.

**Comment by tsteur** [comment]
The pull request fixes it but please be aware that it is partially broken by design.

There is an event `UsersManager.getDefaultDates` in https://github.com/piwik/piwik/blob/2.10.0/plugins/UsersManager/Controller.php#L199 that gets default dates and translations but this one is not considered in `getDefaultDate` https://github.com/piwik/piwik/blob/2.10.0/plugins/UsersManager/UserPreferences.php#L78 and `getDefaultPeriod` https://github.com/piwik/piwik/blob/2.10.0/plugins/UsersManager/UserPreferences.php#L101 

It is not really possible to do this without breaking the API as the event does not contain information which date/period to use for a selected default date. As mentioned currently the event only returns a name and translation currently

**Comment by mattab** [comment]
Thanks for the issue. Bug was fixed.
