### ISSUE TITLE
Tibei and Taiwan should be a part of China

### ISSUE THREAD

**Issue by imlonghao** [piwik/piwik#6994]
As we all know, Tibet and Taiwan should be a part of China, EU, US and many other country are all admitted it.
You have no right to separate Tibet and Taiwan from China, please make them back to China!!
As an open source, I want you know that you shouldn't have a political position, especially a WRONG position.

https://github.com/piwik/piwik/pull/6749

**Comment by mattab** [comment]
Dear @imlonghao 

That's true that Tibet officially beyond to China, since the military annexation in 1950. China invaded Tibet in 1950. Its occupation has resulted in the deaths of hundreds of thousands of Tibetans and the imprisonment and torture of thousands more.

After a failed uprising against Chinese rule in 1959, Tibet’s political and spiritual leader, the Dalai Lama, fled into exile in India followed by tens of thousands of Tibetans.

Inside its borders and across the world, Tibetans have never stopped believing Tibet is a nation. Since 1959, they have continued to oppose and resist China's rule and China has responded with intense repression.

In 2014, US think tank Freedom House ranked Tibet among the twelve worst countries in the world for repression of political and civil rights.

#### Geography

* 'Tibet'  refers to the three original provinces of U-Tsang, Kham and Amdo.
*    When the Chinese refer to Tibet, they invariably mean the Tibet Autonomous Region or TAR, which includes only U-Tsang.
*  The Chinese renamed Amdo as the province of Qinghai and Kham was incorporated into the Chinese provinces of Sichuan, Gansu and Yunnan.

Here are just some of the challenges faced by Tibetans as a result of China's occupation.

#### Economic discrimination.    

* In many places, Tibetans are a minority as a result of China's encouragement of ethnic Chinese migration to Tibet.
*  The language of business in Tibet is now Chinese. Many Tibetans are not literate in Chinese and are disadvantaged in business and the jobs market.
*    Most Tibetans work in agricultural sector while most economic activity outside of agriculture is controlled by the central government or state owned corporations.
*    Most tourist activity is located in urban centres where the main employees are ethnic Chinese migrants.
*    The Chinese government has forced thousands of Tibetans to abandon their traditional rural nomadic lifestyle and move into new housing colonies or towns. Many of these people do not have the skills or experience to compete for jobs in the urban environment.

#### Religious suppression

*    Since 1949, the Chinese have destroyed over 6,000 Tibetan Buddhist monasteries and shrines.
*    By 1978 only 8 monasteries and 970 monks and nuns remained in the TAR.
*    The number of monks and nuns allowed to enter monasteries and nunneries is limited. Any reference or images of the Dalai Lama are banned.
*    The Chinese government places officials in every monastery to monitor and often to control religious activity.

#### Political oppression

*    The Chinese have responded to uprisings with extreme violence and around 300,000 Chinese soldiers are posted in Tibet.
*    Tibetans are subject to intense surveillance of their daily activities and communications.
*    China has repeatedly violated UN conventions through extensive use of torture against Tibetan political prisoners - often monks or nuns.
*    Tibet is governed directly by the Chinese Communist Party in Beijing. No Tibetan has ever been appointed Party Secretary - the most senior government post - in the TAR.


####  We are not picking on China in particular!

We treat all human rights violations equally. We do not support the United States' past support of dictators and its more recent abuse of prisoners. We do not support the UK government's use of Piwik to spy on its citizens. We do not support Israel's bi-annual bombing of Gaza, nor Hamas' acts of terrorism. We support no act of violence or oppression.

There is only one thing Piwik supports: **peace**. We hope you will use Piwik to further the presence of peace in the world and we hope you too will stand up against any inustice you see.

"The thing that we need in the world today is a group of men and women who will stand up for right and to be opposed to wrong, wherever it is. A group of people who have come to see that some things are wrong, whether they're never caught up with. And some things are right, whether nobody sees you doing them or not." - Martin Luther King Jr

**Comment by alexanderververis** [comment]
I get your stance completely (as a person living in China and having been to Tibet), however, let me point out that most businesses (I have worked with) do not recognize Tibet as a sovereign nation officially (simply because doing so would put them in bad graces with China).

The above does not mean I don't respect your wishes, please do as you see fit.

**Comment by wpic2012** [comment]
Actually, please return Tibet to China in your map.  You basically have made your product unusable in China because of your overtly political stance that IMHO does not belong in open source.    The HR abuses in Israel are as grave if not worse yet you don't hack the map up in the middle east.    No company or corporation separates Tibet from China.  Traffic, sales and leads are all counted as coming from China, so all you do is add work for the people using Piwik who now need to carefully check the map and add up the totals.

**Comment by mattab** [comment]
> The HR abuses in Israel are as grave if not worse yet 

I could not agree more with that :+1:

**Comment by imlonghao** [comment]
I am very angry to see what HR said.
It's totally wrong but HR didn't realize it.
I have deleted Piwik from my server and noticed my friends who want to or used Piwik about this issue.
I hope Piwik can reopen this issue and change their wrong political position.


imlonghao

**Comment by mattab** [comment]
Hi @imlonghao 

if you don't want to see Tibet on the Map, you can just DEACTIVATE the UserCountryMap plugin. Problem will be solved.  :+1:

**Comment by zaizai0935** [comment]
Tibet belongs to china. The living standard of the people in Tibet has been greatly improved. If you have a chance, please go to Tibet to have a look. Seeing is believing, not believing in false propaganda.

**Comment by zaizai0935** [comment]
@mattab 
Tibet belongs to china. The living standard of the people in Tibet has been greatly improved. If you have a chance, please go to Tibet to have a look. Seeing is believing, not believing in false propaganda.

**Comment by kuangrenfengyu** [comment]
Tibet and Taiwan belongs to China is a international consensus. This is not a joke. It is serious diplomatic events.

**Comment by joewulf** [comment]
mattab you're free to eat shit

**Comment by jamesjieye** [comment]
@mattab, you should make California, as well as most of the west part of the United States of America as independent countries. They were invaded too!!

I've deleted piwik from my servers and informed my friends that piwiki should not be used until this issue has been resolved.

**Comment by DeanZhixuzhe** [comment]
@mattab ，照这样的逻辑，美国都是中国的一个省而已，其他的就无所谓了！在我们地图中，只有美国省！

**Comment by zaizai0935** [comment]
@mattab 
I can not believe you still insist on Tibetan independence and Taiwan independence. This is really a disgusting point of view. You fucking asshole.

**Comment by forging2012** [comment]
强烈抗议！

**Comment by Tokyliu** [comment]
> Hi @imlonghao
> 
> if you don't want to see Tibet on the Map, you can just DEACTIVATE the UserCountryMap plugin. Problem will be solved. 👍

mother fuck
