### ISSUE TITLE
PECL getting marked as "not installed"

### ISSUE THREAD

**Issue by aequasi** [piwik/piwik#6998]
I installed geoip through pecl, exactly how the instructions say to do it, but i can't seem to use it on the UI

![image](http://content.screencast.com/users/aequasi/folders/Jing/media/4f537fa8-7db9-462d-a05a-1ccba6493dcf/00000220.png)

Is something not right?

**Comment by diosmosis** [comment]
Is it being loaded in your php fpm or cgi's php.ini?

**Comment by aequasi** [comment]
i've put it in both `fpm/php.ini` and `cli/php.ini`

i've also tried in `/etc/php5/mods-enabled/geoip.ini`

**Comment by diosmosis** [comment]
Just to make sure, you restarted php-fpm after editing the INI config right?

Piwik detects the PECL extension by looking for the `geoip_db_avail()` function. If it says it's not installed, the function must not exist for some reason.

**Comment by aequasi** [comment]
yup, restarted several times... not sure why its not showing up as installed.

**Comment by aequasi** [comment]
That function definitely doesn't exist though, ill close this out

**Comment by diosmosis** [comment]
Can you check what the result of `echo (int)function_exists('geoip_db_avail');` is when executed by cli and from php-fpm? Don't add the code to Piwik since you already know it doesn't show up there. Looking at the output of phpinfo() may also help you find the problem. Other than that though, I don't think there's much else I can suggest.

This looks like a server configuration issue, so I'm closing for now. If you find it's caused by a problem in Piwik, feel free to re-open.
