### ISSUE TITLE
trackPageView with a parameter forces avg_time_on_page to 1s

### ISSUE THREAD

**Issue by ondc** [piwik/piwik#7027]
See http://stackoverflow.com/questions/27899717/piwik-trackpageview-2-different-results

There are 2 different result on the `trackPageView` function. The difference occurs when using a variable in the callback.

```javascript
_paq.push(['trackPageView','Variable']);
```

The variable `avg_time_on_page` is always 1 sec.

```javascript
_paq.push(['trackPageView']);
```

Without arguments the `avg_time_on_page` value is correct.

**Comment by ondc** [comment]
thanks for following up

**Comment by mattab** [comment]
@mnapoli could you reproduce this issue? because i couldn't...

**Comment by bglxx** [comment]
after update to 2.11.0 we have the same problem:

on dashboard all avg_time_on_page is 2 sec back to start of project in 2013

when you are clicking on "Visitors" you will see in the lower part "Report"
the small graph "2 mis 15s average visit duration" and when you clicking on
that graph, you will see the "Evolution over the period" in the upper part
- but now with all visits at 2 sec since project start

2015-02-19 4:35 GMT+01:00 Matthieu Aubry <notifications@github.com>:

**Comment by mattab** [comment]
can you try to reproduce this issue in a new site with a simple HTML page, and post here the steps? if we can reproduce for sure we'll fix it. thanks

**Comment by bglxx** [comment]
okay, i will reproduce it within the next hour and give you the reply.

**Comment by bglxx** [comment]
same result:

![err_04](https://cloud.githubusercontent.com/assets/8326945/6264140/fcf3b1bc-b820-11e4-80f7-a86e40e30504.jpg)
I've added a new website to a subdirectory, changed the domain name and result is the same. look here
![err_05](https://cloud.githubusercontent.com/assets/8326945/6264179/54490fe8-b821-11e4-92f3-dbd3ddda9515.jpg)

**Comment by bglxx** [comment]
I've opened a new bug about 2 hrs ago because this bug influences not only average time on site. I've seen also influences to unique visitors line in graph, but this depends on the graph period settings

**Comment by mattab** [comment]
Ok let's follow up in #7247 - please comment in this issue if you have the same bug: #7247
