### ISSUE TITLE
Show Tracking Code Generator / Notification as long as no visit for a website is tracked

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7087]
Imagine you're logging into Piwik the first time after installing it (or on the Cloud) and you wonder what to do now and how to track visits. During the installation it already says "Insert Tracking Code ..." but honestly I doubt many are actually doing it directly. If you don't do it, you're lost afterwards as it is rather hard to find Tracking Code generator. Especially when you don't even know what you're looking for.

I propose to display the Tracking Code or a notification that explains what is to do until the first visit was tracked in `Dashboard` page (not in the actual dashboard although we could display the tracking code in a dashboard widget and a notification on top).

If there is still no visit after 7 days we could also send an email as a reminder including the tracking code (if we are legally allowed to send such email)

**Comment by mnapoli** [comment]
:+1: awesome idea

Instead of showing that in the dashboard page (as a notification or whatever) could it make sense instead to have a whole page dedicated to it where we are redirected (like when not logged in) as long as there are no visits?

I'm imagining we could show the tracking code, but also additional instructions (if there are) and troubleshooting links to FAQs?

**Comment by mattab** [comment]
Great idea!

**Comment by mnapoli** [comment]
Do you guys see a way to know if a website has no visits yet? Simply query the table (on every request…)?

**Comment by tsteur** [comment]
It maybe wouldn't be on every request, maybe it would be enough to query a report when loading `CoreHome.index`

**Comment by mnapoli** [comment]
See #7365
