### ISSUE TITLE
New label for issues: plugin and core

### ISSUE THREAD

**Issue by ThaDafinser** [piwik/piwik#7109]
Good would be the following 2 new labels: plugin and core.

So you can check what idead are around for new plugins. And core things are normally harder things, since you need to check many deps.

**Comment by tsteur** [comment]
Not sure about this. Sometimes it is even hard to tell in advance whether it is plugin or core related. Also code wise the core / plugins are not 100% separated. Meaning sometimes core accesses a plugin directly etc which is bad. Also the term `core` is a bit confusing since developers would understand everything below `/core` but here in the Team we usually consider `/plugins` + `/core` as "core". @mattab  We need to change the wording that we use for `/plugins` and `/core`. Otherwise it will be always confusing, I noticed this a few times. 

We could use a `new plugin` label for features that we would like to solve in a new plugin. Maybe this is what you meant? One downside is that we often have to add new features to core to be able to solve something in a new plugin. So we should use it maybe only when we are certain that it can be already solved in a plugin. It could be nice to have this label beside the `Easy pick` label.

> core things are normally harder 

Or are you maybe interested in a separation of issues into easy and hard? We already have an `easy-pick` but this one contains usually only very easy ones.

**Comment by ThaDafinser** [comment]
Easy/hard is also no bad thing...i wrote not a few plugins and know a bit about core/internal of Piwik, but not that deep always.

So as a contributor i think its a lot easier to write a simple plugin for a missing feature. There is good developer documentation to get started.

So if u can filter issues which can be solved with a plugin its good to get started?

**Comment by tsteur** [comment]
Good point! We sometimes do have the case that things could and should be resolved in plugins. Created a new label: `c: New plugin`. 
FYI @mattab
