### ISSUE TITLE
issues updating from 2.8.3 using Composer

### ISSUE THREAD

**Issue by craue** [piwik/piwik#7179]
I'm using Composer for a project which only requires Piwik as a dependency, so my `composer.json` looks like this:
```json
{
	"type": "project",
	"require": {
		"piwik/piwik": "~2.0"
	}
}
```

As Piwik 2.8.3 is the last tag with only stable dependencies, there are some issues while trying to update to 2.9.0 (which requires `"mnapoli/php-di": "5.0.x-dev"`) or 2.10.0 (which also requires `"doctrine/cache": "dev-filecache-race-condition-fix as 1.3.1"`).

We have two issues here:
 1. Because the [minimum-stability setting](https://getcomposer.org/doc/04-schema.md#minimum-stability) defaults to `stable`, no stable version for the `5.0.x-dev` branch of `mnapoli/php-di` can be found and Composer complains with `piwik/piwik 2.9.0 requires mnapoli/php-di 5.0.x-dev -> no matching package found`. The commit which introduced this is f5b6b4ccb021a3b082e578fc9a42c715985d1fae. The solution would be to tag a stable release. /cc @mnapoli
 2. [Inline aliases](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias) don't work well in published packages and using them should be avoided. The commit which introduced this is 41a0e0df6c642b8ddf90f2ea0972418dd89e7e16. The solution would be to fix the issue (which the custom branch is addressing) upstream and require a proper version of `doctrine/cache`. (Or is it already solved in 1.4.0?)

To successfully update my project to Piwik 2.10.0 while having these two issues I would need to change my `composer.json` to this, which is definitely bad:
```json
{
	"type": "project",
	"require": {
		"piwik/piwik": "~2.0",
		"doctrine/cache": "dev-filecache-race-condition-fix as 1.3.1"
	},
	"minimum-stability": "dev",
	"prefer-stable": true,
	"repositories": [
		{
			"type": "git",
			"url": "https://github.com/piwik/cache.git"
		}
	]
}
```

Would be nice if both issues could be solved prior to releasing Piwik 2.11.0.

**Comment by mnapoli** [comment]
1. Impossible to tag a new release unfortunately (the v5 is not finished), and I guess a beta wouldn't change much. Using `minimum-stability` isn't possible?
2. [1.4.0](https://github.com/doctrine/cache/releases/tag/v1.4.0) contains the fix so we could solve this one

**Comment by craue** [comment]
Maybe requiring `"mnapoli/php-di": "~5.0@dev"` instead would solve the issue, but I don't know for sure and it's still bad to rely on an unstable dependency.

**Comment by mnapoli** [comment]
`~5.0@dev` wouldn't work because it doesn't apply to the root `composer.json`, `minimum-stability` is the only solution.

It's not an unstable dependency in the sense that it's completely controlled with each update (I maintain PHP-DI). It's kind like a rolling release, except we have the liberty to break BC because only Piwik is using it (+ some of my projects). The goal is to develop 5.0 while confronting the choices made to real-life scenarios in Piwik and being able to adjust and break BC when we want (that's why 5.0 is not tagged yet). In a few months (maybe next release) 5.0 should be tagged.

**Comment by craue** [comment]
> only Piwik is using it (+ some of my projects)

How can you know? :smirk:

But solving the `doctrine/cache` dependency issue would be a good start. Will you change that or shall I create a PR?

**Comment by mnapoli** [comment]
I'll fix the doctrine requirement.

> How can you know? :smirk:

Of course anybody can use it ;) but for them it's "unstable". For Piwik it's not because I update Piwik as soon as I update PHP-DI, it's like a joint development, like if PHP-DI 5 was an "internal" fork. Anybody could use it, but there's no guarantee of anything for them.

**Comment by mnapoli** [comment]
Forgot to reference the commit, here it is: f82a2d45df0a365ea40dead55123fad96452ab26!
