### ISSUE TITLE
Save User ID in cookie

### ISSUE THREAD

**Issue by druidajes** [piwik/piwik#7286]
Save userid in the cookie and use SetUserId well the first time.

This can be useful for visitors from emailing, which comes to my site through a link in this way.

http://www.example.com/?email=xxxxxxx@example.com 

But in subsequent visits have not said userid, but if you have saved in the cookie can track more useful.

**Comment by mattab** [comment]
Thanks @druidajes for the suggestion, it would be a nice new feature to have. If we implement such change it would change how User ID works, so we'd have to think about it in detail and upgrade [User ID](http://piwik.org/docs/user-id/) user guide accordingly. Maybe it could be opt-in so that only people who really need to persist User ID in cookies would turn it on.

**Comment by davidgorges** [comment]
I think this feature would be great. Right now, it's a little confusing: Visitors might be recognized as a returning visitor, but not as a returning user.

**Comment by mattab** [comment]
This duplicates https://github.com/piwik/piwik/issues/6171 
Please watch the other issue to get updates
