### ISSUE TITLE
addEcommerceItem tracks only last item with same sku

### ISSUE THREAD

**Issue by 242bpm** [piwik/piwik#7321]
In case you sell customizable (custom-made) goods, addEcommerceItem tracks only the last item.

Example:
// jalousie - 82x181cm, color: silver, remote control: yes
_paq.push(['addEcommerceItem',"1143", "jalousie", "", 196.55, 1]);
// jalousie - 83.5x181cm, color: silver, remote control: no
_paq.push(['addEcommerceItem',"1143", "jalousie", "", 75.20, 1]);

In this case only the last item gets tracked.

**Comment by mattab** [comment]
Hi @242bpm Thanks for the report. This is not a bug but it is by design that in Piwik [Ecommerce tracking](http://piwik.org/docs/ecommerce-analytics/) the Product SKU (the first parameter to `addEcommerceItem` is the unique key for the product. Therefore if you sell custom made product, please append to the SKU an identifier so that the SKU is different for  each custom made product.
