### ISSUE TITLE
Dashboard Undefined index: nb_users

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#7359]
Notice: Undefined index: nb_users in /kunden/wesleyhb.de/webseiten/marquardt/wp/wp-content/plugins/wp-piwik/dashboard/overview.php on line 35

see screenshot on multisite with wp-piwik installed deactived globally, only activated on each site.
http://awesomescreenshot.com/04d4jnywa7

**Comment by mattab** [comment]
Hi @Tobias-Conrad 

I believe it's a bug report more suited for the WP-Piwik plugin, because it can happen that Piwik API does not return the `nb_users` information. This was changed in https://github.com/piwik/piwik/issues/6705 and unfortunately we forgot to document this in the developer changelog. So please send this information to André who created the great WP-Piwik plugin. Thanks!
