### ISSUE TITLE
% of user with Cookie can be more than 100%

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7437]
The goal of this issue is to fix the bug where the "% visits with Cookie support" sometimes shows more than 100%. this can be seen [in the demo here](http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#/module=UserSettings&action=index&idSite=7&period=day&date=yesterday).

![cookie 103 percent](https://cloud.githubusercontent.com/assets/466765/6660321/7a078c12-cbfb-11e4-8a01-301d2310d2b7.png)

**Comment by mnapoli** [comment]
The `piwik.js` tracker will not detect plugins on IE because "it is not supported".

```js
if (!((new RegExp('MSIE')).test(navigatorAlias.userAgent))) {
    if (navigatorAlias.mimeTypes && navigatorAlias.mimeTypes.length) {
        // ... look in navigator.mimeTypes
    }

    ...

    // other browser features
    browserFeatures.cookie = hasCookies();
}
```

full code here: https://github.com/piwik/piwik/blob/master/js/piwik.js#L3996-4022

However [IE 11 does not report itself as `MSIE` user agent anymore](http://stackoverflow.com/a/17907562/245552) which means it will go into this branch of code, so it will report for example if the browser supports cookie. I don't think it will report for other plugins yet but it could happen in the future.

Anyway now the problem is that we have IE11 cookies stats recorded. But in the "Plugins" report we do this:

```php
$visitsSum = $visitsSumTotal - $ieVisits;
```

full code here: https://github.com/piwik/piwik/blob/master/plugins/DevicePlugins/API.php#L77-77

Which means we calculate the percentage over all the visits that are not IE (but IE 11 did report cookie usage). Which leads to a total greater than 100%…

I don't see a perfect way to fix this, here are options:

- do not ignore IE visits when calculating the percentage: however this leads to % that could be wrong (e.g. 95% support for cookies could actually be 100% in reality)
- hack to ignore IE < 11 visits: cookies % would be fixed but for other plugins we don't have stats for IE 11 so we still have wrong % for them…
- even more hacky stuff to ignore IE < 11 visits for cookie % but ignore all IE visits for the rest of the rows: in the future if IE support improves then we will get the same problem again
- just replace any % > 100 to 100: quick and dirty, destroys the value of the report, but that's a possibility
- change `piwik.js` to differentiate between "not supported" and "unknown": that way we can have realistic %

I think the last solution is the best as it would also allow to have realistic % for any other browser that doesn't support getting supported plugins. It would also allow to show 2 percentages: the % for visits that were correctly detected and the % for all the visits (e.g. 80% browsers support Java but it's 50% in total if we include visits where we can't detect the feature). However it requires changing the tracker, and it wouldn't be backward compatible with data previously recorded.

@mattab @sgiehl do you see any other solution, or do you have a preference with the one I exposed?

**Comment by mattab** [comment]
Good find... it's a tricky one to decide the best way forward.

> for other plugins we don't have stats for IE 11 so we still have wrong % for them…

does the plugin detection start working for IE11 as well as the cookie detection? (it uses different JS code (cookes detected with `navigator.cookieEnabled` while plugins detected looking at `navigator.mimeTypes`)

**Comment by mnapoli** [comment]
No I don't think so because on MSDN they still show that `navigator.mimeTypes` is not supported. However that may change in the future of course.

**Comment by mnapoli** [comment]
Pull request here: #7469
