### ISSUE TITLE
New design for Updater screen

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7450]
The goal of this issue is to refresh the design of the Piwik updater screens.

Here is an example of the new design for the "Piwik updated" screen:

![piwik-update](https://cloud.githubusercontent.com/assets/466765/6677406/8655684c-cc94-11e4-8501-636067c9b72c.png)

We should also use this same design for the other Update screens to be consistent with this, ie.
 * Welcome: https://github.com/piwik/piwik-ui-tests/blob/master/CoreUpdaterCode_newVersion.png
 * Auto update progress: https://github.com/piwik/piwik-ui-tests/blob/master/CoreUpdaterCode_httpUpdateSuccess.png
 * HTTPs Upgrade failed: https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/CoreUpdaterCode_httpsUpdateFail.png
 * DB Upgrade required: https://github.com/piwik/piwik-ui-tests/blob/master/CoreUpdaterDb_main.png
 * Piwik upgraded (screenshot above)

**Comment by mattab** [comment]
This new design was proposed for the updater:

![piwik-update-warn](https://cloud.githubusercontent.com/assets/466765/6698873/b7c61958-cd61-11e4-9015-e8824cfec90a.png)

if you have any feedback please comment

**Comment by mnapoli** [comment]
Looks awesome, definitely an improvement over the current situation.

**Comment by gaumondp** [comment]
As long as we get the warning while in command line too I'm ok with this.

I know we can't predict the duration because it's quite variable from one
server to another but maybe a check on the Piwik DB size would help produce
some kind of message like "Considering the size (14 GB) of your database,
it could take more than 30 minutes to upgrade"

In my case, my latest upgrade (2.7 to 2.11) took 36 minutes with 14 GB of
data.

2015-03-17 19:07 GMT-04:00 Matthieu Napoli <notifications@github.com>:

**Comment by mnapoli** [comment]
PR: #7578
