### ISSUE TITLE
Wrong tooltip for Live visitors button

### ISSUE THREAD

**Issue by mnlipp** [piwik/piwik#7474]
The live visitors button is a combined state/action button. I know that this kind of buttons cannot be done right, because some people associate the current state with the icon while others associate the possible action with the icon (we once hat that in a project for phone take off/hang up and changed the semantics at least a dozen times, depending on whom we talked to last at the customer).

Piwik has chosen the "action" approach. So when live tracking has been started, the button shows the pause icon, because clicking the button (the action) pauses live tracking. (This is contrary to your favourite smart phone MP3 player, right? It will show the run icon when it's playing and the pause icon when it's paused.) You can do this, of course.

The problem is that the tooltips are wrong. When the pause icon is shown, the tooltip is "Start Live!", but when you click on the icon it will actually *stop* live. When the "Running" icon is shown, the tooltip is "Pause Live!", but clicking will actually *start* live.

**Comment by mattab** [comment]
Thanks @mnlipp for the report. If the tooltip are wrong, this will be an easy fix we'll take a look

**Comment by saleemkce** [comment]
This type of ON/OFF or change state actions could be quite confusing. I once talked about this with a group of people and asked them to tell in what state the application is (pointing to the ON/OFF) options. Some of them gave right answers, others wrong and yet others got confused to talk what it was about. So, when implementing such morden UI, the user should be better taught about the states. 
Instead of tool-tipping "ON" or "OFF". The tool tip denoting 'currently turned ON' or "currently turned OFF" when hovering, which would give better understanding from user perspective. It's just a suggestion!

**Comment by mnlipp** [comment]
How about combining state and action in the tooltip: "Live! tracking is started. Click to stop" (and "Live! tracking is stopped. Click to start".

**Comment by saleemkce** [comment]
Sure, that would be clearer and nice.
