### ISSUE TITLE
Video Analytics - Measure videos and media players

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7551]
The goal of this issue is to create and release on the Marketplace a new plugin that lets anyone track how Videos players are used. 

For example this plugin will include:
 * Events tracked: `Started, Paused, Ended`
 * How much of each video was viewed: ` 5%, 10%, 25%, 50%, 75%, 95%`
 * Support automatically players, for example: HTML5 Videos, JW player, Videojs, FlowPlayer, Youtube
 * we will keep the first version to minimal feature sets (MVP)

 
Feel free to comment with any suggestion or wishlist!

**Comment by Tobias-Conrad** [comment]
i am used to this nice tracking software before i moved to piwik.
they done it very user friendly, easy. they included video/audio tracking in the code.
this code is loading when it see audio and video on the website.
http://clicky.com/help/media
http://clicky.com/blog/313/tracking-youtube-videos-no-longer-requires-phd

**Comment by Tobias-Conrad** [comment]
more further, create a javascript tracking code (will be the normal piwik tracking code) which track, video, audio, pictures in lightbox, ecommerce, ... and loads the needed scripts for each media from tracking host. 
it is possible clicky.com does this.
http://clicky.com/blog/330/html5-audio-embedded-actions-tracking-code-verification-and-better-cookies
HTML5 audio, and automatic HTML5 video/audio tracking
We've had support for HTML5 video tracking for a while, it simply required adding an additional javascript file to your code. This month we just added the ability to track audio as well. We combined video and audio together into their own report, now called "Media", since they are quite similar in terms of the metrics we track -- and it's unlikely that many sites will have a mix of both.

Even better, we made it so you no longer need to include the extra javascript file at all. When the tracking code detects any video or audio elements on your web site, it will now automatically inject the other javascript file into your page so we can track the video and audio files without you having to do anything. Don't worry, if you already had that file included manually, you don't need to delete it. It will work either way.

->> less extra code, plugins, code snippets (i am and normal user not used to)
->> more open for the public, insert one tracking code and track all media
->> update proved, simple tracking code which reloads missing scripts from tracking host. 
       only host=piwik needs to be updated.

**Comment by geromefreeman** [comment]
I request we add the Wistia player to this as well! 

I am willing to help with coding this plugin too. Has any progress been made thus far?

**Comment by Tobias-Conrad** [comment]
just do it. why not finished?

**Comment by Forsskieken** [comment]
Hi There,

Is this plugin released ?

**Comment by mattab** [comment]
Hi guys, we will release this plugin in coming weeks. Stay tuned on #9265

**Comment by nerbix** [comment]
Hey All, 

Was this plugin released?

**Comment by tsteur** [comment]
We now have a Media Analytics plugin that tracks Videos & Audio.

More information is available here: http://www.media-analytics.net/ The plugin gives useful insights into media / video / audio analytics and adds many new reports, widgets and segments to Piwik.

Works with HTML5 video & audio, Vimeo and YouTube out of the box. Support for other players can be added easily and is documented in the [developer docs](https://developer.piwik.org/guides/media-analytics). We are also happy to add support for more players upon request, please [ping us](https://www.media-analytics.net/#contact). After installation the plugin will in most cases directly start tracking data see the [setup](https://developer.piwik.org/guides/media-analytics/setup) guide

**Comment by tsteur** [comment]
For a full list of features check out https://plugins.piwik.org/MediaAnalytics , [FAQ](https://piwik.org/faq/media-analytics/), [User Guide](https://piwik.org/docs/media-analytics/), [Developer docs](http://developer.piwik.org/guides/media-analytics)
