### ISSUE TITLE
New design for Marketplace (in Administration)

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7586]
The goal of this issue is to change the design of how Plugins are listed within the Piwik platform, to be more consistent with the existing [Marketplace design](http://plugins.piwik.org/)

## Current Marketplace design

![marketplace](https://cloud.githubusercontent.com/assets/466765/6912132/e9b04c34-d7c7-11e4-9bc0-cc7d671bf484.png)

## New proposed Marketplace design

![marketplace-new](https://cloud.githubusercontent.com/assets/466765/6912165/3a2d40f4-d7c8-11e4-9e51-a9172667f381.png)

Notes:
 * in design the Developer is not displayed in the listing of plugins. it's important information and we should still list the developer name.
 * the title, description, sort links and search bar should still be displayed at the top somehow

(I'll ask designers if possible to get updated mockup)

**Comment by gaumondp** [comment]
Would be great to have "Popular/newest/search" on the website too !

**Comment by mattab** [comment]
We need to ask designers how do we display notices per-plugin such as those two:

![displaying notices](https://cloud.githubusercontent.com/assets/466765/7221922/e24cba62-e754-11e4-9386-a2f20390a8ef.png)

**Comment by lemu** [comment]
![marketplace](https://cloud.githubusercontent.com/assets/590637/7231783/e76eca4e-e777-11e4-8ac9-873e39a3189b.png)

**Comment by mattab** [comment]
@lemu I think it looks really nice!  :+1:  maybe others will have some feedback

**Comment by mnapoli** [comment]
I'm halfway through this, a few things:

- the buttons will be `Install` instead of `Download plugin` (because it's not about downloading the plugins), I think it's the correct thing right?
- I've limited the plugin descriptions to maximum 3 lines in the plugin list (we can read more in the "Plugin details" popup): that solves the problem of having all blocks keep the same height in a much better way (plus it's responsive)
- currently clicking *anywhere* on a plugin block will open the "Plugin details" popup (well except if we click on "Install"): I want to change that because it's really confusing:
    - the popup should open only when clicking on a link, e.g. the name of the plugin and the "> more" link

We will need to find a solution for this:

![](https://cloud.githubusercontent.com/assets/466765/7221922/e24cba62-e754-11e4-9386-a2f20390a8ef.png)

My suggestion is to show the warning message only in the popup. In the plugin list we could make the "Install" button disabled for example, or more explicit "Cannot install"? We could also replace the button with text, for example:

![capture d ecran 2015-04-27 a 17 12 04](https://cloud.githubusercontent.com/assets/720328/7341998/96580dc6-ed00-11e4-8c61-995201acb42f.png)

That way it's different from the red "Install" buttons, we can see straightaway we can't install it, yet the fact that it's a link suggests that we can get more info by clicking on it.

**Comment by mattab** [comment]
>    the popup should open only when clicking on a link, e.g. the name of the plugin and the "> more" link

Ok, small note: maybe you can make the whole "title block" open the popover on click, instead of just linking the text (which requires more precision when clicking)

> My suggestion is to show the warning message only in the popup. In the plugin list we could make the "Install" button disabled for example, or more explicit "Cannot install"? We could also replace the button with text, for example:

Sounds good to me, maybe `Cannot install (help)` to make it clear the explanation is available on click?

**Comment by tsteur** [comment]
I find the design quite "heavy". Maybe it is possible to find a solution with less lines and borders? Also I find it a bit confusing that the buttons "Plugins/Themes" and "Popular/Newest/Alpha" are displayed similar and next to each other.
