### ISSUE TITLE
New design for Maintenance mode 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7620]
Feedback from @quba - the maintenance mode is not very usable. 

 * Let's review the design (maybe we ask designers)
 * review the copy to make it non-technical and user friendly

Current design:

![capture d ecran 2015-04-06 a 10 37 57](https://cloud.githubusercontent.com/assets/720328/6998993/05db2a20-dc49-11e4-8853-a146f3f87f12.png)

**Comment by Globulopolis** [comment]
At least we need to remove message about how to disable this mode. And remove `Go Back` and `Go to Piwik` links as it not necessary on this page. Imho

**Comment by mnapoli** [comment]
Currently the maintenance mode simply throws an exception, so the page displayed is the exception page.

In #7578 (redesign of the updater) I applied the same redesign to the exception page because it was using the same layout. Here is how the new exception look (compare with the current design above):

![](https://cloud.githubusercontent.com/assets/720328/6956916/1966f3d0-d951-11e4-8dd9-39b6b11e16c8.png)

(the stack trace will not be shown for users)

We might want to move away from the exception page and have a dedicated page. We can still keep the same design in order to be consistent, but we could discuss the text that are shown on the page?

For example:

- title: "Piwik is undergoing maintenance"
- text: "Piwik is in scheduled maintenance, please come back later." (or something else?)
- no other link (e.g. no link "Back to Piwik")

What else would you see on this page?

**Comment by mattab** [comment]
Feedback:

> We might want to move away from the exception page and have a dedicated page. 

(it would be easier to maintain if we didn't use dedicated page)

> no other link 

 * for the maintenance mode error screen: +1 to remove all links
 * but we still want to show the links when the other exceptions/errors are displayed

> title: "Piwik is undergoing maintenance"

+1

>  text: "Piwik is in scheduled maintenance, please come back later." (or something else?)

Maybe: `We are busy updating Piwik and will be back up and running again before long, so please try again soon. Please note that your analytics data will continue to be tracked as normal. Thanks for your patience!`

**Comment by mnapoli** [comment]
> it would be easier to maintain if we didn't use dedicated page

I don't think it's a good solution to make the exception page generic and customizable just for this. It will make the exception page a mess and make it much harder to maintain.

Here we only want to keep the layout, but replace entirely the content. There will be nothing in common with the exception page except for the borders and background colors (as you described in your comment). We have CSS classes and Twig layouts for that, it will not be hard to maintain at all but rather the opposite.

**Comment by mattab** [comment]
ok this makes sense!

**Comment by quba** [comment]
@mattab I think that we shouldn't assume, that Piwik will be in maintenance mode only during update process. This message should be more generic.

**Comment by mattab** [comment]
good point, maybe simply `We will be back up and running again before long, so please try again soon. Please note that your analytics data will continue to be tracked as normal. Thanks for your patience!

**Comment by mnapoli** [comment]
Current WIP:

![capture d ecran 2015-04-09 a 13 41 29](https://cloud.githubusercontent.com/assets/720328/7059027/294b107a-debe-11e4-9b76-81119838ead2.png)

There's not much to say in that page so it feels a bit empty…

**Comment by mnapoli** [comment]
PR: #7648
