### ISSUE TITLE
Manage Goals shows "Create a new goal" when not having enough permission

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7836]
On demo.piwik.org when clicking on Goals => Manage Goals this is what I see:

![manage_goals](https://cloud.githubusercontent.com/assets/273120/7467172/2e0f2000-f346-11e4-8c93-1565dce0248a.png)

Instead I would expect to see a title "Manage Goals" and instead of the description saying "...can add Goals for a given website..." I would expect something with "... manage goals ...". 

Moving it to short term as this is happening for anonymous users on demo.piwik.org (potential new users) and it might give them a bit of a negative (buggy) impression.

**Comment by mattab** [comment]
:+1: 

Expected:
 * "Manage Goals" title instead of "Create a new Goal" 
 * instead of the description saying "...can add Goals for a given website..." I would expect something with "... manage goals ...". 
 * when a user has permission to `view` the website, but does not have `admin` permission, then "Manage goals" should still show the list of Goals (but without the Edit/Delete buttons). It's very useful to see the Goal definitions even when not able to modify them or add new goals.
