### ISSUE TITLE
On updates, the version number is not updated when manually executing the SQL queries

### ISSUE THREAD

**Issue by larsen0815** [piwik/piwik#7840]
I prefer to manually execute the SQL queries that are needed when Piwik is updated. This gives me better control of what happens and when errors occur.

With the update to 2.13.0, I noticed that the version number is not updated, when I copy the SQL queries that Piwik shows on the page "a database update is needed". Because of this, even after I have executed all needed queries, Piwik still shows a message that the DB needs to be updated.

I had to manually execute "UPDATE piwik_option SET option_value = '2.13.0' WHERE option_name = 'version_core'" to fix this. This needs to be included in the SQL queries that Piwik presents for copy&paste.

**Comment by tsteur** [comment]
Thx for the report! I can reproduce this. I would have expected to see this query in the UI but it was not listed. I'm pretty sure it used to be case. 

![update_no_version](https://cloud.githubusercontent.com/assets/273120/7483466/53cf206e-f3d3-11e4-8494-771aa9699d97.png)

**Comment by mattab** [comment]
This is by design that the last SQL query updating the version is not displayed. 

Why? It was removed to prevent a bug. If you execute this SQL query then Piwik will believe it was already upgraded and  will  skip any non-sql  updates. Sometimes we activate plugins during upgrades and we don't want to skip this, so even though you manually upgrade SQL you still have to click in the UI or run `./console core:update` to finish the upgrade.

**Comment by tsteur** [comment]
Maybe this should be explained somewhere? Otherwise it ends up like in this case that users update the version manually

**Comment by mattab** [comment]
I guess it matters only for users who used to see the last query and now don't see it. I guess it's a small number of users and not worth explaining this to all users (also I wouldn't know how to explain this clearly)

**Comment by tsteur** [comment]
How do we know a user inserted the SQL queries manually? Do we execute them all again?

**Comment by mattab** [comment]
Yes we do run the SQL queries again, and if they were already executed they will be ignored due to the error code set with the SQL query. It's a bit fragile and it would be better to remember which SQL query was executed but so far it's how it's done.

**Comment by tsteur** [comment]
It is quite a bit fragile. Do we have tests for this? I doubt so. 

Since we sometimes also ADD values, eg an option etc this can even result in duplicate values etc. It is also likely that someone (a core developer or a plugin developer) forgets this use case (plugin developers can't know about that) and it results in errors that are hard to debug / explain etc.

One more reason to refactor the updater in #5985 

How can we improve that?

**Comment by mattab** [comment]
> How can we improve that?

refactor the updater in #5985 ? :sunglasses:

**Comment by tsteur** [comment]
OK :)

**Comment by mattab** [comment]
See #5985
