### ISSUE TITLE
All Websites dashboard shows only the first 50 websites

### ISSUE THREAD

**Issue by twodrunkbots** [piwik/piwik#7854]
Hi

After the update from 2.12.1 to 2.13.0, the All Websites dashboard shows only the first 50 websites. 
I have updated to 2.13.1 this morning and it's still the same:
If I click on "next" the dashboard shows nothing. (It should show the websites 50-99)

![2mcecek](https://cloud.githubusercontent.com/assets/11195517/7510016/14bb58a0-f498-11e4-9e52-7b1598433385.jpg)

After some research I think I found the bug. Or, not the bug itself, but where the bug is:
In the controller of the MultiSites plugin i changed the following line:

Line 56: `$limit   = Common::getRequestVar('filter_limit', 0, 'int');`
to
Line 56: `$limit   = 200;`

And now the All Websites dashboard shows the first 200 websites.
So I think there is a problem with the GET parameter.

Have a nice day
Steven

**Comment by airandony** [comment]
Thanks you have fixed my problem !

**Comment by tsteur** [comment]
How many websites do you have in your installation? Which browser are you using?

Have you configured any value for `all_websites_website_per_page` or `site_selector_max_sites` in your `config/config.ini.php`?

**Comment by airandony** [comment]
I have 63 websites. I'm also using the WebsiteGroups (v0.1.3) plugin.
I'm using the new version of Firefox on Mac OS Yosemite
No, I didn't change anything in config.ini.php.

**Comment by tsteur** [comment]
Do you mind asking those questions? How many websites have you added to a group approx? And how many groups do you have approx?

Will help me to reproduce.

**Comment by airandony** [comment]
The problem is since the version 2.13.0. And we go on the second page, the second batch of websites is not showing up.
Here are a screenshot of my 13 groups and between 2 websites to 17.

![capture d ecran 2015-05-08 a 00 52 20](https://cloud.githubusercontent.com/assets/7909575/7530775/aa324342-f51c-11e4-85b8-f1c5c6a2986c.png)

![capture d ecran 2015-05-08 a 00 52 40](https://cloud.githubusercontent.com/assets/7909575/7530774/aa2e58c2-f51c-11e4-8230-0045a1942757.png)

**Comment by tsteur** [comment]
Thanks a lot, I can reproduce it!
