### ISSUE TITLE
Reorganize less variables for simpler theming

### ISSUE THREAD

**Issue by mnapoli** [piwik/piwik#7876]
Following a discussion in #7793 we want to expose a simple less file containing the base variables that themes can override. Those variables will be considered as API (no BC-break).

We still want to be able to create other less variables (for practical purposes) so we will put these other variables in a separate file, and those variables will not be API.

**Comment by mnapoli** [comment]
FYI this needs to be done after most of the "redesign" pull requests are merged to avoid any conflict.

**Comment by tsteur** [comment]
Just to clarify. In this issue can we move `@theme-color-background` and `@theme-color-code-background` to the not API file and let the colours default to `@color-silver-l30` and `@color-silver-l95`? Or remove the new variables and replace `@theme-color-background` with `@color-silver-l30` and `@theme-color-code-background` with `@color-silver-l95` (that's how we usually do it currently, but can be changed if needed)

**Comment by mnapoli** [comment]
Did you mean `@theme-color-code` instead of `@theme-color-background` in your comment? `@theme-color-background` is themable right?

**Comment by tsteur** [comment]
I meant where we currently use that variable in a less file instead of 

```
color: @theme-color-code-background
```

we could use 

```
color: @color-silver-l95
```

and remove the code less variable. That's how it's usually done *currently* in several places.

Alternatively we could at least do 
```
@theme-color-code-background: @color-silver-l95
```

Same with the other variable.

Different topic but can be maybe done in this issue as well: In general I would only put those variables in the `basic.less` or `simple.less` or whatever:
```
@theme-fontFamily-base: Verdana, sans-serif;
@theme-color-brand:                    @color-red-piwik;
@theme-color-brand-contrast:           @color-white;
@theme-color-text:                     @color-black-piwik;
@theme-color-text-light:               #444;
@theme-color-text-lighter:             @color-silver-l40;
@theme-color-link:                     @color-blue-piwik;

@theme-color-menu-contrast-text: @theme-color-text-lighter;
@theme-color-menu-contrast-textActive: @theme-color-text;
@theme-color-menu-contrast-background: @theme-color-background-tinyContrast;
@theme-color-widget-title-text: @theme-color-text;
@theme-color-widget-title-background: @theme-color-background-tinyContrast;
```

This will make it much easier and less frustrating for plugin developers since those variables don't really impact other things that one need to change. 
Eg I would remove all the background color variables in general (or move it to `advanced.less`). Once one starts to change the background color one kinda has to change so many other things to not make it look weird. It's a lot of work and quite hard. For example theming the background color and colors of the Map and some graphs become very hard, icons still have a white background (refs #7618). Meaning if we don't allow to change background color or put it in advanced, needing to change the code thing is basically not needed.

**Comment by mnapoli** [comment]
But the background color is the only thing we know is customized (the two currently published themes). If we speak only of what we know, then removing it wouldn't be such a good idea.

**Comment by tsteur** [comment]
It'd put it in a `advanced.less` or so. Most companies that use theming do very likely not change the background color but only adjust like the widget header, brand color, link color and maybe menu color to their CI. Such themes won't be public in the marketplace. 

This will make it easier for developers to get started since they will have only a few options and those are easy and one shouldn't get frustrated with those as they are straight forward. Knowing that eg background-color is in eg a `advanced.less` will maybe developers make clear there will be more work and it won't be easy etc. Just an idea...

**Comment by mnapoli** [comment]
OK makes sense.

**Comment by mnapoli** [comment]
PR: #7951

**Comment by mnapoli** [comment]
Developer documentation updated.
