### ISSUE TITLE
Organisation of \Piwik\Plugin\* classes

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#7929]
We currently have a couple of classes under `Piwik\Plugin\*` classes. Eg `Piwik\Plugin\Report`, `Piwik\Plugin\Widget`, `Piwik\Plugin\Controller`. We put there classes that can be extended by plugins to create new entities, eg Widgets, Reports, ...

It is quite nice to have all those classes under `Piwik\Plugin` and to see at a glance which classes can be extended and what kinda our main API's are. Though I'm not so sure if it's still the right way.

Eg where do we put Widget related classes such as `WidgetFactory` or `WidgetsList`. Under `Piwik\Plugin\Widget\Factory` and `Piwik\Plugin\Widget\WidgetsList`?

Or should we move `Piwik\Plugin\Widget` to `Piwik\Widget` and `Piwik\Widget\Factory` and `Piwik\Widget\WidgetsList`? Or mixed?  

We currently also have `Piwik\Db`, `Piwik\Url`, `Piwik\DataTable` and I reckon for plugin developers and for us it's maybe not clear where to find/put which class.

Any opinions / thoughts? 

With Piwik 3.0 we could break the API and maybe move those classes although it could be quite a bit of work, especially to also keep all of our plugins compatible.

**Comment by dczajkacc** [comment]
I would keep related classes together and in logical namespaces, e.g.:

Piwik\Widget\List - former WidgetsList
Piwik\Widget\Factory - former WidgetFactory
Piwik\Widget\Provider - former Widgets

**Comment by mgazdzik** [comment]
I think it would also make sense to distribute this by domain, as @dczajkacc wrote.

**Comment by mnapoli** [comment]
There's one thing I dislike with the `Piwik\Plugin\` namespace is that it's very easy to confuse with `Piwik\Plugins\`.

I would be +1 to move related things together as suggested, e.g. `Piwik\Widget\...`, `Piwik\Report\...`, etc.

> We currently also have Piwik\Db, Piwik\Url, Piwik\DataTable…

I honestly hate things in the root namespace ;) I would definitely be +1 to reorganize things in separate namespaces (e.g. `Piwik\Database\…`). Especially since we have the old ZF1/PEAR convention with `Piwik\Db` and the related classes in a subnamespace (`Piwik\Db\AdapterInterface`, …).

However there's one advantage to keep the current [not ideal] names: it allows us to refactor the component later and use the good name without breaking BC. For example with the scheduler the old class was `Piwik\TaskScheduler` (IIRC) and the new refactored class was `Piwik\TaskScheduler\TaskScheduler`. That allows to keep the old class with the old name as an adapter to the new class, which is very cool because then we can write the new class however we want.

> With Piwik 3.0 we could break the API and maybe move those classes although it could be quite a bit of work, especially to also keep all of our plugins compatible.

We can also set up class aliases or write subclasses to keep BC.

**Comment by tsteur** [comment]
> I honestly hate things in the root namespace ;)

That's a strong opinion :) I don't mind them there and find it can be even nice sometimes. I'd rather find `Piwik\Date\Date` or so not as nice when a shorter version (`Piwik\Date`) does it as well. A problem that I see with those classes is that they sometimes contain too many things and too many different things. Also there are some classes that rather belong into a different namespace maybe such as `Piwik\Cookie` could be under something like `Piwik\Http` etc. Saying there are cases where it's nice to have something under the root namespace but it's also nice to have all in one namespace.

How would we rename eg `Piwik\Plugin\Widget` under the `Widget` namespace? One suggestion was `Piwik\Widget\Provider` or basically `Piwik\Widget\WidgetProvider`. Any other ideas?

**Comment by mnapoli** [comment]
Hate maybe was a strong word rather "dislike" ;)

WidgetProvider could do but are we talking about the classes that plugins extend to define widgets? If yes then either each implementation is a widget (in which case the natural name for the class would be `Piwik\Widget\Widget` I'd say), or either each implement provides widgets (plural) (in which case `Piwik\Widget\WidgetProvider` makes sense)?

**Comment by tsteur** [comment]
For now I put everything under `Piwik\Widget`. Eg `Piwik\Widget\Widget`, `Piwik\Widget\WidgetConfig` etc

**Comment by tsteur** [comment]
Feel free to comment etc if someone has new or more thoughts on this
