### ISSUE TITLE
Row Evolution at Referrer Reports shows 0 visitors on subdatatables

### ISSUE THREAD

**Issue by peterbo** [piwik/piwik#7983]
Reproducible on demo:
- Go to http://demo.piwik.org
- Click through "Referrers" -> "All referrers"
- Expand e.g. "Search engines" in "Referrer Types" Report
- Click on "Row Evolution" Icon of any row.

**Comment by mattab** [comment]
Hi @peterbo 

Thanks for sending the report.

**Comment by tsteur** [comment]
FYI: I'm working on a fix. There was a comment made by @mattab in https://github.com/piwik/piwik/commit/79e71e3491829a2c1a2da309b15228caeb6a4a2e#diff-4a0e53d110e40cb8956ce81246ed49adL107

> // NOTE: not yet possible to do this w/ DataTable\Map instances

It is possible to do this with DataTable\Map instances but I'm not sure if it was not done re performance. It should not have any performance effect re Row evolution (`label` param) since we're not loading it expanded and therefore only set a subtableId (instead of actually requesting the subtable). If this API is fetched expanded though it might do 3 subtable requests for each table in the `DataTable\Map`.
