### ISSUE TITLE
How to track Single Page Applications?

### ISSUE THREAD

**Issue by stefan-niedermann** [piwik/piwik#7998]
As a User i want to be able to track my Single Page Application.
It uses a URL hash as "Page Identifier", like "xyz.com/#links", "xyz.com/#welcome" and so on.

**Comment by quba** [comment]
Enable "Page URL fragments tracking" in Websites settings and manually trigger trackPageView after each site "refresh".

**Comment by stefan-niedermann** [comment]
thanks

**Comment by mattab** [comment]
I am re-opening this issue, as there is a strong need for us to document the best practise around "Measuring Single Page Applications". Let's create a User Guide or at least FAQ with our set of best practises.

**Comment by mattab** [comment]
Maybe there is also potential to build a better tracking API, or build in piwik.js some useful features, to make tracking [single page app](https://en.wikipedia.org/wiki/Single-page_application) better & easier.

For example last week Google released a new tool which helps users measure their single page app:

> URL change tracking for single page applications
> If you're building a single page application that dynamically loads content and updates the URL using the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API), the default tracking snippet will not suffice -- it only tracks the initial page load. Even if you're sending additional pageviews after successfully loading new content, there can still [be complications](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#multiple-hits).
> Autotrack automatically detects URL changes made via the History API and tracks those as pageviews. It also keeps the tracker in sync with the updated URL so all subsequent hits (events, social interactions, etc.) are associated with the correct URL.

(this issue is about creating a FAQ. If we identify potential to also create a new feature in piwik.js we shall create a separate issue)

**Comment by mattab** [comment]
This issue is tracked in: https://github.com/piwik/developer-documentation/issues/90#issuecomment-239576388

If anyone has measured their single page app with Piwik, please let us know any tip or advice in the comments on https://github.com/piwik/developer-documentation/issues/90 - we'd like to write this guide in the future :+1:

**Comment by mattab** [comment]
We've just published the guide, check it out here: [How to track single-page websites and web applications using Piwik Analytics
](https://piwik.org/blog/2017/02/how-to-track-single-page-websites-using-piwik-analytics/)

**Comment by mattab** [comment]
and FAQ: [How do I measure my single-page websites and apps with Piwik?](https://piwik.org/faq/how-to/faq_23636/)

**Comment by pappaschris** [comment]
> We've just published the guide, check it out here: [How to track single-page websites and web applications using Piwik Analytics ](https://piwik.org/blog/2017/02/how-to-track-single-page-websites-using-piwik-analytics/)

The guide covers navigation through location hash changes but History API navigation is not mentioned at all. Is there a best practice recommendation for this case?

**Comment by tsteur** [comment]
You can listen to `window.onpopstate = function(event) {};` instead and make changes depending on your application. It's otherwise pretty much the same.
