### ISSUE TITLE
Improve visitor log UI

### ISSUE THREAD

**Issue by Globulopolis** [piwik/piwik#8052]
Hi!
Below only my vision of improvements which we can do for better UI.

- [ ] Can we do something with the stripped and overlapped texts ?
![untitled-1](https://cloud.githubusercontent.com/assets/740757/8021633/ee901d52-0caf-11e5-807f-191ca7ebf174.jpg)
- [x] Add border around of details. Something like this
![untitled-2](https://cloud.githubusercontent.com/assets/740757/8021666/0a6a3732-0cb1-11e5-9f04-2965b5f62f0e.jpg)
- [ ] Maybe add class `truncated-text-line` for all span's which have truncated text to display black tooltip with the text, instead of default browser tooltip.

**Comment by sgiehl** [comment]
Regarding the second point, it is already fixed: see #7907

**Comment by mattab** [comment]
Hi @Globulopolis 

Please check out 2.14.0-beta which has a better Visitor Log (only two columns instead of 3). this was done in #7812

Marking as closed as most issues you describe should be fixed. of course we are still very keen to hear feedback to improve Visitor Log. Please try 2.14.0 beta and then feel free to create one issue per idea to  further improve the Visitor Log :+1:
