### ISSUE TITLE
Bug: Report in Visitors - Overview shows incorrect values

### ISSUE THREAD

**Issue by iMarkus** [piwik/piwik#8089]
Report in Visitors Overview does not show the correct values. Reproducible at demo.piwik.org

http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=range&date=2015-01-01,2015-01-31#/module=VisitsSummary&action=index&idSite=7&period=range&date=2015-01-01,2015-01-31

Export Data as csv and importing in Excel gives the following:
35292 visits, 31551 unique visitors  

When switching to period=month:

http://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=month&date=2015-01-09#/module=VisitsSummary&action=index&idSite=7&period=month&date=2015-01-09

35292 visits, 27540 unique visitors 

I also noticed differences in the calculation of users on our setup. The Evolution Graph seems to work correctly.

**Comment by mattab** [comment]
Hi @iMarkus 

When you get the count of Unique visitors  per day in one month, and sum these, you will get more than the actual number of Unique Visitors in the month. Unique Visitors is the count of unique people across the whole month, because same person/visitor can visit multiple times. so it's working as expected

**Comment by iMarkus** [comment]
Hi Matthieu,

understand. Thank you so much for the explanation.
