### ISSUE TITLE
Link Known Websites in Incoming List

### ISSUE THREAD

**Issue by stefan-niedermann** [piwik/piwik#8105]
In my Dashboard i use the widget "List of external Pages" - i can see from which pages user are referred to my website.

It would be very fancy, if pages, that are managed by the piwik instance would be directly linked.

Example: I look at the dashboard of Website A and see two other known Websites B and C. A, B and C are managed in my Piwik instance.

![screenshot](https://cloud.githubusercontent.com/assets/4741199/8156922/d6d5262e-1350-11e5-970f-4a7ca5f0c559.png)

Expected behaviour: These Webpages should be linked, so i have a quick access to the dashboard of B and C.

**Comment by mattab** [comment]
Hi there,

These rows represent the "Aggregate row" in this case, it represents the visits from this main domain URL, and below, we list all specific URLs from this domain. 

If you want to see the normal report table, you can click on: `Aggregate rows are shown » Hide them (default)` in the cog icon option. 

I think we don't want to make those rows clickable for now, since actually there was no visitor coming from the website domain itself. So if we linked to the main website domain it would be confusing as Piwik users would think this main domain URL brought some traffic... but often the traffic comes from another page on the website.

**Comment by stefan-niedermann** [comment]
I think you misunderstood me. The two red marked Domains are managed by my Piwik-Installation, too. I do not want to link every domain, i want to link Piwik internal known Domains. Compare my "All Websites Dashboard":

![unbenannt](https://cloud.githubusercontent.com/assets/4741199/8202372/8e6fbe32-14d9-11e5-9a49-960ebd3441b3.png)
