### ISSUE TITLE
Consistent passwords in config file

### ISSUE THREAD

**Issue by quba** [piwik/piwik#8130]
If we have a password to the DB like `something&else` Piwik stores it in config file as `something&amp;else`. Is there something we can do with it? Piwik is able to connect to the DB but it's problematic for administrators when they want to use a password that is available in the config file. And of course it may be really confusing sometimes.

**Comment by mnapoli** [comment]
For the record I believe this is related to this piece of code which uses `htmlentities()`: https://github.com/piwik/piwik/blob/master/core/Config/IniFileChain.php#L422-L423

**Comment by tsteur** [comment]
Maybe also see https://github.com/piwik/piwik/issues/5349 
https://github.com/piwik/piwik/issues/341
https://github.com/piwik/piwik/issues/5409

I think it was due to security reasons and to prevent possible errors. I don't remember the exact reasons anymore. I was confused by this initially as well but afterwards it made sense and I think I remember there was no way around this and we had to keep this behaviour I think. Maybe it's different now

**Comment by mattab** [comment]
and  also #7673  #690 #2968

I suggest it's "wontfix / cant fix"

**Comment by mattab** [comment]
"Wontfix" to prevent a lot of pain (and I don't think it can even be fixed due to INI file limitations)

**Comment by mattab** [comment]
@quba if we need to read password from config file, we could maybe create a console command that outputs the password so it prevents confusion and error. such command would be trivial to add.

**Comment by mattab** [comment]
the command could even output the full mysql command to connect to the DB, with username, db name, password
