### ISSUE TITLE
Test should not read global configuration file

### ISSUE THREAD

**Issue by Preclowski** [piwik/piwik#8187]
Reading config from global configuration file, config.ini.php, occurs in many problems with development. In my opinion separating those configurations may improve development speed and quality and would make tests more reliable.

**Comment by diosmosis** [comment]
Tests should only use global.ini.php for most values, see https://github.com/piwik/piwik/blob/master/tests/PHPUnit/Framework/Mock/TestConfig.php#L46 in master.

Please be more specific and provide a failing test if possible.

**Comment by Preclowski** [comment]
you have two new plugins that have own archivers

PluginA and PluginB

and while executing tests for PluginA (e.g. API tests), there might be an error thrown by archiver of PluginB

it really makes no sense to execute this logic or to make sure that all additional plugins are disabled before running tests

**Comment by diosmosis** [comment]
That is not enough information. It is expected that PluginB would throw an exception failing a test in PluginA, if PluginB is specified in global.ini.php. If it is not, then you will need to provide a failing test, as this is not something I can reproduce.

**Comment by quba** [comment]
@diosmosis both plugins are enabled only in config.ini.php, not in global.

**Comment by diosmosis** [comment]
That information does not help me diagnose what is happening in your situation.

**Comment by Preclowski** [comment]
@diosmosis When I finish those plugins I will create pull request which will explain this situation.

**Comment by mattab** [comment]
When creating a bug report, the minimum is to provide an error message or steps to reproduce the issue. Otherwise it does not help us but it takes us time to try to help and then realise we can't help. We always need a way to reproduce an issue before we can decide how to best address the challenge we face.

**Comment by mattab** [comment]
@Preclowski can you send more information how to reproduce this issue, as so far we could not reproduce it? by design the tests "should" use global config file, and not use config.ini.php so that local configuration does not affect the result of tests. please let us know if it is not working as expected

**Comment by mattab** [comment]
Reopen issue if there is any problem, with steps to reproduce (or example test file etc.)
