### ISSUE TITLE
anonymize the ip after looking up the exact position of the person would be nice.

### ISSUE THREAD

**Issue by Tobias-Conrad** [piwik/piwik#8238]
nobody will be hurt and we can track the right position.

allowed in germany? or EU?

**Comment by tsteur** [comment]
Under `Administration => Privacy` you can enable `Also use the Anonymized IP addresses when enriching visits.` which is probably what you want. Regarding your other questions we cannot provide any legal advice I'm sorry.

**Comment by Tobias-Conrad** [comment]
@tsteur Under Administration => Privacy you can enable Also use the Anonymized IP addresses when enriching visits. which is probably what you want. Regarding your other questions we cannot provide any legal advice I'm sorry.

i know i germany we had to xxx the last the digis of the ip.
A) But i do not know if we can get the exact location from the IP and then anonymize IP.
just tell me what you know and add no lawbased answer only opinion.

B) you added it to milestone, so you will add to search for the location berfore anonymized IP?

**Comment by tsteur** [comment]
A) I don't know it actually. Maybe someone else does?

B) you can enable it yourself, it should already work.

**Comment by Tobias-Conrad** [comment]
B) How can i enable it and still anonymized IP?
C) So what did you add to milestone? will you add this feature?
this is the topic i asked for, i am not clear if you are with me:
anonymize the ip after looking up the exact position of the person would be nice.

**Comment by tsteur** [comment]
B) See 
![privacy_enrich](https://cloud.githubusercontent.com/assets/273120/8419205/19ee6166-1f0c-11e5-9ea6-5e4951486512.png)

C) I just added it as it was "answered" during that milestone. There's nothing to do as it is already possible to do. That's why I closed the issue.

> allowed in germany? or EU?

I'd actually recommend to ask this in the German speaking forum: http://forum.piwik.org/list.php?5
Maybe someone even asked this before
