### ISSUE TITLE
Hong Kong shown in the wrong location on Real-time Map

### ISSUE THREAD

**Issue by feimosi** [piwik/piwik#8275]
It appears on the USA area:
![capture](https://cloud.githubusercontent.com/assets/5721520/8517302/c7307e88-23bf-11e5-96c3-6a0ddcf8f701.JPG)

**Comment by mattab** [comment]
Hi @feimosi 
Are you seeing this problem on the World Map as well as the North america zoom map?

 it's maybe due to a bug in the geo location database, returning wrong lat/long for a Hong Kong visitor... but if you see this bug only in the zoomed map, and not on world map, it's likely a bug in Piwik map algorithm. Thanks for sending more info

**Comment by feimosi** [comment]
Hi, 
It appeared on the World Map as well as on the zoomed part. Then you're saying it's independent of Piwik's algorithms?

**Comment by mattab** [comment]
I think it's independant of Piwik algorithm. To be sure, you can look at browser > Developer Tools > and check the response from the Live API. it contains all visitor info, including the latitude and longitude. Check whether the lat and longitude for this visitor is indeed in the USA or whether it was supposed to be in asia. I assume it works well, and it's a problem with the geo location DB, so closing issue, but I may be wrong, so feel free to reopen!

**Comment by feimosi** [comment]
OK, sure, thanks for the response!
