### ISSUE TITLE
Set fixed packages  versions in composer.json and .gitignore composer.lock

### ISSUE THREAD

**Issue by barbushin** [piwik/piwik#8382]
I know that there is official Composer developers position that `composer.lock` is the best way to set fixed versions of vendors for project. But after working in many many different projects, I found that finally, it's much better just to use fixed versions numbers in `composer.json` and if you google it, you will find many people who think the same way. 

![image](https://cloud.githubusercontent.com/assets/683352/8773456/17f2deba-2edd-11e5-8192-a5ae6836c13b.png)

![image](https://cloud.githubusercontent.com/assets/683352/8773493/5374406e-2edd-11e5-98fd-f984bf050050.png)

See http://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control

May be we should think about it one more time?

_I already confused working with Composer in Piwik, because I add some debug libraries for my local use, and got many conflicts with `composer.lock` that is not listed in `.gitignore`._

**Comment by quba** [comment]
@mgazdzik asked the same question several times and nothing has changed so I'd say that the answer is no (even though it would make my life easier as well).

**Comment by mnapoli** [comment]
The answer in the screenshot (the one from Josh) is out of topic as long as you use `composer install` instead of `composer update` (which is the recommended practice). This is a common mistake, nobody should run composer update unless they actually want to update a dependency. The answer from "jieg" says:

> For application/projects: Yes

Piwik is an application, not a library, so yes we should commit composer.lock (which is what we are doing). I don't see why we should move away from that.

I don't see a reason to use fixed versions, and see the following downsides:

- sometimes we require specific versions because of a specific reasons: in that case we can see it in composer.json and be very careful when updating the version (because we can't add comments in JSON) -> so that's useful to be able to use `~2.1` and in other places `1.4.4`
- we risk updating the versions even less because it's one more step (edit composer.json + run composer update) -> the simpler the workflow is, the better IMO (i.e. just running `composer update thepackage` is good)

Also keep in mind that the good practice of Composer is to commit the composer.lock file for applications (which we are doing). So I'd say it's good to stay with the official best practices.

On the other side, I don't see problems with the current practice (but maybe there are). Could you please list them?

**Comment by barbushin** [comment]
@mnapoli There was a problem for me to use some custom vendors that I added in `composer.json`, and getting conflict in Git switching to different branches.

Matt, thanks for your answer - it's very good explanation of how it works for Piwik.

**Comment by mnapoli** [comment]
It's still open for discussion though if we have particular issues. But your conflicts with composer.json will still be there even if we use fixed version numbers (as this file will stay committed anyway).

**Comment by barbushin** [comment]
@mnapoli Problem is that modified `composer.lock` can't be merged automatically with `composer.lock` of another branch. Merging `composer.json` when switching between branches works fine.

**Comment by gitMomo** [comment]
Including composer.lock in your repository avoids a large memory load on the server. composer uses lots of memory when calculating dependencies, but not when just installing packages.
