### ISSUE TITLE
in Update settings, let user choose "Use the latest release" or "Use the Long Term Support release"

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8549]
The goal of this issue is to give Piwik administrators the ability to choose which Piwik major version they want to use.

## Current Update Settings

![update settings](https://cloud.githubusercontent.com/assets/466765/9199058/84bdc07c-4040-11e5-8cd2-9581cd951395.png)

## Proposed changes to Piwik core

 * When a user selects "Use the latest beta release = **Yes**" then....
  * the very latest beta release will be used 
  * (no change to this behavior)

 * When a user selects "Use the latest beta release = **No**" then....
  * Add a new label "Use the latest release" with two radio buttons:
   * [ ] Yes (recommended, Piwik 3.0.0)
   * [ ] No (use Long Term Support version, Piwik 2.15.1)

## Changes to api.piwik.org service

 * the `https://api.piwik.org/1.0/getLatestVersion/` service needs to be updated to know whether a given Piwik user is on the LTS channel or not
  * Add a new parameter eg. `lts=1` or `use_lts=1`
  * when lts=1, return the last 2.X version
  * when lts=0, return the latest stable release

(fyi: I can make those changes to api.piwik.org whoever works on this please let me know)

## Notes

 * high value to user: from the UI one can choose to use [auto-update](https://piwik.org/docs/update/#the-one-click-piwik-update) to the bleeding edge (beta), the latest stable release (3.X) or the Long Term Support version.
 * This is a change we should make in Piwik 2.15.0 as users need to be able to use the LTS version
   * LTS is announced in https://github.com/piwik/piwik/issues/8546
 * the UI and feature should be designed to auomatically work when we next release Piwik 4.0, Piwik 5.0, etc. ideally we wouldn't need to change anything in Piwik core.

**Comment by mattab** [comment]
* In the Upgrade notification box, to expose this feature clearly, we should tell users that they can choose LTS or latest release in the settings. TBD how

**Comment by thomaszbz** [comment]
Would you please default to LTS for existing 2.x users when they do nothing at all (no selection)? Basically that would mean that users should actively opt-in for 3.0 if they want to. Same for 4.0, 5.0, ...

The reason for that would be that they can easily upgrade to the newer version but downgrading to a LTS release could potentially be painful (schema changes in database etc.). Plus, dependencies for the new version might not be fulfilled.

There should also be a dependency check for the newer version.

**Comment by mattab** [comment]
> Would you please default to LTS for existing 2.x users when they do nothing at all (no selection)? Basically that would mean that users should actively opt-in for 3.0 if they want to. Same for 4.0, 5.0, ...

For us making Piwik it is very helpful when more users are on the latest version. 

Maybe we should not let user update to the latest version and stay instead on LTS, when one or more plugin currently in use are not yet compatible with the latest version. Maybe we could detect this and let users know which plugins are not yet compatible with latest Piwik (looking on Marketplace for available updates, and listing there also any private/other third party plugin) 

in your opinion, why should we default to LTS?

**Comment by thomaszbz** [comment]
> in your opinion, why should we default to LTS?

Because a downgrade back to LTS could be painful: Or can you make sure that database schema downgrades will be working (for years!) without the loss of data?

If you want to default to the new version, users should make at least an explicit choice before they leave LTS.

Personally, using Debian 8, I will go for 3.0.0 as for me there's no reason to stay on Piwik LTS.

**Comment by MagicFab** [comment]
Here are two screenshots on how Debian lets users choose.
![selection_643](https://cloud.githubusercontent.com/assets/317514/9219518/c00232a8-40db-11e5-9977-68a5b97f919f.png)
![selection_644](https://cloud.githubusercontent.com/assets/317514/9219519/c0054768-40db-11e5-8b10-ccdb6c9c3232.png)

Ubuntu has more elaborate conditions about this, IIRC.

**Comment by MagicFab** [comment]
In the same dialogs in Ubuntu the main difference is the mention of LTS versions notifications:
![selection_646](https://cloud.githubusercontent.com/assets/317514/9221789/28295c38-40ed-11e5-9150-893e8a42a220.png)

**Comment by MagicFab** [comment]
The OwnCloud project [recently introduced release channels](https://owncloud.org/release-channels/) to let its users manage stable/LTS vs. other versions in use. This could refine the LTS implementation in Piwik.

**Comment by tsteur** [comment]
Will there be no beta versions for 2.X?

I like the term "release channel". Will use that one

**Comment by mattab** [comment]
> Will there be beta versions for 2.X?

yes 

> Under which URLs can I check for 2.X beta versions if they exist?

Ok, we can move the logic from http://builds.piwik.org/LATEST_BETA to api.piwik.org - I can make the change.

> Under which URLs will the builds be available?

let's keep current URL structure http://builds.piwik.org/piwik-X.Y.0-bZ.zip


The screenshot above looks promising :+1:

**Comment by tsteur** [comment]
Sweet, thx. If you want to test it already, check out https://github.com/piwik/piwik/pull/8688

I just noticed we need to maybe hide or disable certain release channels if requirements are not met, eg because of PHP version. So far it's maybe not a problem yet as Piwik 2.X should run on all servers and if someone selects `latest stable` with PHP 5.3 we would just fallback to Piwik 2.X via `api.piwik.org`. Or should we disable that option in case conditions are not met (and on hover show a title "please update to PHP 5.X to activate this channel")? I kinda like the thought of being able to change requirements in `api.piwik.org` at any time and not having it defined in Piwik and `api.piwik.org`. If we ever change requirements older versions of Piwik won't notice that change as it would be hard coded in Piwik.

I tend to not handle these kinda things right now and just always show all options but up to you.

**Comment by MagicFab** [comment]
Instead of hiding, disabling by whowing them in gray and linking to the system req's check could be helpful. then in System Check such channels being disabled unavailable could be highlighted (related to #8700 ?).

**Comment by tsteur** [comment]
I worked a little on it but noticed it's not that easy and we'd kinda need an API on `api.piwik.org` for this. I could kinda identify whether a release channel is available or not but I would not be able to explain why it is not available since requirements are specified on `api.piwik.org`. I will create a new issue for this

**Comment by tsteur** [comment]
created https://github.com/piwik/piwik/issues/8710
