### ISSUE TITLE
external requests show up in statistics

### ISSUE THREAD

**Issue by babielau** [piwik/piwik#8551]
We have a site A on which a JS tracking code is integrated.

When there is a request on an external website via an iframe, this request from this site shows up in our Piwik statistics:
![example2](https://cloud.githubusercontent.com/assets/8897847/9203420/661479a6-4057-11e5-946d-c367b3ac7edb.png)

Furthermore, there is a link on another site www.example.com/161.html.
This site also shows up in our statistics:
![example](https://cloud.githubusercontent.com/assets/8897847/9203425/6bb90890-4057-11e5-95c5-48b8031ad220.png)

Why is that?
Why couldn't be there an option to exclude all external requests from the statistics or if necessary in a seperate folder where all external requests are consolidated?

**Comment by mattab** [comment]
> When there is a request on an external website via an iframe, this request from this site shows up in our Piwik statistics:

This is by design that we show all requests to your website.

To avoid tracking these requests and only track non-iframed reqs, please use this feature: https://cloud.githubusercontent.com/assets/466765/8591373/290445b2-2628-11e5-8982-ae4f5edf0baa.png

> Furthermore, there is a link on another site www.example.com/161.html.

When another website links to your website, it will show in Referrers > Websites, but not in your Page URLs report. if this shows up in your Page URLs report it's because that other websites has your Javascript tracking code in it.

**Comment by babielau** [comment]
@mattab : Where can I find this feature? I am using Piwik 2.4.13.
