### ISSUE TITLE
Display the "Segmented Visitor Log" icon in Custom Variables report

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8755]
Follows up #7212 - requires  #6031

Let's display the Segmented Visitor Log icon in Custom Variables, this will be so very awesome feature!

**Comment by diosmosis** [comment]
Added to the top level report in https://github.com/piwik/piwik/commit/237f202c7a4ac7b659855d3078ae5a58c1ee3c65

It's not possible to add it subtables w/o requesting the top-level report in the subtable API method. This would be a performance hit so I'm moving this to 3.0.

For 3.0, we should make it possible for idSubtables to be the parent row's label, instead of just an integer ID. This would make it possible to get the row label within the subtable method *and* would increase performance in some cases when it is required to get a subtable by row, w/o having querying the parent table first.

**Comment by mattab** [comment]
Moving back to 2.15.0 - let's close this issue as this is already a new feature, we'll open a new one for the sub-tables icon.

**Comment by diosmosis** [comment]
So then should this be closed?

**Comment by mattab** [comment]
When PR  #7212 will be merged, yes

**Comment by mattab** [comment]
This enhancement already is useful, nice :+1: 

Will be followed up & improved further in #8837
