### ISSUE TITLE
Data discrepancy between events reported using event name vs using event action

### ISSUE THREAD

**Issue by LauraHornbake** [piwik/piwik#8792]
There is a discrepancy between the number of events reported under a particular event action vs the number of events reported under an event name. In the attached screenshots, this translates to different numbers for the url of a file downloaded vs. the filename of the file downloaded.

I've attached two screenshots that show how the numbers reported under event name / Ereignisname (secondary dimension event action is open) and event action / Ereignisaktionen are slightly different. In this case the discrepancy is only 1, but over longer time frames I see larger differences.
<img width="1067" alt="event-name" src="https://cloud.githubusercontent.com/assets/573595/9869726/9896eb8a-5b86-11e5-8ce1-63ed72c7d7cf.png">
![event-actions](https://cloud.githubusercontent.com/assets/573595/9869731/9e85d952-5b86-11e5-85fb-2ef1173ddf06.jpg)

**Comment by mattab** [comment]
Hi @LauraHornbake 
I believe this issue is rather due to the way the data is tracked, maybe one of the event tracking requests didn't have `10_Meldewesen.xls` set correctly... If you experience this bug often, please check your data tagging. if you think there is an issue in piwik feel free to leave another comment
