### ISSUE TITLE
When saving plugin settings, disable the "Save" button to prevent double clicks

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8811]
When saving plugin settings, we should disable the "Save" button to prevent double clicks. Otherwise user may get `Cloud not verify the security token on this form` and believe the form submission failed.

**Comment by sgiehl** [comment]
I'd suggest to do that global for all save buttons (where needed) maybe with a special class or data attribute. Doesn't make sense to find a new solution for every new save button ;)

**Comment by mattab** [comment]
Definitely!

**Comment by mgonera** [comment]
![screencast 2015-09-17 12-01-42](https://cloud.githubusercontent.com/assets/11424829/9930443/f6ef4c46-5d33-11e5-8ee0-3ba92f1f1d04.gif)

**Comment by diosmosis** [comment]
This is what https://docs.angularjs.org/api/ng/directive/ngDisabled is for. Should use this instead of creating a non-angular solution. Though something that bridges jquery/angular will be needed for now.

**Comment by tsteur** [comment]
We cannot really use `ngDisabled` here as there's not an angular component around this that unsets `ngDisabled=` once the request is done/failed. Ideally we would use it though I will see what is possible. Of course we can get the elements scope and reset it but that's a mess. Especially when multiple save buttons are registered in the `root scope` because they do not define their own scope.
