### ISSUE TITLE
Add piwik to the official list of docker images

### ISSUE THREAD

**Issue by pierreozoux** [piwik/piwik#8822]
Hi!

First, thanks for your amazing work, I really enjoy this application!

Did you ever consider putting piwik on the official docker images list?

https://github.com/docker-library/official-images/tree/master/library

If you are interested, I can PR a Dockerfile, and then we can work together to make it official :)

Tell me what you think!

Best!

**Comment by mattab** [comment]
Hi @pierreozoux 

it would make a lot of sense to have an official Docker image for Piwik (and complement our ecosystem of tools such as official Debian package, official SDKs for Android, iOS, C#, etc.)

Since there are already many docker images for Piwik, maybe one would be a good candidate to re-use?

@pierreozoux if you want to lead this project and create the  official Piwik docker image, this would be great for the community.  Feel free to get this started and let us know how this goes! we are happy to help with questions and other support.

**Comment by pierreozoux** [comment]
Thanks @mattab for your quick answer. Yes, I'd be happy to lead the project.

What I need to start the project:
 - [ ] a repo piwik/docker-piwik
 - [ ] a cryptographically signed build (not absolutely necessary, but a lot better) (I searched for it, didn't find it)

Thanks :)

**Comment by mattab** [comment]
@pierreozoux great to hear! created https://github.com/piwik/docker-piwik and gave you admin permission. 

> a cryptographically signed build (not absolutely necessary, but a lot better) (I searched for it, didn't find it)

Do you mean the Piwik build? betas and stable are available at: http://builds.piwik.org/ and the builds are signed: https://piwik.org/blog/2014/11/verify-signatures-piwik-packages/ 

Btw: we could also enable Travis CI for this repository. On each commit, a build is triggered. The build is basically a VM and you can execute anything you want, eg. to run some tests, build some package, etc.

**Comment by pierreozoux** [comment]
Ok, let's switch to: https://github.com/piwik/docker-piwik/issues/1

**Comment by pierreozoux** [comment]
@mattab can you review: https://github.com/piwik/docker-piwik/issues then we can move forward?

Thanks!

**Comment by mattab** [comment]
Hi @pierreozoux I left couple comments. Let me know how I can help you further with releasing a great Piwik Docker toolkit! :+1:
