### ISSUE TITLE
Publicise the LogViewer plugin

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8834]
in #7239 we created a great little LogViewer plugin, letting any Piwik Super User view the [log files](http://piwik.org/faq/troubleshooting/faq_115/) created by Piwik. 

Goal of this issue is to:
 * [x] release LogViewer on the Marketplace
 * advocate & publicise LogViewer plugin via:
  * [x] New FAQ "How do I view Piwik application logs?"
  * [x] Link to it from [faq about logging](http://piwik.org/faq/troubleshooting/faq_115/)
  * [x] Mention the plugin in one or several pages of the [Developer guides](http://developer.piwik.org) at least in [Logging](http://developer.piwik.org/guides/logging) 
 

Maybe you have other ideas?

**Comment by tsteur** [comment]
Plugin is published on the marketplace via http://plugins.piwik.org/LogViewer

**Comment by tsteur** [comment]
What about:

# How do I view Piwik application logs?

You can view logs by installing the [LogViewer plugin](https://plugins.piwik.org/LogViewer). The plugin can be installed via the [Piwik Marketplace](https://plugins.piwik.org) with just a few clicks in your Piwik installation. As a Super User simply go to the `Administration` and select `Marketplace` in the left menu. There you will find the plugin and can install it with just one click.

This plugin will be useful if you experience any problems with your Piwik installation, for example when some tracking requests are not processed correctly.

IMAGE FROM https://raw.githubusercontent.com/piwik/plugin-LogViewer/master/screenshots/LogViewer.png if possible

### Configuring logging in Piwik

By default Piwik won't show anything in the LogViewer plugin as logs are written only to screen. In order to actually view logs you need to enable either logging to `file` or to the `database`. The `database` log writer is recommended when you use more than one server for your Piwik installation.

You can read about this in detail in the [FAQ article How do I enable logging in Piwik](https://piwik.org/faq/troubleshooting/faq_115/).

In most cases it is enough to add the following lines to your `config/config.ini.php` file:

```
[log]
log_writers[] = file
```

If you do not see any log messages afterwards this might be just because there were no warnings or errors yet. You can increase the log level by adding the following line to the `[log]` section to see if it works in general:

```
log_level = DEBUG
```

### Configuring logging for the Piwik Tracker

The Piwik Tracker API needs an additional configuration in order to actually log something. See the documentation page about [enabling Debug logging in the piwik.php tracker](http://developer.piwik.org/api-reference/tracking-api#debugging-the-tracker)

### Using the LogViewer plugin

Once logging is configured you can view the logged messages as a Super User by going to the `Administration` and selecting `LogViewer` from the `Diagnostic` section.

You can search for any log messages, filter by log level, switch between the file and database writer and export log messages. Handy is the possibility to narrow down the displayed messages by clicking on a column. For example you can click on a `RequestId` and see all messages that were logged during the same request.

**Comment by tsteur** [comment]
We can mention it in other parts, such as the logging FAQ and some developer pages once the FAQ article is published

**Comment by tsteur** [comment]
Assigning to @mattab to publish FAQ article

**Comment by mattab** [comment]
@tsteur thanks! Faq published at: [ How do I view Piwik application logs?](https://piwik.org/faq/how-to/faq_20991/)

**Comment by mattab** [comment]
Added "Viewing Logs" section in: http://developer.piwik.org/guides/logging#viewing-logs
