### ISSUE TITLE
Click on menu expands the sub-menu, but do not load first sub-menu page

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9007]
Changes suggested:
 * click on menu item: toggle the submenu (expand/collapse)
 * several submenus can be expanded at the same time

Advantages
 * avoid the display of possibly un-necessary information (flashing data, we try to avoid)
 * one can view the whole structure of reports submenus at once (by expanding reports)

**Comment by tsteur** [comment]
:-1: "for several submenus can be expanded at the same time" and for "one can view the whole structure of reports submenus at once (by expanding reports)" 

The more you click around on different reports over time all categories will be opened and you'll have to scroll a lot and it will be harder to find what you want etc. Then you could directly leave all menus open from the beginning as it is in Admin / User area. After clicking on a view reports it'll look like this:

![image](https://cloud.githubusercontent.com/assets/273120/10512018/9e951ab0-733d-11e5-9879-bf1c06cbab4d.png)

I'd be kinda okay with click on menu item expands the submenu but then it should also close the other one.

If we should still do the expanding of all menus we kinda have to show scrollbars in the menu and make it scrollable similar to GA. Otherwise it will be unusable

**Comment by mattab** [comment]
>  with click on menu item expands the submenu but then it should also close the other one.

Ok let's do it with "close the other one" to keep things tidy and avoid the extra-scroll

**Comment by quba** [comment]
What about the option to temporary hide left menu and search bar?

**Comment by tsteur** [comment]
You mean kinda zen mode? That would be a different feature, wouldn't it?

**Comment by quba** [comment]
Just hide/show like in GA. And yes - it's a different feature. :)

**Comment by tsteur** [comment]
Yep could be done with a bit of work. Once quickly tried to implement it but would need a couple of changes, suggested it here (ZenMode): https://github.com/piwik/piwik/pull/8936 

I'd leave the search bar enabled and only hide the actual menu so one can still change between reports, to another menu item and to other segments, websites, ... without having to enable the left menu

**Comment by tassoman** [comment]
@tsteur where did you binded menuitem's onclick behavior? I'm interested because I would like to work on it for better a11y improvements.

**Comment by tsteur** [comment]
I haven't really changed anything here. I think it is this one here: https://github.com/piwik/piwik/blob/master/plugins/CoreHome/javascripts/menu.js#L101 

In Piwik 3.0 they are normal links via `href` if I remember correctly, I presume that will be better?

**Comment by tassoman** [comment]
In general we should try to avoid "no were going" *a href=""* empty attributes. 
In this case I've dived inside js/jquery menu script too and I found *click()* method were used. Sadly this method excludes focus event that are triggered by keyboard. 
So that I've briefly googled the web and I've found something written about it: [Keyboard Accessibility with Javascript](http://accessibility.athena-ict.com/aria/Javascript-jquery-accessibility.shtml#keyboardJS)
