### ISSUE TITLE
Release AnonymousPiwikUsageMeasurement plugin on the Marketplace

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9051]
Steps:

 * [x] Review plugin's README
 * [x] Confirm https://demo-anonymous.piwik.org is working well 
 * [x] Make  https://demo-anonymous.piwik.org publicly available
 * [x] Publish plugin on Marketplace
 * [x] Create a new FAQ `How do I track and measure how my Piwik service is being used?`
 * [x] Write a little blog post to advertise the plugin and invite people to install it
 * [x] Publish FAQ & blog post once all steps are done

follows up https://github.com/piwik/piwik/issues/4589

**Comment by tsteur** [comment]
I'm not sure if it is an issue with demo-anonymous or Piwik itself or just a configuration... I'm logged in in one browser tab, and have an incognito tab open where I  am not logged in. It always uses the same visitor. So when I'm doing something in incognito custom variable `role = anonymous`, when doing something in other tab `role = superuser`. Both send a different visitor id though (url parameter `_id`). Tried to understand the new code but failed. I'm investigating...

**Comment by tsteur** [comment]
Here's a debug tracker output

```
DEBUG: Matching visitors with: visitorId=396a013f678107c8 OR configId=f6547780a6acb063
DEBUG: The visitor is known (idvisitor = ec0e172c2684ea7a,
DEBUG:                     config_id = f6547780a6acb063,
DEBUG:                     idvisit = 30,
DEBUG:                     last action = Mon, 19 Oct 2015 10:51:32 +0000,
DEBUG:                     first action = Mon, 19 Oct 2015 10:36:05 +0000,
DEBUG:                     visit_goal_buyer' = 0)
```

@mattab @diosmosis this might be actually a bug. I guess `$matchOneFieldOnly` is used and here https://github.com/piwik/piwik/blob/2.15.0-rc3/core/Tracker/Model.php#L339-L342 it doesn't find a matching visitor but does find a matching user because of the same config id. So it uses my other visitor but it is not the same visitor. Should we maybe add a config to force `match both visitor and config`? Trust cookies wouldn't help as it would still do `$shouldLookupOneVisitorFieldOnly = true` and it would still fallback to config id I think.

I reckon many users can run into this issue especially when IP Anonymization is enabled, especially since raw IP address is not considered in config id see https://github.com/piwik/piwik/issues/7778 . It could be likely that two visitors using the same default installation generate the same config id. Also within a company where often same hardware / software is used for hundreds or thousands of employees it is likely that the same config id is generated. 

I might be wrong here as I might not have considered everything. I can imagine especially for Piwik users in Germany where IP Anonymization is enabled this can lead to wrong results.

**Comment by tsteur** [comment]
I've prepared a blog post, feel free to tweak and publish once all the steps are done

**Comment by tsteur** [comment]
Little FAQ entry... BTW: Since when do we call it "Piwik service"? 

### How do I track and measure how my Piwik service is being used?

The plugin [AnonymousPiwikUsageMeasurement](http://plugins.piwik.org/AnonymousPiwikUsageMeasurement) allows you to track usage data of the Piwik service into up to three Piwik installations:

* [demo-anonymous.piwik.org](https://demo-anonymous.piwik.org) (enabled by default, can be disabled).
* your own Piwik (can be configured optionally)
* a custom Piwik (can be configured optionally)

The opt-in and anonymised usage tracking information that is sent to the creators of Piwik will be used to build a better product and a great user experience.

The plugin can be installed via the [Piwik Marketplace](https://plugins.piwik.org) with just a few clicks within your Piwik installation. As a Super User simply go to the Administration and select Marketplace in the left menu. There you will find the plugin and can install it with just one click.

**Comment by mattab** [comment]
@tsteur check out this issue I found on the demo when installing the plugin: https://github.com/piwik/plugin-AnonymousPiwikUsageMeasurement/issues/12

**Comment by mattab** [comment]
> Since when do we call it "Piwik service"? 

Not sure, it's sometimes Piwik server, Piwik infrastructure, Piwik service, Piwik instance, Piwik platform... maybe we should use a consistent name, or maybe not

 > I've prepared a blog post, feel free to tweak and publish once all the steps are done

Great, will publish FAQ + blog post once the couple bugs are fixed and we can use it on demo.piwik.org

**Comment by mattab** [comment]
>I reckon many users can run into this issue especially when IP Anonymization is enabled, especially since raw IP address is not considered in config id see #7778 

Here is an idea to solve this problem and even increase accuracy:
 * we know a given username who is logged in Piwik
 * we could use this username to create an anonymised ID and use it as [User ID](http://piwik.org/docs/user-id/). We could use a hash function to anonimise the User ID.
 * by setting the User ID as the Piwik username, we ensure that the sessions & users are tracked correctly

what do you think?

**Comment by tsteur** [comment]
I think it would be nice to fix this in Piwik itself since it is not really Piwik tracking related. I thought about using user id but there would be still problems with anonymous users and didn't want to send a userid to a public system even when it's "hashed"

**Comment by tsteur** [comment]
With "many users can run into this issue" I mean all Piwik users

**Comment by mattab** [comment]
good find. I re-opened: https://github.com/piwik/piwik/issues/7778#issuecomment-149472972

**Comment by tsteur** [comment]
I removed checkbox "Use Piwik 3.0 on demo-anonymous" as Piwik 3.0 will become master soon anyway. Instead I created an issue to have it compatible with 3.0 which I am working on https://github.com/piwik/plugin-AnonymousPiwikUsageMeasurement/issues/14

**Comment by mattab** [comment]
New blog post [Help us to improve Piwik by sending anonymous usage data (and get usage data yourself)](https://piwik.org/blog/2015/10/help-us-to-improve-piwik-by-sending-anonymous-usage-data-and-get-usage-data-yourself/)

New FAQ: [How do I track and measure how my Piwik service is being used?](http://piwik.org/faq/how-to/faq_20982/)

Also added to [2.15.0 changelog](https://piwik.org/changelog/piwik-2-15-0/)
