### ISSUE TITLE
Simplify bots tracking, bot ignoring and switching between both

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9067]
When setting up a new website and even during daily work one really often would like seeing bots behaviour on the website.
Which one do come? How often do they come? Which sites do they visit? Which sites do they miss? (especially the last point is really important!!)

With standard Piwik config one do not see them.

There are at least two ways to make them visible 
- you can set a parameter to the tracking api see https://github.com/piwik/piwik/issues/3139
- or you use bot tracker plugin see https://github.com/piwik/piwik/issues/2391 and https://github.com/Thomas--F/BotTracker

both ways may work, but they are not very comfortable & not flexible in daily usage

A great solution would be **a simple "switch":
show or hide bots** within everything.

Of course a switch make lots of work to integrate.

=> But what about doing this with a simple new "positive working" segment "include bots"?

So one always track them, but hide them until with segment editor "include bots" is chosen.

**Comment by hpvd** [comment]
easy way to put in visitor log seen bots on bot list is documented in #9182

**Comment by mattab** [comment]
Hi @hpvd 

we possibly could build a new setting  "Also track bots", but we prefer not to at this stage, because Piwik is most valuable when only tracking humans. 

Note that it's possible to specifically track bots with Piwik. See our FAQ: https://piwik.org/faq/new-to-piwik/faq_63/

> Using the Javascript Tracker, you can specifically tell Piwik to track the few advanced bots that will execute Javascript with `_paq.push(['appendToTrackingUrl', 'bots=1']);`

unfortunately this won't set a flag on the visit "is bot" so one can't segment only bots. This could be a feature we build. if you need it feel free to create new issue :)

**Comment by mattab** [comment]
and as you point out, to track bots analytics, there's a good plugin for this http://plugins.piwik.org/BotTracker :+1:
