### ISSUE TITLE
Allow switching to 24h format for languages with AM/PM formatted timestamps as default

### ISSUE THREAD

**Issue by basvdijk** [piwik/piwik#9082]
Since the latest upgrade of Piwik the Visitors in realtime is showing the timestamps as: 
`Thursday, October 22, - 11:14:25 PM` instead of `Thursday, October 22, - 23:14:25`

**Comment by Glisse1** [comment]
Hello, I have posted a thread in forums yesterday for exactly this bug, but i figured i should create a ticket instead. As i can see somebody else already did :)

This is a regression, prior to 2.15 upgrade i have had my time in 24-hour mode. Now, regardless of timezone i tried to change in administration--> website (tried utc, several other cities around the world, again my own city which used to work, etc) the time is always formatted as am/pm 

Tried to hack visitor.serverTimePretty which outputs the localized time myself, with no luck.

This does not affect only the real-time widget but every other report and page that outputs the time of an action or visit, like the full Visitor Log report.

Regards.

**Comment by sgiehl** [comment]
That is based on the language. When you are using are language that uses AM/PM as default.
We may include a setting to switch that later.

**Comment by Glisse1** [comment]
OK, solved for now by changing the language, but i dont think is the right way to go. Many users are facing this change all of a sudden just by upgrading to latest version. I used to have 24 hours while in english. 

As for me, after 30 years of having no translations in my mother-tongue, english is so much more natural to me, i really prefer it... so yeah, a switch or a setting somewhere in admin settings "use 24 hours instead of am/pm" would be very nice to have :+1: 

PS: very nice upgrade overall in 2.15, i really like the left menu design, the improved mobile version of the site, kudos!

**Comment by basvdijk** [comment]
I am from the Netherlands but still prefer English for software. I agree with @Glisse1 that a setting would be nice to have.
