### ISSUE TITLE
Add ability to run scheduled tasks before archiving process

### ISSUE THREAD

**Issue by quba** [piwik/piwik#9214]
I'd like to be able to specify that given scheduled tasks should run before starting real archiving process. Example use case is when I need to fetch 3rd party data (e.g. using API) that is then used while archiving process to generate reports).

**Comment by tsteur** [comment]
FYI: A solution / workaround that works already now would be to listen to some of our http://developer.piwik.org/api-reference/events#cronarchive events. Eg `CronArchive.init.start`. Of course this would only work for CLI archiving, not for browser archiving. 

I'm not sure if we can make scheduled tasks run before real archiving process since they are not directly related together. Scheduled tasks just run at a scheduled time (more or less) and that's all. They are not TasksToRunBefore|AfterArchiving which would be a new API. Maybe there would be even a `Import` API or something and it would be actually the other way around that to run archiving whenever Import was run etc. 

Before working on this we need to think / discuss how we want to handle such things in the future (import of 3rd party data etc which is not really supported yet by Piwik) refs https://github.com/piwik/piwik/issues/8631

**Comment by mattab** [comment]
@quba a workaround could be to use `CronArchive.init.start` for now, until we have more definite idea and use cases.

**Comment by quba** [comment]
Another use case is TrafficGenerator plugin which generates visits via scheduled task.
