### ISSUE TITLE
Discrepancies in Transition pageviews

### ISSUE THREAD

**Issue by andrzejewsky** [piwik/piwik#9367]
Please look at below screenshots:

### 1) Range
![screen 1](https://cloud.githubusercontent.com/assets/7943292/11685051/749f6fd0-9e76-11e5-9bc4-be7a308dfcc8.png)

### 2) Week

![screen 2](https://cloud.githubusercontent.com/assets/7943292/11685060/84fc4862-9e76-11e5-922a-317e22539949.png)

Question is... Why there is not the same number of pageviews?

**Comment by tsteur** [comment]
This is possibly a bug and related to event tracking. We fixed this behaviour just a few days ago in https://github.com/piwik/piwik/pull/9314

I'm not 100% sure but think this bug is actually fixed with the 2.15.1 release (or with the latest beta already). 

Problem: Only new requests that will be tracked will be considered in the fix and existing tracked data will remain like this and show more pageviews. Marking it as a duplicate for now but feel free to reopen or comment any time in case it is not fixed with 2.15.1 (for new tracking requests)
