### ISSUE TITLE
Piwik don't track bots. crawlers and my own curl request

### ISSUE THREAD

**Issue by zdravnik** [piwik/piwik#9441]
Hello everybody.
I use piwik version 2.15.0.
I use track code with api options for track bots (bots=1) and I understand that piwik must be track bots in accordance with piwik docs http://piwik.org/faq/new-to-piwik/faq_63/
My track code:

>< script type="text/javascript">
>var _paq = _paq || [];
>_paq.push(['trackPageView']);
>_paq.push(['enableLinkTracking']);
>_paq.push(['appendToTrackingUrl', 'bots=1']);
>(function() {
>var u="https://mypiwik.ru/";
>_paq.push(['setTrackerUrl', u+'piwik.php']);
>_paq.push(['setSiteId', 3]);
>var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
>g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; > >s.parentNode.insertBefore(g,s);
>})();
>
>< noscript >< p>< img src="https://mypiwik.ru/piwik.php?idsite=3&rec=1&bots=1" > > >style="border:0;" alt="" />

Besides, I instal the BotTracker plugin. But if I make request from curl I didn't view it in piwik, and I don't view bots.
Please help me resolve my issue. Why I don't view any bots?
It`s very important for me.

Thanks 2all.

**Comment by sgiehl** [comment]
Setting `bots=1` only disables the filter in Piwik, that would prevent bots from beeing tracked.

Using JavaScript Tracking (as you do) excludes most bots automatically due to the used technique.
Most bots and crawlers do not interpret javascript or fetch images defined in no script elements. So Piwik does not get much data to display.

If you need to track *all* bots you may need to switch to log analytics (http://piwik.org/log-analytics/) or do the tracking of bots directly using the PHP API

**Comment by mattab** [comment]
see also [ Does Piwik track visitors without Javascript? Does Piwik track search engine bots or other spider / robots?](https://piwik.org/faq/new-to-piwik/faq_63/)
