### ISSUE TITLE
Do not overwrite piwikUrl when host is localhost

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#9481]
When Piwik is accessed via localhost URL then piwikUrl in piwik_option DB table is overwritten with such URL. This is later causing images in e-mail reports being linked to localhost, so they are not displayed. The fix I discussed with @mattab is to make sure that piwikUrl is not overwritten with localhost or 127.0.0.1 etc.

**Comment by tsteur** [comment]
This also applies to 127.0.0.1 or 192.168.*.* , 10.*.*.*

**Comment by tsteur** [comment]
Actually 192.168.. , 10..., ... (private IPs) might be ok if used in an intranet

**Comment by quba** [comment]
What's the reason for updating this value in piwik_option? Woulnd't it possible to just use one specific URL (e.g. the first trusted host)?

**Comment by tsteur** [comment]
I don't know. I reckon it's to use the address that users usually actually use. Say there are 3 trusted hosts mentioned but only one is actually used by all of them. So we use the URL that was actually used. Doesn't really work though when different users use different URLs and would be confusing. So I guess there's another reason for this. Maybe @mattab knows more

**Comment by mattab** [comment]
yes, it's meant to select the Piwik URL that was last used. this feature was implemented before we had trusted hosts entries in the config file... but in general we couldn't unfortunately just use the trusted host, because 1) it would be BC break in 2.X, and 2) Piwik may be installed in a sub-path and the trusted host entries only contain the hostname
