### ISSUE TITLE
Low clickthrough causes overlay to show 0% for links

### ISSUE THREAD

**Issue by mgonera** [piwik/piwik#9575]
With @tsteur we discussed and his thought was that we could maybe on hover show the exact amount of clicks with more detailed % amount like `5 clicks (0.004%)`. I think it's great idea to clear out user concerns about 0% "bubbles" showing up on overlay.

**Comment by mattab** [comment]
What I did for now is a quick solution where it will display the more precise % value ie.

* If value is less than 0.001% (ie. 0.00001) then we show `<0.001%` (less than 0.001%):

![less than](https://cloud.githubusercontent.com/assets/466765/12601906/d0d7b492-c509-11e5-91b8-7462e7dfd49a.png)

* otherwise if clickthrough is between 1 and 10, we show one decimal precision:
![one de](https://cloud.githubusercontent.com/assets/466765/12601929/066c720a-c50a-11e5-850d-91e0de1e3447.png)
