### ISSUE TITLE
total time of visit is not the sum of times of page visits

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9610]
Total time of a visit
shown for a visit e.g. in visitor log
is not always the sum of times of all page visits

an example is shown in attachments

if this total time of a visit is not only shown but also used to calculate other things like avarage duration of a visit, it may have a big imapct

![2016-01-21_11h48_02](https://cloud.githubusercontent.com/assets/5681880/12490532/60092148-c076-11e5-84b4-20bbb1b1e7fc.png)

![2016-01-21_11h49_23](https://cloud.githubusercontent.com/assets/5681880/12490551/79b4919a-c076-11e5-97dc-ab90d7903fd0.png)

![2016-01-21_11h49_04](https://cloud.githubusercontent.com/assets/5681880/12490567/89eb3a46-c076-11e5-9d4f-f838a300b60e.png)

![2016-01-21_11h48_52](https://cloud.githubusercontent.com/assets/5681880/12490580/97deda04-c076-11e5-86cd-383dc35fbfbc.png)

![2016-01-21_11h48_39](https://cloud.githubusercontent.com/assets/5681880/12490595/a44f25fa-c076-11e5-955b-f27d489c7c83.png)

![2016-01-21_11h48_16](https://cloud.githubusercontent.com/assets/5681880/12490623/bf55624c-c076-11e5-875a-834622cd6ab4.png)

**Comment by tsteur** [comment]
What's shown on hover for the 4. action (the search)?

**Comment by hpvd** [comment]
sorry for don 't showing it. I had in the calculation during testing: it's only 11s
![2016-01-21_20h25_30](https://cloud.githubusercontent.com/assets/5681880/12491855/7f02a680-c07d-11e5-9c0d-b316620663a4.png)

**Comment by hpvd** [comment]
in the meantime this visit becomes some longer (only last page)
but still doesn't fit together..

![2016-01-21_20h30_51](https://cloud.githubusercontent.com/assets/5681880/12491952/18493e1c-c07e-11e5-969e-acd601081beb.png)

**Comment by tsteur** [comment]
I can reproduce it on demo.piwik.org for Piwik forums. Thx!

![image](https://cloud.githubusercontent.com/assets/273120/12491974/c8cfb41e-c0e2-11e5-8f78-a7e162144cad.png)

aggregating each action individually only makes like 1hour 15minutes but it shows as 2hours 33min. The 2hours 33 min are probably actually right but some actions might not be updated. The second last action has only 10 seconds so I presume a date was never set there.

**Comment by tsteur** [comment]
The problem is the time spent for the first action should be like an "1hour 15min" or so but is only 10 seconds. By looking very quickly through the code I already found one bug here: https://github.com/piwik/piwik/blob/2.16.0-b6/core/Tracker/Visit.php#L249-L253  . We have a visit standard length of 30 minutes. If time on action spent is > 30 min (which is possible with heart beat feature) we save max 30 minutes for an action instead of the actual "1hour 15min". 

However, as there is 10 seconds set, there must be another bug on top.

Buggy seems also the code just a few lines on top. We probably return max 15 seconds here if we sent ping requests every 15 seconds: https://github.com/piwik/piwik/blob/2.16.0-b6/core/Tracker/Visit.php#L244-L248  Heart beat sends constantly ping requests updating `visit_last_action_time`. So when the next request is happening the `visit_last_action_time` will be probably max 15 seconds. In race conditions the time spent value could be even negative causing 10 seconds to be written as in this case.

From what I can tell it seems quite buggy. Thx for the report!

**Comment by hpvd** [comment]
maybe this one https://github.com/piwik/piwik/issues/9646
is the result of working on this topic...
