### ISSUE TITLE
One single big focus point for each release

### ISSUE THREAD

**Issue by hpvd** [piwik/piwik#9639]
At this time in every Piwik release a lot of different topics are addressed.

One idea is to give this a little more focus by concentrating to one **single big focus point** in every release.
Of course not completely but maybe by 50% of the effort put into a release.
Bug-fixes & security optimizations should be within every release.

The benefits from this would be to
1. work **more focused**
2. being able to address **larger goals**
3. have a **great detailed overview** by bundling all to focus point belonging tickets  to a master ticket
4. have **lots of motivation** because one can see a big progress at the end
5. one can give very easy a very rough but **motivating roadmap** (e.g. Piwik 3.1: Optimize for App Tracking)
6. have a describing **"personal name"** for each release "3.1 b3 App Tracking" instead of "3.1 b3"
7. **ask expert community** for wish-list and feedback (also good point to be within news on expert sites)
8. on release date one can **communicate** one major point **much better** than several small ones
(e.g. "Piwik release 3.1 is optimized for App tracking")
9. be able to give people from different fields a **big reason and concrete date to move to piwik** (e.g. app programmer, ecommerce operators) much more convincing to say: **This release is for YOU** Piwik now perfectly serve all your needs.
10. ...

Just some ideas on possible focus points for future releases:

Enhancement of possibilities in the field of
- ecommerce tracking & analysis
- detailed segmentation
- visitorlog "toolification"
- piwik tracking of apps
- code optimizations for LTS
- check of accuracy & plausibility of tracked data
- cross device tracking
- onsite action tracking
- fast overview
- ...

**=> what do you think of this?**

**Comment by gaumondp** [comment]
I think no one can be against such a vision but as often the case in Open Source culture, developers tend to scratch their won itches... Or those of their clients.

Your priorities may not be mine.

I don't want to make it look personal but since I don't have eCommerce nor have any use for VisitorLog (I see many tickets on this last one, created by you and find it overkill because it's useless for me with 3 millions pageviews a month) if those 2 items are the main focus then it *looks like* 6 months of "useless development" from my point of view (I'm exaggerating). See what I'm trying to say?

So Experts would have all their own priorities.

My "main" own tickets are about Showing Percentages #6182, Annual Report #9435, Segments-on-demand #9396 , Printing Pop-Over #6248 and maybe those are all useless for you !

I'm just trying to be realistic and not add more pressure on our Core Devs here. :)

**Comment by hpvd** [comment]
@gaumondp many thanks for your answer and the topic you are pointing to.

Sure not every big focus point is interesting for everyone.
But even if it's not "your topic" which would be addressed in next release,
you could also benefit from this type of strategy:
1. First of all: only a part of efforts is concentrated to big focus, so small issues of different topics can still be addressed within a release.
2. only a minority of possible "focus points" are that specific as mentioned ecommerce.
From working on lot's of issues their is a big benefit also in other places.
3. the topic list is unsorted -> maybe one can make a vote to fix the order of focus points for e.g. next 18month.
4. when their is the release of "your topic" you got a real huge step and a complete working solution. None complete punctual solutions does not help anyone.
5. with a roadmap of focus point you have for the first time the possibility to plan - when does it make sense to use piwik for your kind project?
6. if this kinds of focused releases could motivate more people to use piwik
(imho there is a big change to do so) there will be a bigger active community in the future.
And with this your topics have a great chance to be addressed earlier.
...

**Comment by tsteur** [comment]
Just to give a quick overview re the next releases. On the blog the LTS version was just announced see http://piwik.org/blog/2016/01/announcing-long-term-support-in-piwik-2-the-analytics-platform-for-your-mission-critical-projects/ . This means we will release 2.16.0 soon and then we will pretty much only add some bug and security fixes in coming updates. I presume after that release we will mainly focus on Piwik 3.0 where we have to do some work in the core to make it easier to bring new features in the future and we will work on one big feature as well (although we will only implement more like a first step towards this) https://github.com/piwik/piwik/issues/4734

**Comment by hpvd** [comment]
many thanks for describing this!
good to see you have already set 2 focusses set for next 12 month:

Feb 2016: 2.16.X **LTS** until second half of 2017 with fixing
- Critical bugs causing data loss or data corruption
- Major and Critical security issues

H2/2016 3.0 **Universal** Build a generic Analytics platform: allow to measure 'Mobile App', 'Intranet Website', 'Wearable', 'Sensor' and more

**That's good to see because both are important!**

Just 3 additional points what one should think of when deciding about future focuses:
1)  Is there a market/community **needing this focus point**?
2) **are we able to give a good solution** for this focus point, because:
- we know **what is needed** in this field (mostly oneself need to be an advanced user within this specific field)
- we have the **possibility to test** our solutions (same thing as above: mostly possible if oneself//some of Piwiks contributor are using it, e.g. see tracking of piwik forum plus heartbeat feature)
3)  is there within focus point a *market share of users who are willing to pay for being perfectly served** with a good working complete solution plus support (sure this is not the most popular point to think of, but it's probably important for Piwik)?

Just a personal conclusion at the end:
Looking at these points and existing issues, maybe a focus point ecommerce is worth to think about.

**Comment by hpvd** [comment]
just to get an impression:
when filtering issues by "ecommerce"
- 68 open issues
- from 18 different authors
are found

**Comment by tsteur** [comment]
We need to update Roadmap indeed @mattab Maybe after the 2.16.0 release.

1) There is a market for sure. The possibilities are almost endless :)

2) We won't be able to give the best solution as a solution that is eg build only for Car tracking will be better than any generic solution but it might be good enough and mid to long term we hope to be able to provide a good alternative to a specific tracking solution.

3) There is for sure. Pretty much anything will be connected and tracked in the future.

It's not only about generic analytics, at at the same time we are forced to improve our platform (which is really good) and it will make it much easier to improve features and add new features so that we can expect to innovate faster in the end.

**Comment by mattab** [comment]
Thanks for the discussion and feedback.

We have two main focus points:
 * Maintain LTS and make it very stable
 * Work on the future of Piwik & innovate: Piwik 3 (blog post will be published in next few weeks about our plans for Piwik 3)

I've slightly updated [the roadmap](http://piwik.org/roadmap/). Any feedback / suggestion welcome.
