### ISSUE TITLE
archive log mixing UTC and local timezone

### ISSUE THREAD

**Issue by valmiRe** [piwik/piwik#9653]
Hi all, I was wondering if there is a problem with the archive process mixing UTC and local timezone.
My timezone is UTC+1, the process logs in UTC, but the last line below is confusing, it mixes UTC (16:05:19) and local timezone (17:20:01)

logs extract of 2 last core:archive runs :
```
INFO [2016-01-28 16:05:19] done
INFO [2016-01-28 16:05:19] ---------------------------
INFO [2016-01-28 16:20:01] ---------------------------
INFO [2016-01-28 16:20:01] INIT
INFO [2016-01-28 16:20:01] Running Piwik 2.15.0 as Super User
INFO [2016-01-28 16:20:01] ---------------------------
INFO [2016-01-28 16:20:01] NOTES
INFO [2016-01-28 16:20:01] - Reports for today will be processed at most every 500 seconds. You can change this value in Piwik UI > Settings > General Settings.
INFO [2016-01-28 16:20:01] - Reports for the current week/month/year will be refreshed at most every 3600 seconds.
INFO [2016-01-28 16:20:01] - Archiving was last executed without error 14 min 42s ago
INFO [2016-01-28 16:20:01] ---------------------------
INFO [2016-01-28 16:20:01] START
INFO [2016-01-28 16:20:01] Starting Piwik reports archiving...
INFO [2016-01-28 16:20:01] - tracking data found for website id 1 (between 2016-01-28 16:05:19 and 2016-01-28 17:20:01)
```

**Comment by tsteur** [comment]
> tracking data found for website id 1 (between 2016-01-28 16:05:19 and 2016-01-28 17:20:01)

Here it is supposed to check whether there were visits since midnight or since the last archive.

I presume your last archive was at `16:05:19` and the cron executed again at `16:20:01`. The query always to detect if there were visits always adds one hour and makes it `17:20:01`. I believe I added the + 1 hour or refactored it but to be honest I don't remember why. There might be eg a feature allowing you to import visitors up to one hour in the "future" and this way it covers it. Anyway, the +1 hour shouldn't "hurt" nor should it cause any problems re performance and data should be still correct.
