### ISSUE TITLE
Add Help links in "Oops, there was a problem during the request" message

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9686]
#### Proposal

![oops](https://cloud.githubusercontent.com/assets/466765/12774423/935ec74a-caa9-11e5-9e38-8210ce7c40d3.png)

#### Proposed code

```
Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Piwik administrator for assistance.
  
  <br /><br />
Need more help? 
<a href="https://piwik.org/faq/troubleshooting/faq_19489/">FAQ</a> – 
<a href="http://forum.piwik.org/">Community Help</a> – 
<a href="https://piwik.pro/?campaigns_params_here">Professional Help</a>.
                    
```

#### Notes

 * by default the links in the error notification are maybe not underline, it would increase usability to add the underline as in screenshot 
 * there are several places in core/plugins where the error message is crafted so code needs to be modified in a few places (MultiSites, CoreHome, Dashboard)

**Comment by tsteur** [comment]
Where are links supposed to go to?

**Comment by dev-101** [comment]
Instead of this approach, Piwik devs should really consider serializing all widgets ajax requests, instead of overloading servers with too many parallel connections. This is not an issue on faster ones, but on budget servers and entry-level shared hosting environments is annoying as hell. I opened this years ago, back when old tracker was used, but it was closed as it could not be reproduced. The main problem is that all widgets load data at the same time, so timeoutes occur when server cannot keep up or small timeout is used (sometimes we cannot change this). Again, leaving option in Admin to load widgets in serialized fashion would prevent this from ever happening.

**Comment by tsteur** [comment]
> Again, leaving option in Admin to load widgets in serialized fashion would prevent this from ever happening.

Not sure what you mean here?

It should be quite fast even on budget server as long as pre-archiving is enabled and browser-archiving disabled. Even on a kinda budget server. If it is still slow on a budget server with configured pre-archiving, the server is simply too small for the Piwik it is handling. With pre-archived all data is pretty much cached and to retrieve data server is only doing some "quick" lookups.

**Comment by dev-101** [comment]
Hi tseur,
well, all widgets create requests at the same time, which does pose a problem when limited concurrent connections are in effect, or RAM/CPU, and that creates timeout errors because server cannot serve all the requests.

In the meantime I have done some optimizations (increased concurrent processes limit, mysql recommended performance tweak and raised PHP memory to the max), so this has apparently fixed the problem.

But, I have root access in this case, in shared hosting accounts that is not possible, and there are various levels of low / cheap / budget.

If widgets could load one-by-one, that is, wait until first completes loading, then trigger next, then next until last one loads would be ideal. Or, at least add some preset delay before it start querying data from the server, to leverage the load.

**Comment by tsteur** [comment]
> If widgets could be loaded one-by-one, that is, wait until first completes loading, then trigger next, then next until last one loads would be ideal.

We'd need like a setting for it or detect if an instance is "slow" somehow as for most instances servers are possibly fast enough
