### ISSUE TITLE
Transitions Feature Not Working. I keep getting "Loading Transitions" indefinitely.

### ISSUE THREAD

**Issue by allen92** [piwik/piwik#9765]
Hello all,

I was wondering if anyone had suggestions on resolving the issue I'm having. Basically what happens is when I click on "Open Transitions" the popup launches and says "Loading Transitions for" but nothing ever actually happens. I've looked around and have not found any solution. Any help will be much appreciated. 

Thanks a million!

**Comment by tsteur** [comment]
Are you familiar with developer tools? Is there maybe a JavaScript error happening?

Is it otherwise possible that you give us access to your Piwik? It would be great if you could create a user with view permission for us and send details to "hello at piwik.org".

**Comment by allen92** [comment]
Ok, thanks. I just sent you the login. @tsteur

**Comment by tsteur** [comment]
Thanks for that, I had a quick look. It seems like your server performs a redirect when requesting transitions and doesn't return any data. Your server may perform a redirect because there is a URL in the  URL such as `` see example URL

http://stats.yourdomain.me/index.php?date=2016-02-12&actionType=url&actionName=http%3A%2F%2Fyourdomainthatyoutrack.com%2F&expanded=1&format=JSON&module=API&method=Transitions.getTransitionsForAction&idSite=1&period=day

Maybe a redirect URL from http to https or something is not correctly written and wants to redirect. Please have a look at the server config or ask a system administrator.

**Comment by tsteur** [comment]
FYI: You can delete the created user again
