### ISSUE TITLE
Error on usercountry:attribute

### ISSUE THREAD

**Issue by Maraumax** [piwik/piwik#9912]
Hello,

On piwik 2.16.0 i got this error when i tried to update user country :
 ```
PHP Fatal error:  Call to protected method Piwik\Plugins\UserCountry\Commands\AttributeHistoricalDataWithLocations::onVisitProcessed() from context '' in plugins/UserCountry/Commands/AttributeHistoricalDataWithLocations.php on line 120
```

Another user got [this error](https://forum.piwik.org/t/bug-when-trying-to-re-attribute-visits-with-new-geoip-provider/16934). I just updated my geoip file.

**Comment by tsteur** [comment]
Thank you for the bug report. I issues a fix for this and it should be fixed with the next update of Piwik. Meanwhile you could try to fix it by changing one word in file `plugins/UserCountry/Commands/AttributeHistoricalDataWithLocations.php` on your server see https://github.com/piwik/piwik/pull/9915/files#diff-cd85f7dcd7b94984947e0cc41d8dbe19L148 .

**Comment by Maraumax** [comment]
Thanks @tsteur and @mattab for your work! I will try that tomorrow.
